// Code generated by forge const -- DO NOT EDIT.
//
//   source: amp.consts.sdl

package amp

import "github.com/art-media-platform/amp.SDK/stdlib/tag"

var (
	// The bootstrapping ("head") node — well-known channel UID hosting planet
	// governance records (PlanetEpoch, MemberEpoch, ChannelEpoch) and session
	// meta-ops (Login, PlanetInviteOp).  Deterministic across all planets.
	HeadNodeID = tag.UID{0x0, 0x37}
)

const (
	// Connection-type prefix — the first 4 bytes a peer writes on a new amp.Host TCP
	// connection so the host demultiplexes traffic types on one port without rewinding
	// the stream.  A client login connection continues with a TxMsg stream (whose own
	// preamble is Tx.PreambleSignature); a vault peer continues with sync framing.
	// New traffic types add a new prefix here.
	ClientLoginMagic = "AMPL" // client login / session connection
	VaultAccessMagic = "AMPV" // node-to-node vault sync peer connection
	// Default TCP port used to expose amp.Host service.
	DefaultServicePort = int32(5192)
	// בְּרֵאשִׁ֖ית בָּרָ֣א אֱלֹהִ֑ים אֵ֥ת הַשָּׁמַ֖יִם וְאֵ֥ת הָאָֽרֶץ
	// oh Lord, please bless this project, those who fight for it, and those who lay their life on Your altar...
	// now let us get to work!
	Invocation = int32(3773)
)

// ─── TxMsg wire framing ─────────────────────────────────────────
const (
	// TxPreamble layout (big endian):
	//
	//    00:04  PreambleSignature ("AMP1")
	//    04:08  PreambleSize + serialized(TxHeader) + serialized([]TxOp)
	//    08:12  len(TxMsg.DataStore)
	//    12:14  SignatureLength (uint16 BE; 0 = unsigned)
	//    14:16  Reserved
	TxPreambleSignature = "AMP1"
	// Fixed-size header that leads every TxMsg (see amp.consts.sdl for layout).
	TxPreambleSize = int32(16)
)
