// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: amp/amp.term.proto

// TermIO is the wire frame for amp.Terminal — a teletype that rides an amp
// channel.  One frame is one CRDT append at (sessionNode, terminal series attr,
// ItemID).  The ItemID is a UID stamped when the batch flushes (capture time,
// not commit time): a UID's leading six bytes are UTC seconds, so the series is
// time-ordered by capture with no timestamp field, and a delayed or offline
// commit preserves the original order.  The persisted series is a read-only
// "console"; its live tail driven interactively is a "terminal".
// See AOM/design-specs/AD-app-terminal.md.

package amp

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TermDir is the flow direction of a terminal byte block.
type TermBlock_TermDir int32

const (
	TermBlock_Unspecified  TermBlock_TermDir = 0
	TermBlock_HostToClient TermBlock_TermDir = 1 // PTY output  -> client stdout
	TermBlock_ClientToHost TermBlock_TermDir = 2 // keystrokes  -> PTY stdin
)

// Enum value maps for TermBlock_TermDir.
var (
	TermBlock_TermDir_name = map[int32]string{
		0: "Unspecified",
		1: "HostToClient",
		2: "ClientToHost",
	}
	TermBlock_TermDir_value = map[string]int32{
		"Unspecified":  0,
		"HostToClient": 1,
		"ClientToHost": 2,
	}
)

func (x TermBlock_TermDir) Enum() *TermBlock_TermDir {
	p := new(TermBlock_TermDir)
	*p = x
	return p
}

func (x TermBlock_TermDir) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TermBlock_TermDir) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_amp_term_proto_enumTypes[0].Descriptor()
}

func (TermBlock_TermDir) Type() protoreflect.EnumType {
	return &file_amp_amp_term_proto_enumTypes[0]
}

func (x TermBlock_TermDir) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TermBlock_TermDir.Descriptor instead.
func (TermBlock_TermDir) EnumDescriptor() ([]byte, []int) {
	return file_amp_amp_term_proto_rawDescGZIP(), []int{0, 0}
}

// TermBlock is one contiguous run of terminal bytes — typically one PTY read.
// Blocks within a TermIO are ordered; concatenating their Data reproduces the
// raw stream.
type TermBlock struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw, opaque terminal bytes.  Never UTF-8-validated or transformed; ANSI is
	// rendered only by the receiving emulator.
	Data []byte `protobuf:"bytes,1,opt,name=Data,proto3" json:"Data,omitempty"`
	// Monotonic byte offset of this block's first byte from session start in this
	// direction.  Lets a receiver detect a gap (a dropped laggard) and order or
	// dedupe blocks independently of arrival.
	SeqOffset int64 `protobuf:"varint,2,opt,name=SeqOffset,proto3" json:"SeqOffset,omitempty"`
	// Flow direction.  Per block so a captured batch is self-describing and a
	// future muxed stream stays valid.
	Dir           TermBlock_TermDir `protobuf:"varint,4,opt,name=Dir,proto3,enum=amp.TermBlock_TermDir" json:"Dir,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermBlock) Reset() {
	*x = TermBlock{}
	mi := &file_amp_amp_term_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermBlock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermBlock) ProtoMessage() {}

func (x *TermBlock) ProtoReflect() protoreflect.Message {
	mi := &file_amp_amp_term_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermBlock.ProtoReflect.Descriptor instead.
func (*TermBlock) Descriptor() ([]byte, []int) {
	return file_amp_amp_term_proto_rawDescGZIP(), []int{0}
}

func (x *TermBlock) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TermBlock) GetSeqOffset() int64 {
	if x != nil {
		return x.SeqOffset
	}
	return 0
}

func (x *TermBlock) GetDir() TermBlock_TermDir {
	if x != nil {
		return x.Dir
	}
	return TermBlock_Unspecified
}

// TermIO is one flush of batched terminal I/O for a single session/stream.
type TermIO struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic batch sequence within the session+direction (0,1,2,...).  Earns
	// its place precisely because the series is sparse: a time gap is normal
	// (idle), so this counter is how a reader tells idle apart from a dropped
	// frame.  SeqOffset gives byte-exact detail within a direction.
	BatchSeq uint64 `protobuf:"varint,5,opt,name=BatchSeq,proto3" json:"BatchSeq,omitempty"`
	// Keyframe marks a self-contained full-screen snapshot — a repaint of the
	// visible grid a reader can apply without any prior frame.  It is the DVR's
	// scrub seek target: jump to the nearest keyframe <= T, then replay forward
	// to T.  Ordinary output frames leave it false.
	Keyframe bool `protobuf:"varint,7,opt,name=Keyframe,proto3" json:"Keyframe,omitempty"`
	// The ordered byte blocks in this flush.  Concatenate Data in order to
	// reconstruct the raw stream.
	Blocks        []*TermBlock `protobuf:"bytes,10,rep,name=Blocks,proto3" json:"Blocks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TermIO) Reset() {
	*x = TermIO{}
	mi := &file_amp_amp_term_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TermIO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TermIO) ProtoMessage() {}

func (x *TermIO) ProtoReflect() protoreflect.Message {
	mi := &file_amp_amp_term_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TermIO.ProtoReflect.Descriptor instead.
func (*TermIO) Descriptor() ([]byte, []int) {
	return file_amp_amp_term_proto_rawDescGZIP(), []int{1}
}

func (x *TermIO) GetBatchSeq() uint64 {
	if x != nil {
		return x.BatchSeq
	}
	return 0
}

func (x *TermIO) GetKeyframe() bool {
	if x != nil {
		return x.Keyframe
	}
	return false
}

func (x *TermIO) GetBlocks() []*TermBlock {
	if x != nil {
		return x.Blocks
	}
	return nil
}

var File_amp_amp_term_proto protoreflect.FileDescriptor

const file_amp_amp_term_proto_rawDesc = "" +
	"\n" +
	"\x12amp/amp.term.proto\x12\x03amp\"\xa7\x01\n" +
	"\tTermBlock\x12\x12\n" +
	"\x04Data\x18\x01 \x01(\fR\x04Data\x12\x1c\n" +
	"\tSeqOffset\x18\x02 \x01(\x03R\tSeqOffset\x12(\n" +
	"\x03Dir\x18\x04 \x01(\x0e2\x16.amp.TermBlock.TermDirR\x03Dir\">\n" +
	"\aTermDir\x12\x0f\n" +
	"\vUnspecified\x10\x00\x12\x10\n" +
	"\fHostToClient\x10\x01\x12\x10\n" +
	"\fClientToHost\x10\x02\"h\n" +
	"\x06TermIO\x12\x1a\n" +
	"\bBatchSeq\x18\x05 \x01(\x04R\bBatchSeq\x12\x1a\n" +
	"\bKeyframe\x18\a \x01(\bR\bKeyframe\x12&\n" +
	"\x06Blocks\x18\n" +
	" \x03(\v2\x0e.amp.TermBlockR\x06BlocksB@Z)github.com/art-media-platform/amp.SDK/amp\xaa\x02\x12art.media.platformb\x06proto3"

var (
	file_amp_amp_term_proto_rawDescOnce sync.Once
	file_amp_amp_term_proto_rawDescData []byte
)

func file_amp_amp_term_proto_rawDescGZIP() []byte {
	file_amp_amp_term_proto_rawDescOnce.Do(func() {
		file_amp_amp_term_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amp_amp_term_proto_rawDesc), len(file_amp_amp_term_proto_rawDesc)))
	})
	return file_amp_amp_term_proto_rawDescData
}

var file_amp_amp_term_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_amp_amp_term_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_amp_amp_term_proto_goTypes = []any{
	(TermBlock_TermDir)(0), // 0: amp.TermBlock.TermDir
	(*TermBlock)(nil),      // 1: amp.TermBlock
	(*TermIO)(nil),         // 2: amp.TermIO
}
var file_amp_amp_term_proto_depIdxs = []int32{
	0, // 0: amp.TermBlock.Dir:type_name -> amp.TermBlock.TermDir
	1, // 1: amp.TermIO.Blocks:type_name -> amp.TermBlock
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_amp_amp_term_proto_init() }
func file_amp_amp_term_proto_init() {
	if File_amp_amp_term_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amp_amp_term_proto_rawDesc), len(file_amp_amp_term_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amp_amp_term_proto_goTypes,
		DependencyIndexes: file_amp_amp_term_proto_depIdxs,
		EnumInfos:         file_amp_amp_term_proto_enumTypes,
		MessageInfos:      file_amp_amp_term_proto_msgTypes,
	}.Build()
	File_amp_amp_term_proto = out.File
	file_amp_amp_term_proto_goTypes = nil
	file_amp_amp_term_proto_depIdxs = nil
}
