// Code generated by forge const -- DO NOT EDIT.
//
//   source: safe.consts.sdl

package safe

import "github.com/art-media-platform/amp.SDK/stdlib/tag"

var Crypto = struct {
	Poly25519 tag.Name
	P256      tag.Name
	Secp256k1 tag.Name
}{
	Poly25519: tag.Name{ID: tag.UID{0x629134B84734DA6F, 0xCC870AD1BB12E1E6}, Text: "amp.crypto.poly25519"}, // 32k-4uchjtnv9r-wt1sbu6xj5-sg6
	P256:      tag.Name{ID: tag.UID{0x188DC92BB63ACCBD, 0xE22053F8FFA3A09F}, Text: "amp.crypto.p256"},      // 0sj-r4krejutky-y482mz3zu7-84z
	Secp256k1: tag.Name{ID: tag.UID{0x1906FAF4F88AB854, 0x6328B92D89014254}, Text: "amp.crypto.secp256k1"}, // 0t0-vxg9y4br1b-66b5t5q4h2-hkn
}

// ─── Phrase — the canonical safe.Phrase vocabulary (SD-did-identity §12.1): a ───
// phrase written down in one AMP app must restore in any other, so every
// consumer (Go, C#, web) parses this ONE whitespace-separated string at
// runtime.  Properties:
//   - exactly 256 unique words (8 bits/word → byte-aligned entropy)
//   - short (4–7 characters), common, casual-English familiar
//   - no two list words are homophones of each other
//   - unique on the first FOUR characters (three-char prefixes are NOT
//     unique — abbreviation entry needs at least four typed characters)
//   - alphabetized for reviewability
//
// Any change to this list is a breaking change — existing phrases become
// unparseable; the golden fixtures in stdlib/safe and amp-web trip on any
// byte motion here.
const (
	PhraseWords = "\nable acid acre agent album alert alien alloy amber anchor angel ankle apple arena armor artist\natlas atom auto avid awake axis baby bacon badge baker balm band bark barn base bath\nbeach beam bear bench berry bike bill bird black blade blaze bliss block blood blue blur\nboard boat bolt bone book boot born bottle brain brass brave bread brick bridge brook brown\nbrush buddy budget build bulb bunny cabin cable cake calm camel candy canyon cargo carrot castle\ncave center chair cherry chest chime chip church circle cliff clock cloud coast cobra comet copper\ncoral cosmic cotton couch cradle crane crate crown crystal cube daisy dance dart dawn deep desk\ndiamond disco doll dome donut dove dozen drift drum dune dusk eagle earth echo edge ember\nemerald energy evil falcon feast feather felt ferry field flag flame fleece flower flute focus forge\nframe frost fuel galaxy gate giant glacier globe glow golden grape gravel green grove guard harbor\nharvest hatch hawk heart helmet hero hickory honey hood horizon horn island ivory jade jelly kelp\nkitten ladder lantern laser lemon linen lotus lunar magnet maple marble meadow melon mint moss needle\nnickel north ocean olive opal orchid otter oyster paper parade peach pebble petal piano pine pixel\nplanet poem puzzle quiet quiz radio raven ribbon river robot rodeo rope rose rust saber safari\nsalt satin scout shadow silver smoke snow solar sonic spark spire spruce star steel stone storm\nsugar summit swan taxi tiger torch tulip ultra urban valley velvet violet wagon wolf yellow zebra\n"
)
