// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: amp/std/amp.std.proto

package std

import (
	amp "github.com/art-media-platform/amp.SDK/amp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TRS_Flags int32

const (
	TRS_Flags_FixedScale TRS_Flags = 0
	TRS_Flags_AutoScale  TRS_Flags = 1 // Dynamically adjust scale based on observer position.
)

// Enum value maps for TRS_Flags.
var (
	TRS_Flags_name = map[int32]string{
		0: "FixedScale",
		1: "AutoScale",
	}
	TRS_Flags_value = map[string]int32{
		"FixedScale": 0,
		"AutoScale":  1,
	}
)

func (x TRS_Flags) Enum() *TRS_Flags {
	p := new(TRS_Flags)
	*p = x
	return p
}

func (x TRS_Flags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TRS_Flags) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_std_amp_std_proto_enumTypes[0].Descriptor()
}

func (TRS_Flags) Type() protoreflect.EnumType {
	return &file_amp_std_amp_std_proto_enumTypes[0]
}

func (x TRS_Flags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TRS_Flags.Descriptor instead.
func (TRS_Flags) EnumDescriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{0}
}

// ValueKind specfies the primary type of a JsonValue.
type ValueKind int32

const (
	ValueKind_Null   ValueKind = 0
	ValueKind_False  ValueKind = 1
	ValueKind_True   ValueKind = 2
	ValueKind_Number ValueKind = 3
	ValueKind_String ValueKind = 4
)

// Enum value maps for ValueKind.
var (
	ValueKind_name = map[int32]string{
		0: "Null",
		1: "False",
		2: "True",
		3: "Number",
		4: "String",
	}
	ValueKind_value = map[string]int32{
		"Null":   0,
		"False":  1,
		"True":   2,
		"Number": 3,
		"String": 4,
	}
)

func (x ValueKind) Enum() *ValueKind {
	p := new(ValueKind)
	*p = x
	return p
}

func (x ValueKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueKind) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_std_amp_std_proto_enumTypes[1].Descriptor()
}

func (ValueKind) Type() protoreflect.EnumType {
	return &file_amp_std_amp_std_proto_enumTypes[1]
}

func (x ValueKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueKind.Descriptor instead.
func (ValueKind) EnumDescriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{1}
}

type PointFormat int32

const (
	PointFormat_S2  PointFormat = 0 // (S2)      (1) uint64: lat,lng, (res)
	PointFormat_H3  PointFormat = 1 // (H3)      (1) uint64: lat,lng, (res)
	PointFormat_S2T PointFormat = 2 // (S2, T)   (2) uint64: lat,lng, (res), UTC64
	PointFormat_H3T PointFormat = 3 // (H3, T)   (2) uint64: lat,lng, (res), UTC64
)

// Enum value maps for PointFormat.
var (
	PointFormat_name = map[int32]string{
		0: "S2",
		1: "H3",
		2: "S2T",
		3: "H3T",
	}
	PointFormat_value = map[string]int32{
		"S2":  0,
		"H3":  1,
		"S2T": 2,
		"H3T": 3,
	}
)

func (x PointFormat) Enum() *PointFormat {
	p := new(PointFormat)
	*p = x
	return p
}

func (x PointFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PointFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_std_amp_std_proto_enumTypes[2].Descriptor()
}

func (PointFormat) Type() protoreflect.EnumType {
	return &file_amp_std_amp_std_proto_enumTypes[2]
}

func (x PointFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PointFormat.Descriptor instead.
func (PointFormat) EnumDescriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{2}
}

type MediaFlags int32

const (
	MediaFlags_NoMedia      MediaFlags = 0
	MediaFlags_IsLive       MediaFlags = 1
	MediaFlags_IsSeekable   MediaFlags = 2
	MediaFlags_IsUnending   MediaFlags = 4
	MediaFlags_NewChapter   MediaFlags = 8
	MediaFlags_NewTrack     MediaFlags = 16
	MediaFlags_HasAudio     MediaFlags = 256
	MediaFlags_HasVideo     MediaFlags = 512
	MediaFlags_HasSpeech    MediaFlags = 1024
	MediaFlags_NeedsNetwork MediaFlags = 2048
	// When set, the user is more likely to skipping short intervals than switch media items.
	MediaFlags_SkipIsLikely MediaFlags = 16777216
)

// Enum value maps for MediaFlags.
var (
	MediaFlags_name = map[int32]string{
		0:        "NoMedia",
		1:        "IsLive",
		2:        "IsSeekable",
		4:        "IsUnending",
		8:        "NewChapter",
		16:       "NewTrack",
		256:      "HasAudio",
		512:      "HasVideo",
		1024:     "HasSpeech",
		2048:     "NeedsNetwork",
		16777216: "SkipIsLikely",
	}
	MediaFlags_value = map[string]int32{
		"NoMedia":      0,
		"IsLive":       1,
		"IsSeekable":   2,
		"IsUnending":   4,
		"NewChapter":   8,
		"NewTrack":     16,
		"HasAudio":     256,
		"HasVideo":     512,
		"HasSpeech":    1024,
		"NeedsNetwork": 2048,
		"SkipIsLikely": 16777216,
	}
)

func (x MediaFlags) Enum() *MediaFlags {
	p := new(MediaFlags)
	*p = x
	return p
}

func (x MediaFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_std_amp_std_proto_enumTypes[3].Descriptor()
}

func (MediaFlags) Type() protoreflect.EnumType {
	return &file_amp_std_amp_std_proto_enumTypes[3]
}

func (x MediaFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaFlags.Descriptor instead.
func (MediaFlags) EnumDescriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{3}
}

type ColormapFlags int32

const (
	ColormapFlags_ColormapFlags_None ColormapFlags = 0
	ColormapFlags_ColormapFlags_Full ColormapFlags = 1
	ColormapFlags_ColormapFlags_Back ColormapFlags = 2
	ColormapFlags_ColormapFlags_Fore ColormapFlags = 4
)

// Enum value maps for ColormapFlags.
var (
	ColormapFlags_name = map[int32]string{
		0: "ColormapFlags_None",
		1: "ColormapFlags_Full",
		2: "ColormapFlags_Back",
		4: "ColormapFlags_Fore",
	}
	ColormapFlags_value = map[string]int32{
		"ColormapFlags_None": 0,
		"ColormapFlags_Full": 1,
		"ColormapFlags_Back": 2,
		"ColormapFlags_Fore": 4,
	}
)

func (x ColormapFlags) Enum() *ColormapFlags {
	p := new(ColormapFlags)
	*p = x
	return p
}

func (x ColormapFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ColormapFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_std_amp_std_proto_enumTypes[4].Descriptor()
}

func (ColormapFlags) Type() protoreflect.EnumType {
	return &file_amp_std_amp_std_proto_enumTypes[4]
}

func (x ColormapFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ColormapFlags.Descriptor instead.
func (ColormapFlags) EnumDescriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{4}
}

type SensorFlags int32

const (
	SensorFlags_SensorFlags_None   SensorFlags = 0
	SensorFlags_SensorFlags_GyroUp SensorFlags = 1
)

// Enum value maps for SensorFlags.
var (
	SensorFlags_name = map[int32]string{
		0: "SensorFlags_None",
		1: "SensorFlags_GyroUp",
	}
	SensorFlags_value = map[string]int32{
		"SensorFlags_None":   0,
		"SensorFlags_GyroUp": 1,
	}
)

func (x SensorFlags) Enum() *SensorFlags {
	p := new(SensorFlags)
	*p = x
	return p
}

func (x SensorFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SensorFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_std_amp_std_proto_enumTypes[5].Descriptor()
}

func (SensorFlags) Type() protoreflect.EnumType {
	return &file_amp_std_amp_std_proto_enumTypes[5]
}

func (x SensorFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SensorFlags.Descriptor instead.
func (SensorFlags) EnumDescriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{5}
}

type AudioFlags int32

const (
	AudioFlags_AudioFlags_None AudioFlags = 0
	AudioFlags_AudioFlags_FFT  AudioFlags = 1
)

// Enum value maps for AudioFlags.
var (
	AudioFlags_name = map[int32]string{
		0: "AudioFlags_None",
		1: "AudioFlags_FFT",
	}
	AudioFlags_value = map[string]int32{
		"AudioFlags_None": 0,
		"AudioFlags_FFT":  1,
	}
)

func (x AudioFlags) Enum() *AudioFlags {
	p := new(AudioFlags)
	*p = x
	return p
}

func (x AudioFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AudioFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_std_amp_std_proto_enumTypes[6].Descriptor()
}

func (AudioFlags) Type() protoreflect.EnumType {
	return &file_amp_std_amp_std_proto_enumTypes[6]
}

func (x AudioFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AudioFlags.Descriptor instead.
func (AudioFlags) EnumDescriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{6}
}

type GeoPath_RenderType int32

const (
	GeoPath_Point GeoPath_RenderType = 0
	GeoPath_Path  GeoPath_RenderType = 1
	GeoPath_Ring  GeoPath_RenderType = 2
)

// Enum value maps for GeoPath_RenderType.
var (
	GeoPath_RenderType_name = map[int32]string{
		0: "Point",
		1: "Path",
		2: "Ring",
	}
	GeoPath_RenderType_value = map[string]int32{
		"Point": 0,
		"Path":  1,
		"Ring":  2,
	}
)

func (x GeoPath_RenderType) Enum() *GeoPath_RenderType {
	p := new(GeoPath_RenderType)
	*p = x
	return p
}

func (x GeoPath_RenderType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GeoPath_RenderType) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_std_amp_std_proto_enumTypes[7].Descriptor()
}

func (GeoPath_RenderType) Type() protoreflect.EnumType {
	return &file_amp_std_amp_std_proto_enumTypes[7]
}

func (x GeoPath_RenderType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GeoPath_RenderType.Descriptor instead.
func (GeoPath_RenderType) EnumDescriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{10, 0}
}

// TRS (Translate Rotate Scale) IEEE 1207
// General purpose placement time, space, orientation, and/or geo-position.
type TRS struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Uniform spatial scale; if 0, scale is implicitly 1.0
	Sx float64 `protobuf:"fixed64,1,opt,name=Sx,proto3" json:"Sx,omitempty"`
	// Special TRS behavior
	Flags TRS_Flags `protobuf:"varint,2,opt,name=Flags,proto3,enum=std.TRS_Flags" json:"Flags,omitempty"`
	// Spatial position
	Px float64 `protobuf:"fixed64,3,opt,name=Px,proto3" json:"Px,omitempty"`
	Py float64 `protobuf:"fixed64,4,opt,name=Py,proto3" json:"Py,omitempty"`
	Pz float64 `protobuf:"fixed64,5,opt,name=Pz,proto3" json:"Pz,omitempty"`
	// Spatial rotation; if all values 0, Quaternion is unit identity
	Qx float64 `protobuf:"fixed64,10,opt,name=Qx,proto3" json:"Qx,omitempty"`
	Qy float64 `protobuf:"fixed64,11,opt,name=Qy,proto3" json:"Qy,omitempty"`
	Qz float64 `protobuf:"fixed64,12,opt,name=Qz,proto3" json:"Qz,omitempty"`
	Qw float64 `protobuf:"fixed64,13,opt,name=Qw,proto3" json:"Qw,omitempty"`
	// If non-zero and a globe surface is defined, this TRS is applied from the spherical position, normal, and scale associated with the given S2 tile cell.
	TileS2        uint64 `protobuf:"fixed64,16,opt,name=TileS2,proto3" json:"TileS2,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TRS) Reset() {
	*x = TRS{}
	mi := &file_amp_std_amp_std_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TRS) ProtoMessage() {}

func (x *TRS) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TRS.ProtoReflect.Descriptor instead.
func (*TRS) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{0}
}

func (x *TRS) GetSx() float64 {
	if x != nil {
		return x.Sx
	}
	return 0
}

func (x *TRS) GetFlags() TRS_Flags {
	if x != nil {
		return x.Flags
	}
	return TRS_Flags_FixedScale
}

func (x *TRS) GetPx() float64 {
	if x != nil {
		return x.Px
	}
	return 0
}

func (x *TRS) GetPy() float64 {
	if x != nil {
		return x.Py
	}
	return 0
}

func (x *TRS) GetPz() float64 {
	if x != nil {
		return x.Pz
	}
	return 0
}

func (x *TRS) GetQx() float64 {
	if x != nil {
		return x.Qx
	}
	return 0
}

func (x *TRS) GetQy() float64 {
	if x != nil {
		return x.Qy
	}
	return 0
}

func (x *TRS) GetQz() float64 {
	if x != nil {
		return x.Qz
	}
	return 0
}

func (x *TRS) GetQw() float64 {
	if x != nil {
		return x.Qw
	}
	return 0
}

func (x *TRS) GetTileS2() uint64 {
	if x != nil {
		return x.TileS2
	}
	return 0
}

type Matrix4X4 struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 16 doubles in row-major order
	M00           float64 `protobuf:"fixed64,1,opt,name=M00,proto3" json:"M00,omitempty"`
	M01           float64 `protobuf:"fixed64,2,opt,name=M01,proto3" json:"M01,omitempty"`
	M02           float64 `protobuf:"fixed64,3,opt,name=M02,proto3" json:"M02,omitempty"`
	M03           float64 `protobuf:"fixed64,4,opt,name=M03,proto3" json:"M03,omitempty"`
	M10           float64 `protobuf:"fixed64,5,opt,name=M10,proto3" json:"M10,omitempty"`
	M11           float64 `protobuf:"fixed64,6,opt,name=M11,proto3" json:"M11,omitempty"`
	M12           float64 `protobuf:"fixed64,7,opt,name=M12,proto3" json:"M12,omitempty"`
	M13           float64 `protobuf:"fixed64,8,opt,name=M13,proto3" json:"M13,omitempty"`
	M20           float64 `protobuf:"fixed64,9,opt,name=M20,proto3" json:"M20,omitempty"`
	M21           float64 `protobuf:"fixed64,10,opt,name=M21,proto3" json:"M21,omitempty"`
	M22           float64 `protobuf:"fixed64,11,opt,name=M22,proto3" json:"M22,omitempty"`
	M23           float64 `protobuf:"fixed64,12,opt,name=M23,proto3" json:"M23,omitempty"`
	M30           float64 `protobuf:"fixed64,13,opt,name=M30,proto3" json:"M30,omitempty"`
	M31           float64 `protobuf:"fixed64,14,opt,name=M31,proto3" json:"M31,omitempty"`
	M32           float64 `protobuf:"fixed64,15,opt,name=M32,proto3" json:"M32,omitempty"`
	M33           float64 `protobuf:"fixed64,16,opt,name=M33,proto3" json:"M33,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Matrix4X4) Reset() {
	*x = Matrix4X4{}
	mi := &file_amp_std_amp_std_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Matrix4X4) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Matrix4X4) ProtoMessage() {}

func (x *Matrix4X4) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Matrix4X4.ProtoReflect.Descriptor instead.
func (*Matrix4X4) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{1}
}

func (x *Matrix4X4) GetM00() float64 {
	if x != nil {
		return x.M00
	}
	return 0
}

func (x *Matrix4X4) GetM01() float64 {
	if x != nil {
		return x.M01
	}
	return 0
}

func (x *Matrix4X4) GetM02() float64 {
	if x != nil {
		return x.M02
	}
	return 0
}

func (x *Matrix4X4) GetM03() float64 {
	if x != nil {
		return x.M03
	}
	return 0
}

func (x *Matrix4X4) GetM10() float64 {
	if x != nil {
		return x.M10
	}
	return 0
}

func (x *Matrix4X4) GetM11() float64 {
	if x != nil {
		return x.M11
	}
	return 0
}

func (x *Matrix4X4) GetM12() float64 {
	if x != nil {
		return x.M12
	}
	return 0
}

func (x *Matrix4X4) GetM13() float64 {
	if x != nil {
		return x.M13
	}
	return 0
}

func (x *Matrix4X4) GetM20() float64 {
	if x != nil {
		return x.M20
	}
	return 0
}

func (x *Matrix4X4) GetM21() float64 {
	if x != nil {
		return x.M21
	}
	return 0
}

func (x *Matrix4X4) GetM22() float64 {
	if x != nil {
		return x.M22
	}
	return 0
}

func (x *Matrix4X4) GetM23() float64 {
	if x != nil {
		return x.M23
	}
	return 0
}

func (x *Matrix4X4) GetM30() float64 {
	if x != nil {
		return x.M30
	}
	return 0
}

func (x *Matrix4X4) GetM31() float64 {
	if x != nil {
		return x.M31
	}
	return 0
}

func (x *Matrix4X4) GetM32() float64 {
	if x != nil {
		return x.M32
	}
	return 0
}

func (x *Matrix4X4) GetM33() float64 {
	if x != nil {
		return x.M33
	}
	return 0
}

// General purpose Camera state
type CameraState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Placement     *TRS                   `protobuf:"bytes,1,opt,name=Placement,proto3" json:"Placement,omitempty"`
	Pitch         float32                `protobuf:"fixed32,2,opt,name=Pitch,proto3" json:"Pitch,omitempty"`          // degrees
	Yaw           float32                `protobuf:"fixed32,3,opt,name=Yaw,proto3" json:"Yaw,omitempty"`              // degrees
	Distance      float32                `protobuf:"fixed32,5,opt,name=Distance,proto3" json:"Distance,omitempty"`    // optional distance to anchor
	Altitude      float32                `protobuf:"fixed32,6,opt,name=Altitude,proto3" json:"Altitude,omitempty"`    // optional altitude above the surface
	Mass          float32                `protobuf:"fixed32,9,opt,name=Mass,proto3" json:"Mass,omitempty"`            // optional mass (inertia) of camera body
	NearPlane     float32                `protobuf:"fixed32,10,opt,name=NearPlane,proto3" json:"NearPlane,omitempty"` // optional near plane distance
	FarPlane      float32                `protobuf:"fixed32,11,opt,name=FarPlane,proto3" json:"FarPlane,omitempty"`   // optional far plane distance
	Fov           float32                `protobuf:"fixed32,13,opt,name=Fov,proto3" json:"Fov,omitempty"`             // field of view in degrees; 0 denotes orthographic camera
	PixelsX       int32                  `protobuf:"varint,16,opt,name=PixelsX,proto3" json:"PixelsX,omitempty"`      // viewport width in pixels
	PixelsY       int32                  `protobuf:"varint,17,opt,name=PixelsY,proto3" json:"PixelsY,omitempty"`      // viewport height in pixels
	Mode          string                 `protobuf:"bytes,20,opt,name=Mode,proto3" json:"Mode,omitempty"`             // optional camera mode description
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraState) Reset() {
	*x = CameraState{}
	mi := &file_amp_std_amp_std_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraState) ProtoMessage() {}

func (x *CameraState) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraState.ProtoReflect.Descriptor instead.
func (*CameraState) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{2}
}

func (x *CameraState) GetPlacement() *TRS {
	if x != nil {
		return x.Placement
	}
	return nil
}

func (x *CameraState) GetPitch() float32 {
	if x != nil {
		return x.Pitch
	}
	return 0
}

func (x *CameraState) GetYaw() float32 {
	if x != nil {
		return x.Yaw
	}
	return 0
}

func (x *CameraState) GetDistance() float32 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *CameraState) GetAltitude() float32 {
	if x != nil {
		return x.Altitude
	}
	return 0
}

func (x *CameraState) GetMass() float32 {
	if x != nil {
		return x.Mass
	}
	return 0
}

func (x *CameraState) GetNearPlane() float32 {
	if x != nil {
		return x.NearPlane
	}
	return 0
}

func (x *CameraState) GetFarPlane() float32 {
	if x != nil {
		return x.FarPlane
	}
	return 0
}

func (x *CameraState) GetFov() float32 {
	if x != nil {
		return x.Fov
	}
	return 0
}

func (x *CameraState) GetPixelsX() int32 {
	if x != nil {
		return x.PixelsX
	}
	return 0
}

func (x *CameraState) GetPixelsY() int32 {
	if x != nil {
		return x.PixelsY
	}
	return 0
}

func (x *CameraState) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

type CameraOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MoveSpeed     float32                `protobuf:"fixed32,1,opt,name=MoveSpeed,proto3" json:"MoveSpeed,omitempty"` // movement speed multiplier
	Mode          string                 `protobuf:"bytes,2,opt,name=Mode,proto3" json:"Mode,omitempty"`             // e.g. "orbit", "first-person", "flight", etc.
	ModeTags      string                 `protobuf:"bytes,3,opt,name=ModeTags,proto3" json:"ModeTags,omitempty"`     // e.g. "hide-altitude.present-fullscreen"
	ShowUnits     int32                  `protobuf:"varint,4,opt,name=ShowUnits,proto3" json:"ShowUnits,omitempty"`  // level of detail
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CameraOptions) Reset() {
	*x = CameraOptions{}
	mi := &file_amp_std_amp_std_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CameraOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CameraOptions) ProtoMessage() {}

func (x *CameraOptions) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CameraOptions.ProtoReflect.Descriptor instead.
func (*CameraOptions) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{3}
}

func (x *CameraOptions) GetMoveSpeed() float32 {
	if x != nil {
		return x.MoveSpeed
	}
	return 0
}

func (x *CameraOptions) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *CameraOptions) GetModeTags() string {
	if x != nil {
		return x.ModeTags
	}
	return ""
}

func (x *CameraOptions) GetShowUnits() int32 {
	if x != nil {
		return x.ShowUnits
	}
	return 0
}

// FileInfo a general-purpose file system meta info block.
type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=Mode,proto3" json:"Mode,omitempty"`               // unix file mode label
	IsDir         bool                   `protobuf:"varint,2,opt,name=IsDir,proto3" json:"IsDir,omitempty"`            // true if item is a directory
	DirName       string                 `protobuf:"bytes,4,opt,name=DirName,proto3" json:"DirName,omitempty"`         // prepended to FileName forms full path
	ItemName      string                 `protobuf:"bytes,5,opt,name=ItemName,proto3" json:"ItemName,omitempty"`       // file/dir item name
	ExtLen        int32                  `protobuf:"varint,6,opt,name=ExtLen,proto3" json:"ExtLen,omitempty"`          // length of the file extension (0 if none)
	ContentType   string                 `protobuf:"bytes,8,opt,name=ContentType,proto3" json:"ContentType,omitempty"` // MIME type of the file (e.g. "image/png", "text/html", etc.);
	CreatedAt     int64                  `protobuf:"varint,10,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`   // UTC << 16
	ModifiedAt    int64                  `protobuf:"varint,11,opt,name=ModifiedAt,proto3" json:"ModifiedAt,omitempty"` // UTC << 16
	ByteSize      int64                  `protobuf:"varint,14,opt,name=ByteSize,proto3" json:"ByteSize,omitempty"`     // data fork byte length
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_amp_std_amp_std_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{4}
}

func (x *FileInfo) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FileInfo) GetIsDir() bool {
	if x != nil {
		return x.IsDir
	}
	return false
}

func (x *FileInfo) GetDirName() string {
	if x != nil {
		return x.DirName
	}
	return ""
}

func (x *FileInfo) GetItemName() string {
	if x != nil {
		return x.ItemName
	}
	return ""
}

func (x *FileInfo) GetExtLen() int32 {
	if x != nil {
		return x.ExtLen
	}
	return 0
}

func (x *FileInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *FileInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *FileInfo) GetModifiedAt() int64 {
	if x != nil {
		return x.ModifiedAt
	}
	return 0
}

func (x *FileInfo) GetByteSize() int64 {
	if x != nil {
		return x.ByteSize
	}
	return 0
}

// Multi-purpose, future-proof text element or label.
type TextItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Body          string                 `protobuf:"bytes,2,opt,name=Body,proto3" json:"Body,omitempty"` // atomic plain-text body
	Tags          *amp.Tags              `protobuf:"bytes,4,opt,name=Tags,proto3" json:"Tags,omitempty"` // free use attachments or metadata
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextItem) Reset() {
	*x = TextItem{}
	mi := &file_amp_std_amp_std_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextItem) ProtoMessage() {}

func (x *TextItem) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextItem.ProtoReflect.Descriptor instead.
func (*TextItem) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{5}
}

func (x *TextItem) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *TextItem) GetTags() *amp.Tags {
	if x != nil {
		return x.Tags
	}
	return nil
}

// JsonValue is a general-purpose JSON value container.
// Though multiple fields can be set (e.g. a Number also encoded as a string,
//
//	the Kind field is which field is considered the primary source of truth.
type JsonValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          ValueKind              `protobuf:"varint,1,opt,name=Kind,proto3,enum=std.ValueKind" json:"Kind,omitempty"`
	String_       string                 `protobuf:"bytes,2,opt,name=String,proto3" json:"String,omitempty"`
	Number        float64                `protobuf:"fixed64,3,opt,name=Number,proto3" json:"Number,omitempty"`
	Array         []*JsonValue           `protobuf:"bytes,4,rep,name=Array,proto3" json:"Array,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonValue) Reset() {
	*x = JsonValue{}
	mi := &file_amp_std_amp_std_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonValue) ProtoMessage() {}

func (x *JsonValue) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonValue.ProtoReflect.Descriptor instead.
func (*JsonValue) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{6}
}

func (x *JsonValue) GetKind() ValueKind {
	if x != nil {
		return x.Kind
	}
	return ValueKind_Null
}

func (x *JsonValue) GetString_() string {
	if x != nil {
		return x.String_
	}
	return ""
}

func (x *JsonValue) GetNumber() float64 {
	if x != nil {
		return x.Number
	}
	return 0
}

func (x *JsonValue) GetArray() []*JsonValue {
	if x != nil {
		return x.Array
	}
	return nil
}

// Generic report summary
type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *TextItem              `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Caption       *TextItem              `protobuf:"bytes,2,opt,name=Caption,proto3" json:"Caption,omitempty"`
	Errors        []*TextItem            `protobuf:"bytes,3,rep,name=Errors,proto3" json:"Errors,omitempty"`
	Warnings      []*TextItem            `protobuf:"bytes,4,rep,name=Warnings,proto3" json:"Warnings,omitempty"`
	Messages      []*TextItem            `protobuf:"bytes,5,rep,name=Messages,proto3" json:"Messages,omitempty"`
	Debug         []*TextItem            `protobuf:"bytes,15,rep,name=Debug,proto3" json:"Debug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_amp_std_amp_std_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{7}
}

func (x *Report) GetTitle() *TextItem {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Report) GetCaption() *TextItem {
	if x != nil {
		return x.Caption
	}
	return nil
}

func (x *Report) GetErrors() []*TextItem {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *Report) GetWarnings() []*TextItem {
	if x != nil {
		return x.Warnings
	}
	return nil
}

func (x *Report) GetMessages() []*TextItem {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *Report) GetDebug() []*TextItem {
	if x != nil {
		return x.Debug
	}
	return nil
}

type Labels struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	About         string                 `protobuf:"bytes,4,opt,name=About,proto3" json:"About,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Labels) Reset() {
	*x = Labels{}
	mi := &file_amp_std_amp_std_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Labels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Labels) ProtoMessage() {}

func (x *Labels) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Labels.ProtoReflect.Descriptor instead.
func (*Labels) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{8}
}

func (x *Labels) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Labels) GetAbout() string {
	if x != nil {
		return x.About
	}
	return ""
}

// General purpose lightweight set of geo tiles in the shape of a rectangle - composed rectangle given a center and width/height.
// The units are typically mid H3 resolution with rectangular dimensions in units of font glyph size.
type Rect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Format        PointFormat            `protobuf:"varint,1,opt,name=Format,proto3,enum=std.PointFormat" json:"Format,omitempty"` // specifies the type and format of Coords
	Anchor        uint64                 `protobuf:"fixed64,2,opt,name=Anchor,proto3" json:"Anchor,omitempty"`                     // S2 or H3 tile index; also implies visual
	R             uint64                 `protobuf:"fixed64,3,opt,name=R,proto3" json:"R,omitempty"`                               // mm altitude from globe center or UTC64
	Width         int32                  `protobuf:"varint,8,opt,name=Width,proto3" json:"Width,omitempty"`                        // mm
	Height        int32                  `protobuf:"varint,9,opt,name=Height,proto3" json:"Height,omitempty"`                      // mm
	I             int32                  `protobuf:"varint,10,opt,name=I,proto3" json:"I,omitempty"`                               // center offset
	J             int32                  `protobuf:"varint,11,opt,name=J,proto3" json:"J,omitempty"`                               // center offset
	K             int32                  `protobuf:"varint,12,opt,name=K,proto3" json:"K,omitempty"`                               // center offset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Rect) Reset() {
	*x = Rect{}
	mi := &file_amp_std_amp_std_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Rect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rect) ProtoMessage() {}

func (x *Rect) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rect.ProtoReflect.Descriptor instead.
func (*Rect) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{9}
}

func (x *Rect) GetFormat() PointFormat {
	if x != nil {
		return x.Format
	}
	return PointFormat_S2
}

func (x *Rect) GetAnchor() uint64 {
	if x != nil {
		return x.Anchor
	}
	return 0
}

func (x *Rect) GetR() uint64 {
	if x != nil {
		return x.R
	}
	return 0
}

func (x *Rect) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Rect) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *Rect) GetI() int32 {
	if x != nil {
		return x.I
	}
	return 0
}

func (x *Rect) GetJ() int32 {
	if x != nil {
		return x.J
	}
	return 0
}

func (x *Rect) GetK() int32 {
	if x != nil {
		return x.K
	}
	return 0
}

// General purpose polygonal path of geo tiles.
type GeoPath struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          GeoPath_RenderType     `protobuf:"varint,1,opt,name=Type,proto3,enum=std.GeoPath_RenderType" json:"Type,omitempty"`
	ExtrudeLo     float32                `protobuf:"fixed32,4,opt,name=ExtrudeLo,proto3" json:"ExtrudeLo,omitempty"`                // If non-zero, extrude the path to this height
	ExtrudeHi     float32                `protobuf:"fixed32,5,opt,name=ExtrudeHi,proto3" json:"ExtrudeHi,omitempty"`                // If non-zero, extrude the path to this height
	Format        PointFormat            `protobuf:"varint,14,opt,name=Format,proto3,enum=std.PointFormat" json:"Format,omitempty"` // specifies the type and format of Coords
	Points        []uint64               `protobuf:"fixed64,15,rep,packed,name=Points,proto3" json:"Points,omitempty"`              // tile indices interleaved with associated UTC64 or Rmm based on Format.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeoPath) Reset() {
	*x = GeoPath{}
	mi := &file_amp_std_amp_std_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeoPath) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeoPath) ProtoMessage() {}

func (x *GeoPath) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeoPath.ProtoReflect.Descriptor instead.
func (*GeoPath) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{10}
}

func (x *GeoPath) GetType() GeoPath_RenderType {
	if x != nil {
		return x.Type
	}
	return GeoPath_Point
}

func (x *GeoPath) GetExtrudeLo() float32 {
	if x != nil {
		return x.ExtrudeLo
	}
	return 0
}

func (x *GeoPath) GetExtrudeHi() float32 {
	if x != nil {
		return x.ExtrudeHi
	}
	return 0
}

func (x *GeoPath) GetFormat() PointFormat {
	if x != nil {
		return x.Format
	}
	return PointFormat_S2
}

func (x *GeoPath) GetPoints() []uint64 {
	if x != nil {
		return x.Points
	}
	return nil
}

// MediaItem wraps a media track, feature, featurette, collection, album, or playlist.
type MediaItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Flags         MediaFlags             `protobuf:"varint,1,opt,name=Flags,proto3,enum=std.MediaFlags" json:"Flags,omitempty"` // describes this item
	Tag           *amp.Tag               `protobuf:"bytes,3,opt,name=Tag,proto3" json:"Tag,omitempty"`                          // free use
	StartAt       float64                `protobuf:"fixed64,5,opt,name=StartAt,proto3" json:"StartAt,omitempty"`                // starts playback at the given seconds offset
	Seconds       float64                `protobuf:"fixed64,6,opt,name=Seconds,proto3" json:"Seconds,omitempty"`                // playback duration in seconds
	Popularity    float32                `protobuf:"fixed32,16,opt,name=Popularity,proto3" json:"Popularity,omitempty"`         // 0.0 to 1.0
	Ordering      float32                `protobuf:"fixed32,17,opt,name=Ordering,proto3" json:"Ordering,omitempty"`             // items are sorted by this value
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaItem) Reset() {
	*x = MediaItem{}
	mi := &file_amp_std_amp_std_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaItem) ProtoMessage() {}

func (x *MediaItem) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaItem.ProtoReflect.Descriptor instead.
func (*MediaItem) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{11}
}

func (x *MediaItem) GetFlags() MediaFlags {
	if x != nil {
		return x.Flags
	}
	return MediaFlags_NoMedia
}

func (x *MediaItem) GetTag() *amp.Tag {
	if x != nil {
		return x.Tag
	}
	return nil
}

func (x *MediaItem) GetStartAt() float64 {
	if x != nil {
		return x.StartAt
	}
	return 0
}

func (x *MediaItem) GetSeconds() float64 {
	if x != nil {
		return x.Seconds
	}
	return 0
}

func (x *MediaItem) GetPopularity() float32 {
	if x != nil {
		return x.Popularity
	}
	return 0
}

func (x *MediaItem) GetOrdering() float32 {
	if x != nil {
		return x.Ordering
	}
	return 0
}

// Arg is a any-purpose key/value pair
type Arg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Arg) Reset() {
	*x = Arg{}
	mi := &file_amp_std_amp_std_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Arg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Arg) ProtoMessage() {}

func (x *Arg) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Arg.ProtoReflect.Descriptor instead.
func (*Arg) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{12}
}

func (x *Arg) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Arg) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type VisPreset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         *TextItem              `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Collection    *TextItem              `protobuf:"bytes,2,opt,name=Collection,proto3" json:"Collection,omitempty"`
	Credits       *TextItem              `protobuf:"bytes,3,opt,name=Credits,proto3" json:"Credits,omitempty"`
	ColormapFlags ColormapFlags          `protobuf:"varint,6,opt,name=ColormapFlags,proto3,enum=std.ColormapFlags" json:"ColormapFlags,omitempty"`
	SensorFlags   SensorFlags            `protobuf:"varint,7,opt,name=SensorFlags,proto3,enum=std.SensorFlags" json:"SensorFlags,omitempty"`
	AudioFlags    AudioFlags             `protobuf:"varint,8,opt,name=AudioFlags,proto3,enum=std.AudioFlags" json:"AudioFlags,omitempty"`
	AspectMin     float32                `protobuf:"fixed32,10,opt,name=AspectMin,proto3" json:"AspectMin,omitempty"` // y/x lower peg; 0 denotes no min
	AspectMax     float32                `protobuf:"fixed32,11,opt,name=AspectMax,proto3" json:"AspectMax,omitempty"` // y/x upper peg; 0 denotes no max
	AssetURI      string                 `protobuf:"bytes,20,opt,name=AssetURI,proto3" json:"AssetURI,omitempty"`     // VisShader asset URI
	Args          []*Arg                 `protobuf:"bytes,21,rep,name=Args,proto3" json:"Args,omitempty"`             // free use arguments passed to the asset
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VisPreset) Reset() {
	*x = VisPreset{}
	mi := &file_amp_std_amp_std_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VisPreset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VisPreset) ProtoMessage() {}

func (x *VisPreset) ProtoReflect() protoreflect.Message {
	mi := &file_amp_std_amp_std_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VisPreset.ProtoReflect.Descriptor instead.
func (*VisPreset) Descriptor() ([]byte, []int) {
	return file_amp_std_amp_std_proto_rawDescGZIP(), []int{13}
}

func (x *VisPreset) GetTitle() *TextItem {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *VisPreset) GetCollection() *TextItem {
	if x != nil {
		return x.Collection
	}
	return nil
}

func (x *VisPreset) GetCredits() *TextItem {
	if x != nil {
		return x.Credits
	}
	return nil
}

func (x *VisPreset) GetColormapFlags() ColormapFlags {
	if x != nil {
		return x.ColormapFlags
	}
	return ColormapFlags_ColormapFlags_None
}

func (x *VisPreset) GetSensorFlags() SensorFlags {
	if x != nil {
		return x.SensorFlags
	}
	return SensorFlags_SensorFlags_None
}

func (x *VisPreset) GetAudioFlags() AudioFlags {
	if x != nil {
		return x.AudioFlags
	}
	return AudioFlags_AudioFlags_None
}

func (x *VisPreset) GetAspectMin() float32 {
	if x != nil {
		return x.AspectMin
	}
	return 0
}

func (x *VisPreset) GetAspectMax() float32 {
	if x != nil {
		return x.AspectMax
	}
	return 0
}

func (x *VisPreset) GetAssetURI() string {
	if x != nil {
		return x.AssetURI
	}
	return ""
}

func (x *VisPreset) GetArgs() []*Arg {
	if x != nil {
		return x.Args
	}
	return nil
}

var File_amp_std_amp_std_proto protoreflect.FileDescriptor

const file_amp_std_amp_std_proto_rawDesc = "" +
	"\n" +
	"\x15amp/std/amp.std.proto\x12\x03std\x1a\x12amp/amp.core.proto\"\xc3\x01\n" +
	"\x03TRS\x12\x0e\n" +
	"\x02Sx\x18\x01 \x01(\x01R\x02Sx\x12$\n" +
	"\x05Flags\x18\x02 \x01(\x0e2\x0e.std.TRS_FlagsR\x05Flags\x12\x0e\n" +
	"\x02Px\x18\x03 \x01(\x01R\x02Px\x12\x0e\n" +
	"\x02Py\x18\x04 \x01(\x01R\x02Py\x12\x0e\n" +
	"\x02Pz\x18\x05 \x01(\x01R\x02Pz\x12\x0e\n" +
	"\x02Qx\x18\n" +
	" \x01(\x01R\x02Qx\x12\x0e\n" +
	"\x02Qy\x18\v \x01(\x01R\x02Qy\x12\x0e\n" +
	"\x02Qz\x18\f \x01(\x01R\x02Qz\x12\x0e\n" +
	"\x02Qw\x18\r \x01(\x01R\x02Qw\x12\x16\n" +
	"\x06TileS2\x18\x10 \x01(\x06R\x06TileS2\"\xab\x02\n" +
	"\tMatrix4x4\x12\x10\n" +
	"\x03M00\x18\x01 \x01(\x01R\x03M00\x12\x10\n" +
	"\x03M01\x18\x02 \x01(\x01R\x03M01\x12\x10\n" +
	"\x03M02\x18\x03 \x01(\x01R\x03M02\x12\x10\n" +
	"\x03M03\x18\x04 \x01(\x01R\x03M03\x12\x10\n" +
	"\x03M10\x18\x05 \x01(\x01R\x03M10\x12\x10\n" +
	"\x03M11\x18\x06 \x01(\x01R\x03M11\x12\x10\n" +
	"\x03M12\x18\a \x01(\x01R\x03M12\x12\x10\n" +
	"\x03M13\x18\b \x01(\x01R\x03M13\x12\x10\n" +
	"\x03M20\x18\t \x01(\x01R\x03M20\x12\x10\n" +
	"\x03M21\x18\n" +
	" \x01(\x01R\x03M21\x12\x10\n" +
	"\x03M22\x18\v \x01(\x01R\x03M22\x12\x10\n" +
	"\x03M23\x18\f \x01(\x01R\x03M23\x12\x10\n" +
	"\x03M30\x18\r \x01(\x01R\x03M30\x12\x10\n" +
	"\x03M31\x18\x0e \x01(\x01R\x03M31\x12\x10\n" +
	"\x03M32\x18\x0f \x01(\x01R\x03M32\x12\x10\n" +
	"\x03M33\x18\x10 \x01(\x01R\x03M33\"\xbd\x02\n" +
	"\vCameraState\x12&\n" +
	"\tPlacement\x18\x01 \x01(\v2\b.std.TRSR\tPlacement\x12\x14\n" +
	"\x05Pitch\x18\x02 \x01(\x02R\x05Pitch\x12\x10\n" +
	"\x03Yaw\x18\x03 \x01(\x02R\x03Yaw\x12\x1a\n" +
	"\bDistance\x18\x05 \x01(\x02R\bDistance\x12\x1a\n" +
	"\bAltitude\x18\x06 \x01(\x02R\bAltitude\x12\x12\n" +
	"\x04Mass\x18\t \x01(\x02R\x04Mass\x12\x1c\n" +
	"\tNearPlane\x18\n" +
	" \x01(\x02R\tNearPlane\x12\x1a\n" +
	"\bFarPlane\x18\v \x01(\x02R\bFarPlane\x12\x10\n" +
	"\x03Fov\x18\r \x01(\x02R\x03Fov\x12\x18\n" +
	"\aPixelsX\x18\x10 \x01(\x05R\aPixelsX\x12\x18\n" +
	"\aPixelsY\x18\x11 \x01(\x05R\aPixelsY\x12\x12\n" +
	"\x04Mode\x18\x14 \x01(\tR\x04Mode\"{\n" +
	"\rCameraOptions\x12\x1c\n" +
	"\tMoveSpeed\x18\x01 \x01(\x02R\tMoveSpeed\x12\x12\n" +
	"\x04Mode\x18\x02 \x01(\tR\x04Mode\x12\x1a\n" +
	"\bModeTags\x18\x03 \x01(\tR\bModeTags\x12\x1c\n" +
	"\tShowUnits\x18\x04 \x01(\x05R\tShowUnits\"\xfe\x01\n" +
	"\bFileInfo\x12\x12\n" +
	"\x04Mode\x18\x01 \x01(\tR\x04Mode\x12\x14\n" +
	"\x05IsDir\x18\x02 \x01(\bR\x05IsDir\x12\x18\n" +
	"\aDirName\x18\x04 \x01(\tR\aDirName\x12\x1a\n" +
	"\bItemName\x18\x05 \x01(\tR\bItemName\x12\x16\n" +
	"\x06ExtLen\x18\x06 \x01(\x05R\x06ExtLen\x12 \n" +
	"\vContentType\x18\b \x01(\tR\vContentType\x12\x1c\n" +
	"\tCreatedAt\x18\n" +
	" \x01(\x03R\tCreatedAt\x12\x1e\n" +
	"\n" +
	"ModifiedAt\x18\v \x01(\x03R\n" +
	"ModifiedAt\x12\x1a\n" +
	"\bByteSize\x18\x0e \x01(\x03R\bByteSize\"=\n" +
	"\bTextItem\x12\x12\n" +
	"\x04Body\x18\x02 \x01(\tR\x04Body\x12\x1d\n" +
	"\x04Tags\x18\x04 \x01(\v2\t.amp.TagsR\x04Tags\"\x85\x01\n" +
	"\tJsonValue\x12\"\n" +
	"\x04Kind\x18\x01 \x01(\x0e2\x0e.std.ValueKindR\x04Kind\x12\x16\n" +
	"\x06String\x18\x02 \x01(\tR\x06String\x12\x16\n" +
	"\x06Number\x18\x03 \x01(\x01R\x06Number\x12$\n" +
	"\x05Array\x18\x04 \x03(\v2\x0e.std.JsonValueR\x05Array\"\xf8\x01\n" +
	"\x06Report\x12#\n" +
	"\x05Title\x18\x01 \x01(\v2\r.std.TextItemR\x05Title\x12'\n" +
	"\aCaption\x18\x02 \x01(\v2\r.std.TextItemR\aCaption\x12%\n" +
	"\x06Errors\x18\x03 \x03(\v2\r.std.TextItemR\x06Errors\x12)\n" +
	"\bWarnings\x18\x04 \x03(\v2\r.std.TextItemR\bWarnings\x12)\n" +
	"\bMessages\x18\x05 \x03(\v2\r.std.TextItemR\bMessages\x12#\n" +
	"\x05Debug\x18\x0f \x03(\v2\r.std.TextItemR\x05Debug\"4\n" +
	"\x06Labels\x12\x14\n" +
	"\x05Title\x18\x01 \x01(\tR\x05Title\x12\x14\n" +
	"\x05About\x18\x04 \x01(\tR\x05About\"\xae\x01\n" +
	"\x04Rect\x12(\n" +
	"\x06Format\x18\x01 \x01(\x0e2\x10.std.PointFormatR\x06Format\x12\x16\n" +
	"\x06Anchor\x18\x02 \x01(\x06R\x06Anchor\x12\f\n" +
	"\x01R\x18\x03 \x01(\x06R\x01R\x12\x14\n" +
	"\x05Width\x18\b \x01(\x05R\x05Width\x12\x16\n" +
	"\x06Height\x18\t \x01(\x05R\x06Height\x12\f\n" +
	"\x01I\x18\n" +
	" \x01(\x05R\x01I\x12\f\n" +
	"\x01J\x18\v \x01(\x05R\x01J\x12\f\n" +
	"\x01K\x18\f \x01(\x05R\x01K\"\xe1\x01\n" +
	"\aGeoPath\x12+\n" +
	"\x04Type\x18\x01 \x01(\x0e2\x17.std.GeoPath.RenderTypeR\x04Type\x12\x1c\n" +
	"\tExtrudeLo\x18\x04 \x01(\x02R\tExtrudeLo\x12\x1c\n" +
	"\tExtrudeHi\x18\x05 \x01(\x02R\tExtrudeHi\x12(\n" +
	"\x06Format\x18\x0e \x01(\x0e2\x10.std.PointFormatR\x06Format\x12\x16\n" +
	"\x06Points\x18\x0f \x03(\x06R\x06Points\"+\n" +
	"\n" +
	"RenderType\x12\t\n" +
	"\x05Point\x10\x00\x12\b\n" +
	"\x04Path\x10\x01\x12\b\n" +
	"\x04Ring\x10\x02\"\xbe\x01\n" +
	"\tMediaItem\x12%\n" +
	"\x05Flags\x18\x01 \x01(\x0e2\x0f.std.MediaFlagsR\x05Flags\x12\x1a\n" +
	"\x03Tag\x18\x03 \x01(\v2\b.amp.TagR\x03Tag\x12\x18\n" +
	"\aStartAt\x18\x05 \x01(\x01R\aStartAt\x12\x18\n" +
	"\aSeconds\x18\x06 \x01(\x01R\aSeconds\x12\x1e\n" +
	"\n" +
	"Popularity\x18\x10 \x01(\x02R\n" +
	"Popularity\x12\x1a\n" +
	"\bOrdering\x18\x11 \x01(\x02R\bOrdering\"-\n" +
	"\x03Arg\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value\"\x9d\x03\n" +
	"\tVisPreset\x12#\n" +
	"\x05Title\x18\x01 \x01(\v2\r.std.TextItemR\x05Title\x12-\n" +
	"\n" +
	"Collection\x18\x02 \x01(\v2\r.std.TextItemR\n" +
	"Collection\x12'\n" +
	"\aCredits\x18\x03 \x01(\v2\r.std.TextItemR\aCredits\x128\n" +
	"\rColormapFlags\x18\x06 \x01(\x0e2\x12.std.ColormapFlagsR\rColormapFlags\x122\n" +
	"\vSensorFlags\x18\a \x01(\x0e2\x10.std.SensorFlagsR\vSensorFlags\x12/\n" +
	"\n" +
	"AudioFlags\x18\b \x01(\x0e2\x0f.std.AudioFlagsR\n" +
	"AudioFlags\x12\x1c\n" +
	"\tAspectMin\x18\n" +
	" \x01(\x02R\tAspectMin\x12\x1c\n" +
	"\tAspectMax\x18\v \x01(\x02R\tAspectMax\x12\x1a\n" +
	"\bAssetURI\x18\x14 \x01(\tR\bAssetURI\x12\x1c\n" +
	"\x04Args\x18\x15 \x03(\v2\b.std.ArgR\x04Args**\n" +
	"\tTRS_Flags\x12\x0e\n" +
	"\n" +
	"FixedScale\x10\x00\x12\r\n" +
	"\tAutoScale\x10\x01*B\n" +
	"\tValueKind\x12\b\n" +
	"\x04Null\x10\x00\x12\t\n" +
	"\x05False\x10\x01\x12\b\n" +
	"\x04True\x10\x02\x12\n" +
	"\n" +
	"\x06Number\x10\x03\x12\n" +
	"\n" +
	"\x06String\x10\x04*/\n" +
	"\vPointFormat\x12\x06\n" +
	"\x02S2\x10\x00\x12\x06\n" +
	"\x02H3\x10\x01\x12\a\n" +
	"\x03S2T\x10\x02\x12\a\n" +
	"\x03H3T\x10\x03*\xb9\x01\n" +
	"\n" +
	"MediaFlags\x12\v\n" +
	"\aNoMedia\x10\x00\x12\n" +
	"\n" +
	"\x06IsLive\x10\x01\x12\x0e\n" +
	"\n" +
	"IsSeekable\x10\x02\x12\x0e\n" +
	"\n" +
	"IsUnending\x10\x04\x12\x0e\n" +
	"\n" +
	"NewChapter\x10\b\x12\f\n" +
	"\bNewTrack\x10\x10\x12\r\n" +
	"\bHasAudio\x10\x80\x02\x12\r\n" +
	"\bHasVideo\x10\x80\x04\x12\x0e\n" +
	"\tHasSpeech\x10\x80\b\x12\x11\n" +
	"\fNeedsNetwork\x10\x80\x10\x12\x13\n" +
	"\fSkipIsLikely\x10\x80\x80\x80\b*o\n" +
	"\rColormapFlags\x12\x16\n" +
	"\x12ColormapFlags_None\x10\x00\x12\x16\n" +
	"\x12ColormapFlags_Full\x10\x01\x12\x16\n" +
	"\x12ColormapFlags_Back\x10\x02\x12\x16\n" +
	"\x12ColormapFlags_Fore\x10\x04*;\n" +
	"\vSensorFlags\x12\x14\n" +
	"\x10SensorFlags_None\x10\x00\x12\x16\n" +
	"\x12SensorFlags_GyroUp\x10\x01*5\n" +
	"\n" +
	"AudioFlags\x12\x13\n" +
	"\x0fAudioFlags_None\x10\x00\x12\x12\n" +
	"\x0eAudioFlags_FFT\x10\x01BHZ-github.com/art-media-platform/amp.SDK/amp/std\xaa\x02\x16art.media.platform.stdb\x06proto3"

var (
	file_amp_std_amp_std_proto_rawDescOnce sync.Once
	file_amp_std_amp_std_proto_rawDescData []byte
)

func file_amp_std_amp_std_proto_rawDescGZIP() []byte {
	file_amp_std_amp_std_proto_rawDescOnce.Do(func() {
		file_amp_std_amp_std_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amp_std_amp_std_proto_rawDesc), len(file_amp_std_amp_std_proto_rawDesc)))
	})
	return file_amp_std_amp_std_proto_rawDescData
}

var file_amp_std_amp_std_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_amp_std_amp_std_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_amp_std_amp_std_proto_goTypes = []any{
	(TRS_Flags)(0),          // 0: std.TRS_Flags
	(ValueKind)(0),          // 1: std.ValueKind
	(PointFormat)(0),        // 2: std.PointFormat
	(MediaFlags)(0),         // 3: std.MediaFlags
	(ColormapFlags)(0),      // 4: std.ColormapFlags
	(SensorFlags)(0),        // 5: std.SensorFlags
	(AudioFlags)(0),         // 6: std.AudioFlags
	(GeoPath_RenderType)(0), // 7: std.GeoPath.RenderType
	(*TRS)(nil),             // 8: std.TRS
	(*Matrix4X4)(nil),       // 9: std.Matrix4x4
	(*CameraState)(nil),     // 10: std.CameraState
	(*CameraOptions)(nil),   // 11: std.CameraOptions
	(*FileInfo)(nil),        // 12: std.FileInfo
	(*TextItem)(nil),        // 13: std.TextItem
	(*JsonValue)(nil),       // 14: std.JsonValue
	(*Report)(nil),          // 15: std.Report
	(*Labels)(nil),          // 16: std.Labels
	(*Rect)(nil),            // 17: std.Rect
	(*GeoPath)(nil),         // 18: std.GeoPath
	(*MediaItem)(nil),       // 19: std.MediaItem
	(*Arg)(nil),             // 20: std.Arg
	(*VisPreset)(nil),       // 21: std.VisPreset
	(*amp.Tags)(nil),        // 22: amp.Tags
	(*amp.Tag)(nil),         // 23: amp.Tag
}
var file_amp_std_amp_std_proto_depIdxs = []int32{
	0,  // 0: std.TRS.Flags:type_name -> std.TRS_Flags
	8,  // 1: std.CameraState.Placement:type_name -> std.TRS
	22, // 2: std.TextItem.Tags:type_name -> amp.Tags
	1,  // 3: std.JsonValue.Kind:type_name -> std.ValueKind
	14, // 4: std.JsonValue.Array:type_name -> std.JsonValue
	13, // 5: std.Report.Title:type_name -> std.TextItem
	13, // 6: std.Report.Caption:type_name -> std.TextItem
	13, // 7: std.Report.Errors:type_name -> std.TextItem
	13, // 8: std.Report.Warnings:type_name -> std.TextItem
	13, // 9: std.Report.Messages:type_name -> std.TextItem
	13, // 10: std.Report.Debug:type_name -> std.TextItem
	2,  // 11: std.Rect.Format:type_name -> std.PointFormat
	7,  // 12: std.GeoPath.Type:type_name -> std.GeoPath.RenderType
	2,  // 13: std.GeoPath.Format:type_name -> std.PointFormat
	3,  // 14: std.MediaItem.Flags:type_name -> std.MediaFlags
	23, // 15: std.MediaItem.Tag:type_name -> amp.Tag
	13, // 16: std.VisPreset.Title:type_name -> std.TextItem
	13, // 17: std.VisPreset.Collection:type_name -> std.TextItem
	13, // 18: std.VisPreset.Credits:type_name -> std.TextItem
	4,  // 19: std.VisPreset.ColormapFlags:type_name -> std.ColormapFlags
	5,  // 20: std.VisPreset.SensorFlags:type_name -> std.SensorFlags
	6,  // 21: std.VisPreset.AudioFlags:type_name -> std.AudioFlags
	20, // 22: std.VisPreset.Args:type_name -> std.Arg
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_amp_std_amp_std_proto_init() }
func file_amp_std_amp_std_proto_init() {
	if File_amp_std_amp_std_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amp_std_amp_std_proto_rawDesc), len(file_amp_std_amp_std_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amp_std_amp_std_proto_goTypes,
		DependencyIndexes: file_amp_std_amp_std_proto_depIdxs,
		EnumInfos:         file_amp_std_amp_std_proto_enumTypes,
		MessageInfos:      file_amp_std_amp_std_proto_msgTypes,
	}.Build()
	File_amp_std_amp_std_proto = out.File
	file_amp_std_amp_std_proto_goTypes = nil
	file_amp_std_amp_std_proto_depIdxs = nil
}
