// Code generated by forge const -- DO NOT EDIT.
//
//   source: amp.std.consts.sdl

package std

import "github.com/art-media-platform/amp.SDK/stdlib/tag"

var Attr = struct {
	App                                tag.Name
	AppState                           tag.Name
	SessionAttr                        tag.Name
	Login                              tag.Name
	LoginChallenge                     tag.Name
	LoginResponse                      tag.Name
	LoginCheckpoint                    tag.Name
	SessionStatus                      tag.Name
	SessionTag                         tag.Name
	LaunchWeb                          tag.Name
	LaunchOAuth                        tag.Name
	ItemAttr                           tag.Name
	ChildLink                          tag.Name
	ItemLabels                         tag.Name
	ItemTextTag                        tag.Name
	ItemLabel                          tag.Name
	ItemCaption                        tag.Name
	ItemCollection                     tag.Name
	ItemSynopsis                       tag.Name
	ItemFileInfo                       tag.Name
	MainLink                           tag.Name
	ItemVis                            tag.Name
	ItemBehaviors                      tag.Name
	ItemGlyphs                         tag.Name
	ItemLinks                          tag.Name
	ItemCameraState                    tag.Name
	ItemCameraOptions                  tag.Name
	ItemAtmosphere                     tag.Name
	ItemFSInfo                         tag.Name
	GlyphTag                           tag.Name
	TileAttr                           tag.Name
	TileLayout                         tag.Name
	ItemSeries                         tag.Name
	SeriesTRS                          tag.Name
	SeriesLabels                       tag.Name
	SeriesAssetTag                     tag.Name
	SeriesHeadLink                     tag.Name
	SeriesLinkTree                     tag.Name
	SeriesS2R                          tag.Name
	SeriesS2T                          tag.Name
	MediaLink                          tag.Name
	MediaRelease                       tag.Name
	MediaItem                          tag.Name
	MediaPlaylist                      tag.Name
	ChannelAttr                        tag.Name
	ChannelCatalog                     tag.Name
	ChannelEpochs                      tag.Name
	ChannelPropertySeries              tag.Name
	ChannelPropertyLabel               tag.Name
	ChannelPropertyDescription         tag.Name
	ChannelPropertyGlyph               tag.Name
	ChannelPropertySkybox              tag.Name
	ChannelPropertyGrid                tag.Name
	ChannelType                        tag.Name
	ChannelTypeSpreadsheet             tag.Name
	ChannelTypeMessages                tag.Name
	ChannelTypeTimeline                tag.Name
	ChannelTypeNotes                   tag.Name
	ChannelTypeMap                     tag.Name
	ChannelTypeGlobe                   tag.Name
	ChannelTypeManifold                tag.Name
	ChannelTypeSpace                   tag.Name
	ChannelTypeLinks                   tag.Name
	ChannelTypeRegistry                tag.Name
	ChannelTypeSystem                  tag.Name
	ChannelTypeWeb                     tag.Name
	ChannelTypeCrateManager            tag.Name
	ChannelTypePlaylist                tag.Name
	ChannelTypePicker                  tag.Name
	ChannelTypePlanetPicker            tag.Name
	ChannelTypeBrand                   tag.Name
	ChannelTypeNameService             tag.Name
	Brand                              tag.Name
	NameService                        tag.Name
	NameServiceRecord                  tag.Name
	FederationDirectory                tag.Name
	LawAttr                            tag.Name
	LawPlanetEpoch                     tag.Name
	LawMemberEpoch                     tag.Name
	LawChannelEpoch                    tag.Name
	LawPlanetOrigin                    tag.Name
	LawEquivalence                     tag.Name
	LawWithdraw                        tag.Name
	LawMemberKind                      tag.Name
	LawMemberKind_Person               tag.Name
	LawMemberKind_Group                tag.Name
	LawMemberKind_Agent                tag.Name
	LawMemberKind_Instance             tag.Name
	LawMemberKind_Successor            tag.Name
	LawMemberKind_Memorial             tag.Name
	LawMemberKind_Process              tag.Name
	LawAttestationModality             tag.Name
	LawAttestationModality_Asserted    tag.Name
	LawAttestationModality_Witnessed   tag.Name
	LawAttestationModality_Reported    tag.Name
	LawAttestationModality_Inferred    tag.Name
	LawAttestationModality_Speculated  tag.Name
	LawAttestationModality_Dreamed     tag.Name
	LawAttestationModality_Liturgical  tag.Name
	LawAttestationModality_Conditional tag.Name
	LawAttestationModality_Contested   tag.Name
	LawAttestationModality_Retracted   tag.Name
	LawEquivalenceStrength             tag.Name
	LawEquivalenceStrength_Identity    tag.Name
	LawEquivalenceStrength_Translation tag.Name
	LawEquivalenceStrength_Approximate tag.Name
	LawEquivalenceStrength_Analogous   tag.Name
	LawWithdrawReason                  tag.Name
	LawWithdrawReason_Consent          tag.Name
	LawWithdrawReason_Inaccuracy       tag.Name
	LawWithdrawReason_Outdated         tag.Name
	LawWithdrawReason_Coerced          tag.Name
	LawWithdrawReason_Forgotten        tag.Name
	LawWithdrawReason_Departed         tag.Name
	LawWithdrawReason_InviteRecall     tag.Name
	LawWithdrawReason_Retracted        tag.Name
	LedgerAttr                         tag.Name
	LedgerAttestation                  tag.Name
	MemberAttr                         tag.Name
	PlanetInvite                       tag.Name
	PlanetInviteOp                     tag.Name
	HomeAttr                           tag.Name
	PlanetBinding                      tag.Name
	PlanetStorageOpts                  tag.Name
	SystemPropertyAttr                 tag.Name
	SpaceReticleStyle                  tag.Name
	SpaceReticleOverlay                tag.Name
	SpaceSkybox                        tag.Name
	BlobAttr                           tag.Name
	BlobRef                            tag.Name
	NodeBlobs                          tag.Name
	TileServerAttr                     tag.Name
	TileServer                         tag.Name
}{
	// ─── App-centric tags ───────────────────────────────────────────
	App: tag.Name{ID: tag.UID{0x9FC2012FD63F847A, 0x51AA55A31D90CD25}, Canonic: "app"}, // 4ZS80KZPJZHJX53BKPNDFT1M95

	AppState: tag.Name{ID: tag.UID{0xFAA5BBA978628672, 0x22BC2C65BFDD460C}, Canonic: "app.state"}, // 7UNQXUKY32HTT25G1DDQZXUJHD

	// ─── Session management ─────────────────────────────────────────
	SessionAttr: tag.Name{ID: tag.UID{0x5948CA6969CBDF2F, 0x01C92A44FA60AB24}, Canonic: "session"}, // 2T9356KUFCVWRH3K9B8MX61BT4

	Login:           tag.Name{ID: tag.UID{0x761CD041F19A871E, 0x588D714F3B7C0369}, Canonic: "session.login"},           // 3Q3M843WDUHWG5J3CJ9WXRS0V9
	LoginChallenge:  tag.Name{ID: tag.UID{0x4CDE92F1C346D9A6, 0x3DBC5E21F58B7690}, Canonic: "session.loginchallenge"},  // 2DVU9G3HU6V6M3VG2Y47USQXNH
	LoginResponse:   tag.Name{ID: tag.UID{0xD5D931DCBF32B11B, 0x845B0B9940F8F258}, Canonic: "session.loginresponse"},   // 6PV4SXTGTKQ4ES8QSCM50GJWKS
	LoginCheckpoint: tag.Name{ID: tag.UID{0xD1FD78AD2D86A001, 0x89D5922FF13EB7CE}, Canonic: "session.logincheckpoint"}, // 6JZPWBUCD6N00SMPDK5ZSMXEYF
	SessionStatus:   tag.Name{ID: tag.UID{0x7FB381BC8DB19B28, 0xE3EC642BF561552B}, Canonic: "session.status"},          // 3ZQF0VT3EJMDNF7V345GUQ2P9C
	SessionTag:      tag.Name{ID: tag.UID{0xCCE00314A1263502, 0x7A38CD68C10DC759}, Canonic: "session.tag"},             // 6DW01J98966N17NF6EE30HVJUT

	LaunchWeb:   tag.Name{ID: tag.UID{0x7900A4A514A3C61B, 0x69753310BD7BA8BB}, Canonic: "session.tag.www"},   // 3T02KBB553SSEQKX9M22YRRB5V
	LaunchOAuth: tag.Name{ID: tag.UID{0x230B9C43F0F6149B, 0xF1FD67764E068928}, Canonic: "session.tag.oauth"}, // 131FF47W7Q2KEZ3ZC7FT70E298

	// ─── Item attributes ────────────────────────────────────────────
	ItemAttr: tag.Name{ID: tag.UID{0xE8D8BECA5B3BBEB3, 0x1308458DB27C3504}, Canonic: "item"}, // 78V2ZDNQTVRUTJ6225JQT7SE84

	ChildLink:   tag.Name{ID: tag.UID{0x95D3A6EF1C535313, 0x7D09B00E54481F34}, Canonic: "item.child.link.ID"}, // 4PUFMFY72MBD9RU2EH1TB4H7TN
	ItemLabels:  tag.Name{ID: tag.UID{0x89DC7C30D083C0B7, 0xCCB62B4FAAB34B4D}, Canonic: "item.labels"},        // 49VJY31N43S2VWTEJC9YPC6KUE
	ItemTextTag: tag.Name{ID: tag.UID{0xF2CECA12B7434121, 0x9CB04C216D399967}, Canonic: "item.text.tag"},      // 7KTV515EU384HTTD2D45QMM6C7

	ItemLabel:         tag.Name{ID: tag.UID{0x75508F13447213B1, 0x8AA3D9367709DC8D}, Canonic: "item.text.tag.label"},      // 3PB27J6J3K2FSSP8YT6TVHMR4E
	ItemCaption:       tag.Name{ID: tag.UID{0x3B12033B6C89B7E1, 0x60495EEB57BA257B}, Canonic: "item.text.tag.caption"},    // 1V281MQV49QZHQ0KBYXECVN9CV
	ItemCollection:    tag.Name{ID: tag.UID{0xC2D5B84FCDB6AC3C, 0x2A31CC7CB71E75FB}, Canonic: "item.text.tag.collection"}, // 62UQW4ZMEQPHY2NDFDGKVJWXGV
	ItemSynopsis:      tag.Name{ID: tag.UID{0xEA2B06C4B8C0A28E, 0xD3824B8511203663}, Canonic: "item.text.tag.synopsis"},   // 7B5D3D9F60NB7E70KCHN8K0EM3
	ItemFileInfo:      tag.Name{ID: tag.UID{0x37F1C92B7B61AFDE, 0x319025BC546E254F}, Canonic: "item.fileinfo"},            // 1RY74KQYV1PZG33415RJB6W9BG
	MainLink:          tag.Name{ID: tag.UID{0x37B0FE6AE6B37D2A, 0xC3CE3A24E57524FC}, Canonic: "item.tag.link.main"},       // 1RQ3Z6PTPMGNPD7MJU4MKRB97W
	ItemVis:           tag.Name{ID: tag.UID{0x5B54B02DB28E8EF9, 0x0AE7886178A1CA4E}, Canonic: "item.tag.vis"},             // 2VBKS2VDNFJVWHPTW8D5WB3KKF
	ItemBehaviors:     tag.Name{ID: tag.UID{0xB75CB32EA769E591, 0x0021078330DAE19E}, Canonic: "item.tags.behaviors"},      // 5RCKTKX9V9WQ8H0887HDSEPSDY
	ItemGlyphs:        tag.Name{ID: tag.UID{0xEE43A6D5936D0774, 0x688B4FDE07BA993C}, Canonic: "item.tags.glyphs"},         // 7F8FMEC4VE0XU6J2UGVS3VP69W
	ItemLinks:         tag.Name{ID: tag.UID{0xE89203E570B3684E, 0xC9088CEB810A9572}, Canonic: "item.tags.links"},          // 78K81YBW5ME17DK24DXF0HP5CK
	ItemCameraState:   tag.Name{ID: tag.UID{0x18E764034A5B20FD, 0x53FEC933E18782D4}, Canonic: "item.camerastate"},         // 0SWXK06KKV43YP7ZQ96GHSG0QN
	ItemCameraOptions: tag.Name{ID: tag.UID{0xEF9DCA7B29C45C47, 0xBB03A56AA33F6432}, Canonic: "item.cameraoptions"},       // 7GMR57QBF4CJ3VQ0X5EBJMYT1K
	ItemAtmosphere:    tag.Name{ID: tag.UID{0x8718C93E8B1E2B4C, 0xB09A9629ED2B9B9B}, Canonic: "item.atmospherespec"},      // 47334MX2SY5E6C16NQ57QKR6WV
	ItemFSInfo:        tag.Name{ID: tag.UID{0xA1E0C4997B686974, 0x8D3FE7CCD220FE74}, Canonic: "item.fsinfo"},              // 51W329KYV8E5U8UGZ7TM921ZMN
	GlyphTag:          tag.Name{ID: tag.UID{0x1D8CBE271B52879E, 0x85F5B26AEA77F435}, Canonic: "item.glyph.tag"},           // 0XJKZ2F6UKHYG8CXEKECP7GX1P
	TileAttr:          tag.Name{ID: tag.UID{0xBF3216B40F0EE8E3, 0x9E0C1A4B0E2789C8}, Canonic: "item.tile"},                // 5Z68CC83SFX3JTW30U9D72G2F8

	TileLayout: tag.Name{ID: tag.UID{0x0D7B88E4A44AC047, 0xABD63B92B2AB46D7}, Canonic: "item.tile.tag.layout"}, // 0EGF4F992BS13URPJVKBTBQJQR
	ItemSeries: tag.Name{ID: tag.UID{0x647B2CF1DF98191A, 0xFF84E8A015C7C0BB}, Canonic: "item.series"},          // 34GDQG3RWS34EGZ178N0BWGH5V

	SeriesTRS:      tag.Name{ID: tag.UID{0xE9D0FE9CBE647199, 0x63524D7EB6E49423}, Canonic: "item.series.TRS"},            // 79U3Z9TGM4F6DQ6NKEGUVF9513
	SeriesLabels:   tag.Name{ID: tag.UID{0x64DF54E7607F2F0E, 0xE02A46D568115245}, Canonic: "item.series.labels"},         // 34VXBFFS3Z5W7F0BK6UPN12NK5
	SeriesAssetTag: tag.Name{ID: tag.UID{0x6A38B0B69A67BFE2, 0x046DD022E5743226}, Canonic: "item.series.tag.asset"},      // 3B72SCE6M7RZJ08VFH4CKR8DJ6
	SeriesHeadLink: tag.Name{ID: tag.UID{0xB53FF14221D2395A, 0x13E86D2EBB019E3F}, Canonic: "item.series.tag.link"},       // 5P7ZSN48FK75E17U3E5UXH37JZ
	SeriesLinkTree: tag.Name{ID: tag.UID{0xDB22686C45264AF3, 0x33E6E69F1A5D9E7C}, Canonic: "item.series.tags.link.tree"}, // 6V49N6SJ969CTM7TR6MWE5V7MW
	SeriesS2R:      tag.Name{ID: tag.UID{0x01F3B6F1011A3461, 0xB95F3BAC5E740555}, Canonic: "item.series.S2.r.mm"},        // 01YFVG208U6JHVKRTVPJG781BP
	SeriesS2T:      tag.Name{ID: tag.UID{0xF312A66F7997D4DF, 0xA939F8D7E498ED62}, Canonic: "item.series.S2.UTC64"},       // 7M2BM6YYDRUMGUKFGSUZK9JVC2
	MediaLink:      tag.Name{ID: tag.UID{0x4DED4FC2D91C296A, 0x44D348001E677047}, Canonic: "item.media.link.tag"},        // 2EXP7W5Q8W55P49NU800G6FW27
	MediaRelease:   tag.Name{ID: tag.UID{0x6C5BC935E454FEC6, 0x6F4F5F1B04975D0E}, Canonic: "item.media.release"},         // 3DCG4MCT2NZV36YMUZ3D29FR8F
	MediaItem:      tag.Name{ID: tag.UID{0xF8CF20D20A67B40F, 0x9D8F1F0071CDFBF5}, Canonic: "item.mediaitem"},             // 7STWHE42M7QH7TV3SZ01SWVYZP
	MediaPlaylist:  tag.Name{ID: tag.UID{0x3DAB9BFD75B29097, 0x7EE88C07BE024476}, Canonic: "item.mediaplaylist"},         // 1XPFEZUXEKK2CRXU4D0YZ04J3Q

	// ─── Channel metadata and catalog ───────────────────────────────
	ChannelAttr: tag.Name{ID: tag.UID{0x3C0BCCB260A85864, 0xC4DF8E1CD985DD60}, Canonic: "channel"}, // 1W1G6C4S58C1KD9RWF3MDSCRC0

	ChannelCatalog:        tag.Name{ID: tag.UID{0x2677628531BECA52, 0x034FC22E4BB05B8C}, Canonic: "channel.catalog.channelepoch"},      // 16FXJ8BDEYT9906MY25T5V0QWD
	ChannelEpochs:         tag.Name{ID: tag.UID{0x46671B0AF50329A0, 0x6C63540862D1B521}, Canonic: "channel.channelepoch"},              // 26DWEHPX8356H6SSUN11JE3E91
	ChannelPropertySeries: tag.Name{ID: tag.UID{0x35C4FC8DB15756BE, 0x94B84BDA369A0177}, Canonic: "channel.property.series.jsonvalue"}, // 1PSMY8VDBRBUZ99F2CV8V9N0CR

	ChannelPropertyLabel:       tag.Name{ID: tag.UID{0xF7C87A5DC3025A6B, 0x62451D178A230942}, Canonic: "channel.property.series.jsonvalue.label"},       // 7RT1X5VHS2C9PQ4J8X2Y5262B2
	ChannelPropertyDescription: tag.Name{ID: tag.UID{0xD26B185D4D0E180D, 0x10CC7625CBD6B999}, Canonic: "channel.property.series.jsonvalue.description"}, // 6KEDD5UM8F306J1M3Q4R5XEFDT
	ChannelPropertyGlyph:       tag.Name{ID: tag.UID{0xAE095B7DD0477B81, 0x9D2209318CB11B4A}, Canonic: "channel.property.series.jsonvalue.glyph"},       // 5F15ERVN27GF0TU8H9666C26UB
	ChannelPropertySkybox:      tag.Name{ID: tag.UID{0xFBDB14B7FE48F62B, 0x902F51D9718AF1C0}, Canonic: "channel.property.series.jsonvalue.skybox"},      // 7VVDBCGZK8YSPT0CUJV5SSPWF0
	ChannelPropertyGrid:        tag.Name{ID: tag.UID{0x4128F9AAC9CC12E3, 0xFEDEA64C3C3FDF40}, Canonic: "channel.property.series.jsonvalue.grid"},        // 2153WUPKFD2CJZXRP69HY3ZRU0
	ChannelType:                tag.Name{ID: tag.UID{0xE16EE14B4532E786, 0x8166AD32465165B0}, Canonic: "channel.type"},                                  // 71EVHNQJ9KWY382TPE69352TEH

	ChannelTypeSpreadsheet:  tag.Name{ID: tag.UID{0x1C0062A36805F2FB, 0xC37F9A8B51C0A909}, Canonic: "channel.type.spreadsheet"},  // 0W01JB6U05YCXW6ZWUJE8W1B89
	ChannelTypeMessages:     tag.Name{ID: tag.UID{0x0B6D6A2421321CA6, 0xFBA2073C02B917A6}, Canonic: "channel.type.messages"},     // 0CEPP2889K3KMGR8H77H1CK5X6
	ChannelTypeTimeline:     tag.Name{ID: tag.UID{0xCAA590A1B24C80D3, 0xF0D695C6FDB81BC9}, Canonic: "channel.type.timeline"},     // 6BNQ8B3DKDH39Z1PNPSVYVH6Y9
	ChannelTypeNotes:        tag.Name{ID: tag.UID{0x7F066E7E15634C8E, 0x2B42527E940C4785}, Canonic: "channel.type.notes"},        // 3Z0TR7W5C39K72QHKKGUB0SJW5
	ChannelTypeMap:          tag.Name{ID: tag.UID{0x461600979AF3D842, 0x5A0DB0A3BDCC6D2C}, Canonic: "channel.type.map"},          // 262S09G6RMV115N3EHNFYWSV9D
	ChannelTypeGlobe:        tag.Name{ID: tag.UID{0x5AE48F27C6756F95, 0xD710170F8601E1CA}, Canonic: "channel.type.globe"},        // 2UWK7KGJMPEYBXF40R1Y303SFB
	ChannelTypeManifold:     tag.Name{ID: tag.UID{0x4CBB7B8671F99205, 0xF3E8260DB0811029}, Canonic: "channel.type.manifold"},     // 2DREXSDWGTK82Z7U161QS82419
	ChannelTypeSpace:        tag.Name{ID: tag.UID{0x7A73CEC90BFC9F74, 0x5A5DE66730642BD4}, Canonic: "channel.type.space"},        // 3UFG7DK2ZWMXU5NRG6DWS68BYN
	ChannelTypeLinks:        tag.Name{ID: tag.UID{0x0F753C0ED5870184, 0x1FC3120334FEC794}, Canonic: "channel.type.links"},        // 0GFNY0XPD70621ZHSK0DUGXJWN
	ChannelTypeRegistry:     tag.Name{ID: tag.UID{0xB9BF3D6330F504B7, 0xE0B97F3A75A18971}, Canonic: "channel.type.registry"},     // 5TRWYQ6D7P0KVY1FCZ79UU32CJ
	ChannelTypeSystem:       tag.Name{ID: tag.UID{0xBAAE45A1E50DB5D6, 0xA110D0DF2A2A8A6B}, Canonic: "channel.type.system"},       // 5UPT2U3T8EQRCB246HVWP2P2MC
	ChannelTypeWeb:          tag.Name{ID: tag.UID{0x0E85824C4CAE1CCD, 0x03B61877597F1503}, Canonic: "channel.type.web"},          // 0FHQ14SM5F3M6H7EHSFXDRY583
	ChannelTypeCrateManager: tag.Name{ID: tag.UID{0x9E74B4232D25A550, 0x3FAB0CD74C29B100}, Canonic: "channel.type.cratemanager"}, // 4YFKU26C95NP83ZBSDUX62MD80
	ChannelTypePlaylist:     tag.Name{ID: tag.UID{0x13359329BB89DC00, 0x0A5737DF5CC11363}, Canonic: "channel.type.playlist"},     // 0M6Q9KMFW9VH00NPTRVXFD24V3
	ChannelTypePicker:       tag.Name{ID: tag.UID{0xD2EBF18403D0BFF7, 0x94A830AA64236EE9}, Canonic: "channel.type.picker"},       // 6KXGSS80YHRZVT9B1HP9K26VR9
	ChannelTypePlanetPicker: tag.Name{ID: tag.UID{0x235A1464B1A9B829, 0xA3F82B96FE207780}, Canonic: "channel.type.planetpicker"}, // 13C8B69DE9R0NU7Y1CKVZ20XW0
	ChannelTypeBrand:        tag.Name{ID: tag.UID{0xB65147BCC3C55E4C, 0x9BE811A46788AFF8}, Canonic: "channel.type.brand"},        // 5QB53VTHY5CT69RU0JNJMSJCZS
	ChannelTypeNameService:  tag.Name{ID: tag.UID{0xE2BA6A5DBCA4EC87, 0x3B64FA486677CFBA}, Canonic: "channel.type.name.service"}, // 72R9P5VG54XK3MQT7U91M7GMXU

	// ─── Brand — substrate-native planet identity (PRD-name-service.md §2). ───
	// Single item per planet at (HeadNodeID, amp.brand, amp.brand.UID); the genesis
	// TxOp at EditID=0 welds identity-tier fields to the planet's cryptographic root.
	Brand: tag.Name{ID: tag.UID{0xB70889689791764B, 0xB554FC786AE221AE}, Canonic: "amp.brand"}, // 5R124QJ5WJFT5VBP7WG1PF48EF

	// ─── NameService — substrate-native naming primitive (PRD-name-service.md §3). ───
	// A channel any planet may host; records map FQDN → tag.UID with bootstrap metadata.
	// Federations propagate their channel to members via normal CRDT sync.
	// Generalized beyond planet naming — any UID-bearing entity is namable.
	NameService: tag.Name{ID: tag.UID{0xB363152A99B543E3, 0x44B6A07DD731D29D}, Canonic: "amp.name.service"}, // 5MDDBKP6EP8GJN9EP0GRCM3NNX

	NameServiceRecord: tag.Name{ID: tag.UID{0x46F3C16F52B61C22, 0x7C5C870E89180A36}, Canonic: "amp.name.service.record"}, // 26YG0QYNPQ3HJ7SR471U4JH2JQ

	// ─── Federation directory — peer / parent federation pointers (PRD-name-service.md §4.3). ───
	// NS-record-style cross-federation forwarding without DNS dependency.
	FederationDirectory: tag.Name{ID: tag.UID{0x9D75EA0B352ABCF1, 0xE8235D89C9A7D3F9}, Canonic: "amp.federation.directory"}, // 4XFRP0QE9BRMSYH8UXJ74UGNZT

	// ─── Planet governance — the law-making channel (sibling of amp.ledger + amp.arbitrate). ───
	// "Law" names the role concretely: this channel grants, revises, and revokes
	// the permissions other channels inherit.
	LawAttr: tag.Name{ID: tag.UID{0xB8D21569231305B8, 0xF74881C639EB11E5}, Canonic: "amp.law"}, // 5SU8BQK8SM0QWGFK41SSWYQ4G5

	LawPlanetEpoch:  tag.Name{ID: tag.UID{0x62F9D4DD32683CE3, 0x1D28B3308B06594F}, Canonic: "amp.law.planetepoch"},  // 32Z7BEUDM87MJJUB5M625HDQBG
	LawMemberEpoch:  tag.Name{ID: tag.UID{0xD4D5E6BE48B6D994, 0x19B1DB5E98597C29}, Canonic: "amp.law.memberepoch"},  // 6NURMCWK5QV6B1MDFVCUD5KZ19
	LawChannelEpoch: tag.Name{ID: tag.UID{0xC49076CDFEB23BBF, 0xAD7271CB90287F97}, Canonic: "amp.law.channelepoch"}, // 64K1VDVZPK7FZUUWMJTF82HZWR
	LawPlanetOrigin: tag.Name{ID: tag.UID{0x6C8CDF082B47A29E, 0xCC572ADCF4282E79}, Canonic: "amp.law.planetorigin"}, // 3DJMGHHBU7NBGDSPTBVMU2HCMT
	LawEquivalence:  tag.Name{ID: tag.UID{0x99F3808D1F407BE6, 0x2E656BA55F1738FE}, Canonic: "amp.law.equivalence"},  // 4TYF08U7U0GGM2WTCCNPGJFF7Y
	LawWithdraw:     tag.Name{ID: tag.UID{0x850B8DAE8EC87EF2, 0x228AC81879D663ED}, Canonic: "amp.law.withdraw"},     // 451F6UX3Q8GVT252Q831WXDSZE
	// Substrate-agnostic Member Kind (DESIGN-11).  MemberEpoch.Kind is a Tag
	// resolving to one of these UIDs.  Communities + apps may register
	// additional Kinds in their own consts.sdl.  Zero UID = unspecified.
	LawMemberKind: tag.Name{ID: tag.UID{0x102047CBC77F0A3E, 0x5C2BBD3DA4EA137C}, Canonic: "amp.law.memberkind"}, // 0H413WRJVZ18Z5SBXX7QKFN4VW

	LawMemberKind_Person:    tag.Name{ID: tag.UID{0x9066A58EE8084472, 0x7ECCB4DC966DA647}, Canonic: "amp.law.memberkind.person"},    // 4HDUKSXU088JT7XM5NVKC6V9K7
	LawMemberKind_Group:     tag.Name{ID: tag.UID{0xEF2C5586176DEED8, 0x5B05F595BBE5600D}, Canonic: "amp.law.memberkind.group"},     // 7G5JBSD5VEXVD5Q1GPKQXYBS0E
	LawMemberKind_Agent:     tag.Name{ID: tag.UID{0x749E0C48FD2107B3, 0x929ECFA81FC32124}, Canonic: "amp.law.memberkind.agent"},     // 3NMS64JZ910YTT57QGP0GW6894
	LawMemberKind_Instance:  tag.Name{ID: tag.UID{0xB7889D1CF912DC06, 0xFDF984BBDFA0D5BB}, Canonic: "amp.law.memberkind.instance"},  // 5RJ2FJTY8KVH3GVYD4RGGU1PEV
	LawMemberKind_Successor: tag.Name{ID: tag.UID{0x627C11221E4584F9, 0xCD00ACCD3211B4F9}, Canonic: "amp.law.memberkind.successor"}, // 32GH8K47K5HMWWU05DTNT13E7T
	LawMemberKind_Memorial:  tag.Name{ID: tag.UID{0xBA335B3927C0252B, 0xB791D002F55B477F}, Canonic: "amp.law.memberkind.memorial"},  // 5U6EEMK9Y04NPVG4FH0CUPQJVZ
	LawMemberKind_Process:   tag.Name{ID: tag.UID{0x98ECE8E691BE5BD5, 0x7E0A29F6F4393466}, Canonic: "amp.law.memberkind.process"},   // 4SXMNFE4EYCGBRW2J9YVU3KE36
	// Modal Attestation modalities (DESIGN-13).  Attestation.Modality is a
	// Tag resolving to one of these UIDs.  Communities + apps may register
	// additional modalities.  Zero UID = unspecified.
	LawAttestationModality: tag.Name{ID: tag.UID{0x9F5377F513757A9F, 0x74B304390F47261B}, Canonic: "amp.law.attestationmodality"}, // 4ZBEVZB4VPGBGR9DS4747NF9HV

	LawAttestationModality_Asserted:    tag.Name{ID: tag.UID{0x75C91DBFE351CFA4, 0xBDF0BBC9911BA504}, Canonic: "amp.law.attestationmodality.asserted"},    // 3PT4FVZSUJTYKCVW5VT68JR984
	LawAttestationModality_Witnessed:   tag.Name{ID: tag.UID{0xEDF2976BE9E0FC72, 0xA1AA047BE5D91C2F}, Canonic: "amp.law.attestationmodality.witnessed"},   // 7EYBCQRUG0ZJTB3BH4GGKXK71G
	LawAttestationModality_Reported:    tag.Name{ID: tag.UID{0x01ABA5357F784D15, 0x96F49237F6805E56}, Canonic: "amp.law.attestationmodality.reported"},    // 01PFKMBZVS9NBTEX4K6ZV80RKQ
	LawAttestationModality_Inferred:    tag.Name{ID: tag.UID{0x586F8C9352B3899C, 0x8F41E2BF1D0BB521}, Canonic: "amp.law.attestationmodality.inferred"},    // 2SEY696NPMJ6F8YHG2RWFHRE91
	LawAttestationModality_Speculated:  tag.Name{ID: tag.UID{0xB39330159C4E87E1, 0xF842FF134BF859C2}, Canonic: "amp.law.attestationmodality.speculated"},  // 5MKDS1C72FHZHZHHRZ2E5ZHQF2
	LawAttestationModality_Dreamed:     tag.Name{ID: tag.UID{0xAC2C17267CD4DF9B, 0x94DD976E325E51B4}, Canonic: "amp.law.attestationmodality.dreamed"},     // 5D5HCKDZ6NVYET9RDREST5WNEN
	LawAttestationModality_Liturgical:  tag.Name{ID: tag.UID{0x801C1A7DF12F7128, 0xFA0D77ADD9E695AB}, Canonic: "amp.law.attestationmodality.liturgical"},  // 403HE7VW9GF4NGN3CRPRDYE5EC
	LawAttestationModality_Conditional: tag.Name{ID: tag.UID{0x84466F1352512715, 0x29E493F726901576}, Canonic: "amp.law.attestationmodality.conditional"}, // 448TRJ6NKJ4WBKMT4MYWM905CQ
	LawAttestationModality_Contested:   tag.Name{ID: tag.UID{0x0502182AD6D3BDB4, 0xC9F14651631969E3}, Canonic: "amp.law.attestationmodality.contested"},   // 0508D2PPQMRQUDMWB6B5JJKUG3
	LawAttestationModality_Retracted:   tag.Name{ID: tag.UID{0xCA955565A08728E6, 0x4FCC6CCB72D595CB}, Canonic: "amp.law.attestationmodality.retracted"},   // 6BKPBQC84753M4ZM3DTETEC5FC
	// Equivalence strengths (DESIGN-14).  Equivalence.Strength is a Tag
	// resolving to one of these UIDs.  Zero UID = unspecified.
	LawEquivalenceStrength: tag.Name{ID: tag.UID{0x17501E56DC9B1A5D, 0x19F49F4EF6B49F84}, Canonic: "amp.law.equivalencestrength"}, // 0RB0G5ER4V39FJMX4Z9VVC97W4

	LawEquivalenceStrength_Identity:    tag.Name{ID: tag.UID{0x7A180A04688254AF, 0xEDCDADDC2F98FC54}, Canonic: "amp.law.equivalencestrength.identity"},    // 3U30508U42BKRYVMEEVHRTJZ2N
	LawEquivalenceStrength_Translation: tag.Name{ID: tag.UID{0x8D295A1372FA2C5D, 0x10798077BE8E1B1A}, Canonic: "amp.law.equivalencestrength.translation"}, // 4E55E16WRU5JFJ0YD0FYZ8W6SU
	LawEquivalenceStrength_Approximate: tag.Name{ID: tag.UID{0x90E61D55697A0D3C, 0xA6613FC42F78EF78}, Canonic: "amp.law.equivalencestrength.approximate"}, // 4HWSFPBUCU1NYBDS9ZSHRRJVVS
	LawEquivalenceStrength_Analogous:   tag.Name{ID: tag.UID{0x112A5CA73BB8C091, 0x8A80533CC1EC7186}, Canonic: "amp.law.equivalencestrength.analogous"},   // 0J59FBFFXSS28SP02M7M0YSWD6
	// Withdrawal reasons (DESIGN-15).  Withdraw.Reason is a Tag resolving
	// to one of these UIDs.  Zero UID = unspecified.
	LawWithdrawReason: tag.Name{ID: tag.UID{0x72FDAD1F33EAB71A, 0x6643A4A97C032829}, Canonic: "amp.law.withdrawreason"}, // 3KZQQJYDZBQWE6DHX4P5Y06B19

	LawWithdrawReason_Consent:      tag.Name{ID: tag.UID{0x4AD66B3839C79795, 0x6DD78A8C11DC59F0}, Canonic: "amp.law.withdrawreason.consent"},      // 2BUTPMHFF7KYBQVPWBJH8XSQGH
	LawWithdrawReason_Inaccuracy:   tag.Name{ID: tag.UID{0x17501A166D3A425C, 0xA91DD4F561E2CB93}, Canonic: "amp.law.withdrawreason.inaccuracy"},   // 0RB0E1DV9U89FBK7FNYPHY5KWM
	LawWithdrawReason_Outdated:     tag.Name{ID: tag.UID{0xAAC00FC9DDCE0FCB, 0xE6859461FE7A1D4F}, Canonic: "amp.law.withdrawreason.outdated"},     // 5BS07WMRFF1Z5YE1DND7Z7N7BG
	LawWithdrawReason_Coerced:      tag.Name{ID: tag.UID{0xF49C167CF4CAFF70, 0xEB1DCBB71E6D98A1}, Canonic: "amp.law.withdrawreason.coerced"},      // 7NMHC7TX6BZXSFQ7FCQWG6V651
	LawWithdrawReason_Forgotten:    tag.Name{ID: tag.UID{0x8E3232ED30CC6260, 0x0BE1A6A4E66AEE93}, Canonic: "amp.law.withdrawreason.forgotten"},    // 4F68TFUD6DD9H0RSE6NMM6PVNM
	LawWithdrawReason_Departed:     tag.Name{ID: tag.UID{0x13C1FB18E732E44E, 0x5EE266E36A490A3A}, Canonic: "amp.law.withdrawreason.departed"},     // 0MS7XJJTTKWJ75XSM6WEP4K2JU
	LawWithdrawReason_InviteRecall: tag.Name{ID: tag.UID{0x1E4FCBCAB504D83C, 0xF6B5D654AF78F091}, Canonic: "amp.law.withdrawreason.inviterecall"}, // 0Y9Z5WPE84V0YGEEFQBKRRJW4J
	LawWithdrawReason_Retracted:    tag.Name{ID: tag.UID{0xD9CBFFFA74C3D8E7, 0x77AC984C332610A6}, Canonic: "amp.law.withdrawreason.retracted"},    // 6TTGZZNX63V3MRGC4S9HTKD456

	// ─── Planet ledger — durable record of observations and citations. ───
	// Attestations (strikes, endorsements, witness records, audits, amnesties)
	// live here as convergent TxOps.  Admin acts in the ACC cite entries from
	// the ledger via AttestationRef, making every governance decision auditable.
	LedgerAttr: tag.Name{ID: tag.UID{0x82BC4E1F6FB05241, 0x03CA388E1C44C848}, Canonic: "amp.ledger"}, // 42RJ71YVXHB90H7KJSJSF49K28

	LedgerAttestation: tag.Name{ID: tag.UID{0x3C774A8A36241368, 0x2074703AFA0EF846}, Canonic: "amp.ledger.attestation"}, // 1WFX58NEJ42EN20X3H7CX0XY26

	// ─── Member lifecycle ───────────────────────────────────────────
	MemberAttr: tag.Name{ID: tag.UID{0x4CCC7C4A23169DBF, 0x2EC0059288020E9F}, Canonic: "amp.member"}, // 2DTJY4N8SQMQZKXH05KB4043NZ

	PlanetInvite:   tag.Name{ID: tag.UID{0x6FEE6335FCDBCE81, 0x4BA0971C012DEF93}, Canonic: "amp.member.planetinvite"},   // 3GXTJMCZ6VTU0NR84R3H0KVVWM
	PlanetInviteOp: tag.Name{ID: tag.UID{0x282E9002D3DEC1D9, 0x4E7FE61F5118FF87}, Canonic: "amp.member.planetinviteop"}, // 185U805NYYS7DNWZZ63X8JJZW7

	// ─── Home planet attributes ─────────────────────────────────────
	HomeAttr: tag.Name{ID: tag.UID{0x45A5C59F62D1113F, 0x73AEED98C41EFBFA}, Canonic: "amp.home"}, // 25NR2TYSQJ24ZR7CREM321XYZU

	PlanetBinding:     tag.Name{ID: tag.UID{0xD1107652908E11D6, 0x1B2B3BC082553787}, Canonic: "amp.home.planet.binding.tag"},               // 6J21V5544F27C1QBTVS215BEW7
	PlanetStorageOpts: tag.Name{ID: tag.UID{0x69BFD182C13A9A31, 0xF66973A8296693D5}, Canonic: "amp.home.planet.storage.planetstorageopts"}, // 39RZ8S5H9UM8SZDUCMP0NQE4YP

	// ─── System properties ──────────────────────────────────────────
	SystemPropertyAttr: tag.Name{ID: tag.UID{0x2BA3C11AEAB12331, 0xCAFD58A215C24C83}, Canonic: "system.property"}, // 1CNG0JPUPJ4DSWPZBSN8BW4M43

	SpaceReticleStyle:   tag.Name{ID: tag.UID{0x898D209EB3284EB4, 0x6854FCADE835E46C}, Canonic: "system.property.reticle.style"},   // 49JNH9XDT89UU6HP7WPRN3CT3D
	SpaceReticleOverlay: tag.Name{ID: tag.UID{0x31C05BF7F1CE5245, 0x3A9ECBD90E6673D1}, Canonic: "system.property.reticle.overlay"}, // 1JS1EZGWFFB92MP7QCV476DWYJ
	SpaceSkybox:         tag.Name{ID: tag.UID{0x101BF55A052215FA, 0x8E0BC10873E916AC}, Canonic: "system.property.skybox.space"},    // 0H3GUPN1922RX8W2Y111TYK5PD

	// ─── Blob storage ───────────────────────────────────────────────
	BlobAttr: tag.Name{ID: tag.UID{0x43839888952F19F9, 0xB576A64453AD2634}, Canonic: "amp.blob"}, // 23HFD8J59G37WVBXP68J9UU9JN

	BlobRef:   tag.Name{ID: tag.UID{0xAEE1E83EB38BBF5D, 0x17C1EF094E5F4850}, Canonic: "amp.blob.ref"},           // 5FW7N3XDWCRXFJGHGG1575YK2H
	NodeBlobs: tag.Name{ID: tag.UID{0x306CC090FC4E717C, 0xFECED441B9B156B5}, Canonic: "amp.blob.node.blobrefs"}, // 1HEM091Z2FF5YGXMQN86WV2PPP

	// ─── Tile-server registry — list of available raster / terrain / vector ───
	// tile backends.  Each entry is a TileServer proto stored as one item
	// under TileServer; consumers (TileService, manifold compositor) filter
	// by Kind / Projection / region tags to assemble a layer stack.
	TileServerAttr: tag.Name{ID: tag.UID{0xD5FC9ECEE1CD0384, 0xDD46B5FC1E37D2F4}, Canonic: "tile.server"}, // 6PZKGDXSFE0F2EUJPPZHG3GNRN

	TileServer: tag.Name{ID: tag.UID{0xE33FC73D7E59EC57, 0x935C14FC5D1E29A2}, Canonic: "tile.server.tileserver"}, // 737Z3MUZKTXJCT6R0NZJFJWBE2
}

const (
	ContentGlyphURI  = "asset:glyph/"
	GenericImageType = "image/*"
	GenericAudioType = "audio/*"
	GenericVideoType = "video/*"
	BulletSeparator  = " · "
)

// ─── Session-scope well-known IDs. ──────────────────────────────
// ContextID is attached to TxMsgs that carry session-level meta-ops
// (login, logout, status) so the receiving session can match request/response.
var (
	SessionContextID = tag.UID{0x0, 0x777}
)

const (
	// Canonic URI scheme prefix for amp asset references (matches UriScheme.Asset).
	AssetScheme = "asset:"
)

const (
	PlanetInviteFileExt = ".planet-invite"
)

// ─── Glyph URIs ─────────────────────────────────────────────────
const (
	GlyphWebLink       = "asset:glyph/web.link"
	GlyphDefaultNode   = "asset:glyph/default.node"
	GlyphAssetNotFound = "asset:glyph/asset.not.found"
	GlyphNewLocation   = "asset:glyph/new-location"
)

// ─── Manifold (3D globe / sphere channel) — modding override points. ───
// Each URI resolves through the crate / asset system; a mod can register
// an override at the same key to swap implementations without touching code.
//
// TileLayers ship as prefab GameObjects (TileLayer MonoBehaviour attached);
// loaders Instantiate as a child of GlobeInstance to enable the layer.  Mods
// register their own layer prefab at the same URI to swap layers without
// touching core code.
const (
	ManifoldDefaultTileMaterial = "asset:manifold/tile.material.default"
	ManifoldDefaultVolumePrefab = "asset:manifold/volume.prefab.default"
	ManifoldDebugGridTileLayer  = "asset:manifold/tile.layer.debug-grid"
)

// ─── Atmosphere — stock URIs for the four-category atmosphere composition. ───
// Each URI resolves through a built-in param-bundle switch today and an
// AssetRequest pipeline later (the moddable path: a planet ships a
// custom sky / sun / night / fog effect under its own URI).  Empty
// string on an AtmosphereSpec field disables that category.
const (
	// Category labels — AtmosphereEffect.Label values that identify which of
	// the four functional axes an entry contributes to.  Mods may register
	// additional labels in their own consts.sdl, but the v240 renderer only
	// honors the four canonical categories.
	AtmosphereLabelSky   = "Sky"
	AtmosphereLabelSun   = "Sun"
	AtmosphereLabelNight = "Night"
	AtmosphereLabelFog   = "Fog"
	// Category defaults — picked when an AtmosphereEffect has Enabled = true
	// and URI is empty.  Empty URI in an enabled entry means "use whatever
	// ships as the default for this category"; this is where they live.
	AtmosphereSkyEarth       = "asset:atmosphere/sky/earth"       // blue zenith → soft white horizon + limb sheen
	AtmosphereSkyMars        = "asset:atmosphere/sky/mars"        // dusty pink zenith, ochre horizon
	AtmosphereSkyNoir        = "asset:atmosphere/sky/noir"        // monochrome cool blue
	AtmosphereSunStandard    = "asset:atmosphere/sun/standard"    // sunset / terminator / HG forward scatter (legibility-cost)
	AtmosphereNightStandard  = "asset:atmosphere/night/standard"  // night-side dim + cool tint
	AtmosphereFogExponential = "asset:atmosphere/fog/exponential" // exponential aerial perspective; seam-hider, on by default
	// Inspector defaults — 0 on the serialized field means "unset, use this".
	AtmosphereDefaultNightDimmer    = float32(0.3)    // 0 = pitch black night limb; default reaches 70% dim
	AtmosphereDefaultFogScaleMeters = float32(100000) // e-folding distance; ~63% opacity at this distance, asymptotes
	AtmosphereDefaultFogSunWarmth   = float32(2)      // sun-aligned warm sharpness on the fog mix (pow exponent)
	AtmosphereDefaultMieG           = float32(0.76)   // HG asymmetry; typical Mie aerosol forward peak
	AtmosphereDefaultMieStrength    = float32(0.5)    // HG glow amplitude on the outer shell sunset
)

// ─── Bundled crate URIs — platform-wide crates every amp client imports at boot. ───
// BaseAssets/VisAssets are platform-fixed; brand-specific bundled crates live in
// Brand.BundledCrates (PRD-name-service §2).  Each URI is asset:PublisherID/CrateID
// per the wire scheme declared in amp.core.proto:Asset; the build pipeline stages
// matching .crate files under StreamingAssets/Bundled/CrateDepot.
const (
	CratesBaseAssets = "asset:crates.planet.tools/amp.3D.base.assets"
	CratesHelloWorld = "asset:crates.planet.tools/amp.3D.hello.world"
	CratesVisAssets  = "asset:soundspectrum.com/amp.3D.vis.assets"
)

// ─── Actor — in-world actor skins resolve through the crate / asset ───
// system; a mod registers an override at the same key to ship a custom
// actor without touching code.  An unresolved URI falls back to a
// primitive so a ManifoldActor is always visible.
const (
	ActorDefaultSkin             = "asset:actor/skin.default"
	ActorDefaultBodyHeightMeters = float32(1.6) // composed-body height (m)   when the field is 0
	ActorDefaultBodySides        = int32(6)     // composed-body facets       when the field is 0
	ActorDefaultEyeHeightMeters  = 1.7          // eye reference (m)          when the field is 0
	ActorDefaultOrbitDegPerSec   = float32(8)   // signature orbit rate (deg/s) when the field is 0
)

// ─── Locus spatial binding ──────────────────────────────────────
const (
	LocusBits         = uint32(6)    // cell index bit width
	LocusSpan         = uint32(0x40) // total cells per locus (1 << Bits)
	LocusMask         = uint64(0x3F) // low 6-bit extraction mask
	LocusHexCells     = uint32(37)   // 3 hex rings: 1+6+12+18
	LocusCompassStart = uint32(56)   // first compass rose cell index
	LocusCompassCells = uint32(8)    // N, NE, E, SE, S, SW, W, NW
	LocusTier0        = uint32(1)    // center only
	LocusTier1        = uint32(7)    // center + ring 1
	LocusTier2        = uint32(19)   // + ring 2
	LocusTier3        = uint32(37)   // + ring 3
)
