// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: amp.status.proto

package status

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strconv "strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Code expresses status and error codes.
type StatusCode int32

const (
	Nil                        StatusCode = 0
	Unnamed                    StatusCode = -23001
	AssertFailed               StatusCode = -23002
	UnsupportedOp              StatusCode = -23003
	Unimplemented              StatusCode = -23004
	Timeout                    StatusCode = -23005
	ShuttingDown               StatusCode = -23006
	NotConnected               StatusCode = -23007
	AuthFailed                 StatusCode = -23008
	LoginFailed                StatusCode = -23009
	Expired                    StatusCode = -23010
	NotReady                   StatusCode = -23011
	Cancelled                  StatusCode = -23012
	ItemNotFound               StatusCode = -23013
	ParseFailed                StatusCode = -23014
	StartupFailed              StatusCode = -23015
	ContextNotReady            StatusCode = -23020
	RequestClosed              StatusCode = -23021
	BadRequest                 StatusCode = -23022
	BadTag                     StatusCode = -23023
	BadValue                   StatusCode = -23024
	AlreadyExists              StatusCode = -23025
	AttrNotFound               StatusCode = -23026
	NothingToCommit            StatusCode = -23027
	CommitFailed               StatusCode = -23028
	StorageFailure             StatusCode = -23030
	MalformedTx                StatusCode = -23032
	BadSchema                  StatusCode = -23040
	DataFailure                StatusCode = -23041
	ExportErr                  StatusCode = -23042
	PinFailed                  StatusCode = -23043
	ProviderErr                StatusCode = -23045
	ViolatesAppendOnly         StatusCode = -23050
	InsufficientPermissions    StatusCode = -23051
	CryptoKitAlreadyRegistered StatusCode = -23100
	UnrecognizedCryptoKit      StatusCode = -23101
	DecryptFailed              StatusCode = -23102
	VerifySignatureFailed      StatusCode = -23103
	BadKeyFormat               StatusCode = -23104
	KeyGenerationFailed        StatusCode = -23105
	KeyringNotFound            StatusCode = -23106
	KeyEntryNotFound           StatusCode = -23107
	HashKitNotFound            StatusCode = -23108
	UnrecognizedCryptOp        StatusCode = -23110
	MarshalFailed              StatusCode = -23111
	UnmarshalFailed            StatusCode = -23112
)

var StatusCode_name = map[int32]string{
	0:      "Nil",
	-23001: "Unnamed",
	-23002: "AssertFailed",
	-23003: "UnsupportedOp",
	-23004: "Unimplemented",
	-23005: "Timeout",
	-23006: "ShuttingDown",
	-23007: "NotConnected",
	-23008: "AuthFailed",
	-23009: "LoginFailed",
	-23010: "Expired",
	-23011: "NotReady",
	-23012: "Cancelled",
	-23013: "ItemNotFound",
	-23014: "ParseFailed",
	-23015: "StartupFailed",
	-23020: "ContextNotReady",
	-23021: "RequestClosed",
	-23022: "BadRequest",
	-23023: "BadTag",
	-23024: "BadValue",
	-23025: "AlreadyExists",
	-23026: "AttrNotFound",
	-23027: "NothingToCommit",
	-23028: "CommitFailed",
	-23030: "StorageFailure",
	-23032: "MalformedTx",
	-23040: "BadSchema",
	-23041: "DataFailure",
	-23042: "ExportErr",
	-23043: "PinFailed",
	-23045: "ProviderErr",
	-23050: "ViolatesAppendOnly",
	-23051: "InsufficientPermissions",
	-23100: "CryptoKitAlreadyRegistered",
	-23101: "UnrecognizedCryptoKit",
	-23102: "DecryptFailed",
	-23103: "VerifySignatureFailed",
	-23104: "BadKeyFormat",
	-23105: "KeyGenerationFailed",
	-23106: "KeyringNotFound",
	-23107: "KeyEntryNotFound",
	-23108: "HashKitNotFound",
	-23110: "UnrecognizedCryptOp",
	-23111: "MarshalFailed",
	-23112: "UnmarshalFailed",
}

var StatusCode_value = map[string]int32{
	"Nil":                        0,
	"Unnamed":                    -23001,
	"AssertFailed":               -23002,
	"UnsupportedOp":              -23003,
	"Unimplemented":              -23004,
	"Timeout":                    -23005,
	"ShuttingDown":               -23006,
	"NotConnected":               -23007,
	"AuthFailed":                 -23008,
	"LoginFailed":                -23009,
	"Expired":                    -23010,
	"NotReady":                   -23011,
	"Cancelled":                  -23012,
	"ItemNotFound":               -23013,
	"ParseFailed":                -23014,
	"StartupFailed":              -23015,
	"ContextNotReady":            -23020,
	"RequestClosed":              -23021,
	"BadRequest":                 -23022,
	"BadTag":                     -23023,
	"BadValue":                   -23024,
	"AlreadyExists":              -23025,
	"AttrNotFound":               -23026,
	"NothingToCommit":            -23027,
	"CommitFailed":               -23028,
	"StorageFailure":             -23030,
	"MalformedTx":                -23032,
	"BadSchema":                  -23040,
	"DataFailure":                -23041,
	"ExportErr":                  -23042,
	"PinFailed":                  -23043,
	"ProviderErr":                -23045,
	"ViolatesAppendOnly":         -23050,
	"InsufficientPermissions":    -23051,
	"CryptoKitAlreadyRegistered": -23100,
	"UnrecognizedCryptoKit":      -23101,
	"DecryptFailed":              -23102,
	"VerifySignatureFailed":      -23103,
	"BadKeyFormat":               -23104,
	"KeyGenerationFailed":        -23105,
	"KeyringNotFound":            -23106,
	"KeyEntryNotFound":           -23107,
	"HashKitNotFound":            -23108,
	"UnrecognizedCryptOp":        -23110,
	"MarshalFailed":              -23111,
	"UnmarshalFailed":            -23112,
}

func (StatusCode) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_187b1a6ae9aece88, []int{0}
}

type LogLevel int32

const (
	LogLevel_Error LogLevel = 0
	LogLevel_Warn  LogLevel = 2
	LogLevel_Info  LogLevel = 4
)

var LogLevel_name = map[int32]string{
	0: "LogLevel_Error",
	2: "LogLevel_Warn",
	4: "LogLevel_Info",
}

var LogLevel_value = map[string]int32{
	"LogLevel_Error": 0,
	"LogLevel_Warn":  2,
	"LogLevel_Info":  4,
}

func (LogLevel) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_187b1a6ae9aece88, []int{1}
}

// Error is a general purpose error / warning / log message.
type Error struct {
	// Identifies the type of error.
	Code StatusCode `protobuf:"varint,1,opt,name=Code,proto3,enum=status.StatusCode" json:"Code,omitempty"`
	// Severity level
	Level LogLevel `protobuf:"varint,2,opt,name=Level,proto3,enum=status.LogLevel" json:"Level,omitempty"`
	// human-readable message
	Message string `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`
}

func (m *Error) Reset()      { *m = Error{} }
func (*Error) ProtoMessage() {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_187b1a6ae9aece88, []int{0}
}
func (m *Error) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Error.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return m.Size()
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetCode() StatusCode {
	if m != nil {
		return m.Code
	}
	return Nil
}

func (m *Error) GetLevel() LogLevel {
	if m != nil {
		return m.Level
	}
	return LogLevel_Error
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterEnum("status.StatusCode", StatusCode_name, StatusCode_value)
	proto.RegisterEnum("status.LogLevel", LogLevel_name, LogLevel_value)
	proto.RegisterType((*Error)(nil), "status.Error")
}

func init() { proto.RegisterFile("amp.status.proto", fileDescriptor_187b1a6ae9aece88) }

var fileDescriptor_187b1a6ae9aece88 = []byte{
	// 843 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x95, 0x4b, 0x6f, 0x1b, 0x55,
	0x14, 0xc7, 0x3d, 0x21, 0x4d, 0x9a, 0x0b, 0x0d, 0x97, 0x69, 0x4b, 0x4d, 0x81, 0x21, 0xaa, 0x50,
	0xa9, 0xba, 0xc8, 0x02, 0x3e, 0x41, 0xec, 0x38, 0x10, 0x39, 0x71, 0x22, 0x3b, 0x09, 0x4b, 0x74,
	0xf1, 0x3d, 0x1e, 0x5f, 0x69, 0xe6, 0xde, 0xe9, 0xbd, 0x67, 0x8a, 0x87, 0x55, 0x97, 0x08, 0xf1,
	0x28, 0x8f, 0x0d, 0xef, 0xf7, 0x43, 0x7c, 0x02, 0x40, 0xbc, 0x61, 0x81, 0x64, 0x16, 0x59, 0x76,
	0x49, 0x9c, 0x0d, 0xcb, 0x6e, 0x60, 0x83, 0xda, 0xa0, 0x71, 0xc6, 0x73, 0x7d, 0xa9, 0x37, 0xf6,
	0x9c, 0xdf, 0xf9, 0x9f, 0xb7, 0xc6, 0x84, 0xb2, 0x38, 0x59, 0x36, 0xc8, 0x30, 0x35, 0xcb, 0x89,
	0x56, 0xa8, 0xfc, 0xb9, 0xe3, 0xa7, 0x0b, 0x57, 0xc8, 0x89, 0x86, 0xd6, 0x4a, 0xfb, 0x17, 0xc9,
	0x6c, 0x5d, 0x71, 0xa8, 0x7a, 0x4b, 0xde, 0xa5, 0xc5, 0xc7, 0xfd, 0x89, 0x77, 0x67, 0xfc, 0x95,
	0x93, 0xf6, 0x98, 0xfb, 0x17, 0xc9, 0x89, 0x0d, 0xb8, 0x0a, 0x51, 0x75, 0x66, 0xec, 0x48, 0x27,
	0x8e, 0x1b, 0x2a, 0x1c, 0xdb, 0xdb, 0xc7, 0xd8, 0xaf, 0x92, 0xf9, 0x4d, 0x30, 0x86, 0x85, 0x50,
	0x9d, 0x5d, 0xf2, 0x2e, 0x2d, 0xb4, 0x27, 0x8f, 0x97, 0x6f, 0x2d, 0x10, 0x62, 0xc3, 0xfa, 0xf3,
	0xe4, 0xae, 0x96, 0x88, 0x68, 0xc5, 0x3f, 0x43, 0xe6, 0x77, 0xa5, 0x64, 0x31, 0x70, 0xfa, 0xc5,
	0x1f, 0xb7, 0x8f, 0xc6, 0x1f, 0xcf, 0x7f, 0x80, 0xdc, 0xb3, 0x62, 0x0c, 0x68, 0x5c, 0x63, 0x22,
	0x02, 0x4e, 0x3f, 0xb7, 0xe8, 0x3c, 0x39, 0xb5, 0x2b, 0x4d, 0x9a, 0x24, 0x4a, 0x23, 0xf0, 0xad,
	0x84, 0x7e, 0xf6, 0x3f, 0x26, 0xe2, 0x24, 0x82, 0x18, 0x24, 0x02, 0xa7, 0x9f, 0x5a, 0x76, 0x86,
	0xcc, 0xef, 0x88, 0x18, 0x54, 0x8a, 0xf4, 0x13, 0x27, 0x51, 0xa7, 0x9f, 0x22, 0x0a, 0x19, 0xae,
	0xaa, 0xe7, 0x24, 0xfd, 0xd8, 0x41, 0x2d, 0x85, 0x75, 0x25, 0x25, 0x74, 0xf3, 0x58, 0x1f, 0x59,
	0x74, 0x8e, 0x90, 0x95, 0x14, 0xfb, 0x45, 0x71, 0x1f, 0x5a, 0x50, 0x25, 0x77, 0x6f, 0xa8, 0x50,
	0xc8, 0x82, 0x7c, 0xe0, 0xa4, 0x6f, 0x0c, 0x12, 0xa1, 0x81, 0xd3, 0xf7, 0xad, 0xf5, 0x2c, 0x39,
	0xd9, 0x52, 0xd8, 0x06, 0xc6, 0x33, 0xfa, 0x9e, 0x35, 0xdf, 0x4f, 0x16, 0xea, 0x4c, 0x76, 0x21,
	0xca, 0x83, 0xbc, 0xeb, 0x94, 0xb4, 0x8e, 0x10, 0xb7, 0x14, 0xae, 0xa9, 0x54, 0x72, 0xfa, 0x8e,
	0x93, 0x79, 0x9b, 0x69, 0x03, 0x45, 0xe6, 0xb7, 0x9d, 0xa1, 0x74, 0x90, 0x69, 0x4c, 0x93, 0x82,
	0xbd, 0x65, 0xd9, 0x43, 0xe4, 0xde, 0xba, 0x92, 0x08, 0x03, 0x2c, 0xcb, 0x78, 0xd3, 0x51, 0xb6,
	0xe1, 0x4a, 0x0a, 0x06, 0xeb, 0x91, 0x32, 0xc0, 0xe9, 0x1b, 0xce, 0x08, 0x6a, 0x8c, 0x17, 0x98,
	0xbe, 0x6e, 0xc1, 0x69, 0x32, 0x57, 0x63, 0x7c, 0x87, 0x85, 0xf4, 0x35, 0xa7, 0xcf, 0x1a, 0xe3,
	0x7b, 0x2c, 0x4a, 0x81, 0x5e, 0x77, 0x12, 0xac, 0x44, 0x3a, 0x4f, 0xdb, 0x18, 0x08, 0x83, 0x86,
	0xbe, 0xea, 0x9e, 0x00, 0xa2, 0x2e, 0x7b, 0x7d, 0xc5, 0xa9, 0xba, 0xa5, 0xb0, 0x2f, 0x64, 0xb8,
	0xa3, 0xea, 0x2a, 0x8e, 0x05, 0xd2, 0x97, 0x1d, 0xe1, 0xb1, 0xb1, 0x68, 0xf7, 0x25, 0x8b, 0x1e,
	0x24, 0x8b, 0x1d, 0x54, 0x9a, 0x85, 0xe3, 0x31, 0xa5, 0x1a, 0xe8, 0x8b, 0xce, 0x04, 0x37, 0x59,
	0xd4, 0x53, 0x3a, 0x06, 0xbe, 0x33, 0xa0, 0x2f, 0x38, 0xeb, 0xa8, 0x31, 0xde, 0xe9, 0xf6, 0x21,
	0x66, 0xf4, 0x9a, 0xa3, 0x58, 0x65, 0xc8, 0x26, 0xb1, 0x8e, 0x86, 0xd3, 0x8a, 0xc6, 0x20, 0xbf,
	0xd0, 0x86, 0xd6, 0xf4, 0xb6, 0x63, 0xdf, 0x2e, 0xaf, 0xe3, 0xd6, 0xd0, 0xd9, 0x9e, 0x56, 0x57,
	0x05, 0x07, 0x9d, 0x2b, 0xfe, 0xb5, 0xe4, 0x11, 0xe2, 0xef, 0x09, 0x15, 0x31, 0x04, 0xb3, 0x92,
	0x24, 0x20, 0xf9, 0x96, 0x8c, 0x32, 0xfa, 0x8f, 0x75, 0x78, 0x94, 0x9c, 0x5b, 0x97, 0x26, 0xed,
	0xf5, 0x44, 0x57, 0x80, 0xc4, 0x6d, 0xd0, 0xb1, 0x30, 0x46, 0x28, 0x69, 0xe8, 0xdf, 0xd6, 0xeb,
	0x31, 0x72, 0xbe, 0xae, 0xb3, 0x04, 0x55, 0x53, 0x60, 0x31, 0xf2, 0x36, 0x84, 0xc2, 0x20, 0xe4,
	0x17, 0xf9, 0x9b, 0x75, 0xbc, 0x40, 0xce, 0xee, 0x4a, 0x0d, 0x5d, 0x15, 0x4a, 0xf1, 0x3c, 0xf0,
	0x52, 0x44, 0x7f, 0x1d, 0x4e, 0xaf, 0x6d, 0x15, 0xba, 0x39, 0x29, 0x3a, 0xf9, 0xc5, 0xd1, 0xef,
	0x81, 0x16, 0xbd, 0xac, 0x23, 0x42, 0xc9, 0x30, 0xd5, 0x93, 0x8b, 0xfc, 0x79, 0x38, 0xbd, 0xa1,
	0x1a, 0xe3, 0x4d, 0xc8, 0xd6, 0x94, 0x8e, 0x19, 0xd2, 0x9f, 0x2c, 0x5a, 0x22, 0xa7, 0x9b, 0x90,
	0x3d, 0x09, 0x12, 0x34, 0x43, 0xa1, 0x26, 0xa3, 0xfa, 0x71, 0x38, 0xbd, 0xfc, 0x26, 0x64, 0x5a,
	0xc8, 0xb0, 0x3c, 0x8d, 0x1f, 0x2c, 0x7d, 0x98, 0xd0, 0x26, 0x64, 0x0d, 0x89, 0x3a, 0x2b, 0xf1,
	0xf7, 0x8e, 0xf8, 0x29, 0x66, 0xfa, 0x4d, 0x81, 0x25, 0xfd, 0xce, 0x49, 0x7e, 0x47, 0xef, 0x5b,
	0x09, 0xfd, 0xd6, 0xe9, 0x7c, 0x93, 0x69, 0xd3, 0x67, 0x51, 0x51, 0xd8, 0x37, 0x4e, 0xec, 0x5d,
	0x19, 0x3b, 0xf4, 0xeb, 0x92, 0x5e, 0x5e, 0x25, 0x27, 0x27, 0x2f, 0x4b, 0xdf, 0x27, 0x8b, 0x93,
	0xdf, 0xcf, 0x8c, 0xdf, 0xc3, 0xb4, 0xe2, 0xdf, 0x47, 0x4e, 0x95, 0xb6, 0xa7, 0x99, 0x96, 0x74,
	0xc6, 0x31, 0xad, 0xcb, 0x9e, 0xa2, 0xb3, 0xb5, 0xf5, 0xfd, 0x83, 0xa0, 0x72, 0xe3, 0x20, 0xa8,
	0xdc, 0x3c, 0x08, 0xbc, 0x6b, 0xa3, 0xc0, 0xfb, 0x72, 0x14, 0x78, 0xbf, 0x8f, 0x02, 0x6f, 0x7f,
	0x14, 0x78, 0x7f, 0x8e, 0x02, 0xef, 0xaf, 0x51, 0x50, 0xb9, 0x39, 0x0a, 0xbc, 0xeb, 0x87, 0x41,
	0x65, 0xff, 0x30, 0xa8, 0xdc, 0x38, 0x0c, 0x2a, 0x5f, 0xcd, 0xf8, 0x4c, 0xe3, 0x72, 0x0c, 0x5c,
	0xb0, 0xe5, 0x24, 0x62, 0x98, 0xdf, 0xf8, 0xb3, 0x73, 0xe3, 0xbf, 0x84, 0x27, 0xfe, 0x0b, 0x00,
	0x00, 0xff, 0xff, 0x86, 0xdc, 0xfb, 0x65, 0x26, 0x06, 0x00, 0x00,
}

func (x StatusCode) String() string {
	s, ok := StatusCode_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (x LogLevel) String() string {
	s, ok := LogLevel_name[int32(x)]
	if ok {
		return s
	}
	return strconv.Itoa(int(x))
}
func (this *Error) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Error)
	if !ok {
		that2, ok := that.(Error)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Code != that1.Code {
		return false
	}
	if this.Level != that1.Level {
		return false
	}
	if this.Message != that1.Message {
		return false
	}
	return true
}
func (this *Error) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&status.Error{")
	s = append(s, "Code: "+fmt.Sprintf("%#v", this.Code)+",\n")
	s = append(s, "Level: "+fmt.Sprintf("%#v", this.Level)+",\n")
	s = append(s, "Message: "+fmt.Sprintf("%#v", this.Message)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringAmpStatus(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *Error) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Error) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Error) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintAmpStatus(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x22
	}
	if m.Level != 0 {
		i = encodeVarintAmpStatus(dAtA, i, uint64(m.Level))
		i--
		dAtA[i] = 0x10
	}
	if m.Code != 0 {
		i = encodeVarintAmpStatus(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAmpStatus(dAtA []byte, offset int, v uint64) int {
	offset -= sovAmpStatus(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Error) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Code != 0 {
		n += 1 + sovAmpStatus(uint64(m.Code))
	}
	if m.Level != 0 {
		n += 1 + sovAmpStatus(uint64(m.Level))
	}
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovAmpStatus(uint64(l))
	}
	return n
}

func sovAmpStatus(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAmpStatus(x uint64) (n int) {
	return sovAmpStatus(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Error) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Error{`,
		`Code:` + fmt.Sprintf("%v", this.Code) + `,`,
		`Level:` + fmt.Sprintf("%v", this.Level) + `,`,
		`Message:` + fmt.Sprintf("%v", this.Message) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringAmpStatus(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Error) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAmpStatus
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Error: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Error: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Code", wireType)
			}
			m.Code = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmpStatus
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Code |= StatusCode(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Level", wireType)
			}
			m.Level = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmpStatus
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Level |= LogLevel(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAmpStatus
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAmpStatus
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAmpStatus
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAmpStatus(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAmpStatus
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAmpStatus(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAmpStatus
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAmpStatus
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAmpStatus
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAmpStatus
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAmpStatus
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAmpStatus
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAmpStatus        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAmpStatus          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAmpStatus = fmt.Errorf("proto: unexpected end of group")
)
