// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: amp/crates/amp.crates.proto

// Contains data structures used by the client for content management and deployment

package crates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AssetFlags int32

const (
	AssetFlags_NoFlags         AssetFlags = 0
	AssetFlags_IsTexture       AssetFlags = 1  // asset is a Texture
	AssetFlags_IsSprite        AssetFlags = 2  // asset is a Sprite
	AssetFlags_IsMaterial      AssetFlags = 4  // asset is a Material
	AssetFlags_IsPlaceable     AssetFlags = 8  // asset can be placed in a space
	AssetFlags_IsRectTransform AssetFlags = 16 // has a RectTransform component.
	AssetFlags_IsScene         AssetFlags = 32 // has a Scene component.
	// HasIcon means that this Asset includes an icon with the same name (and has IsIcon set),
	AssetFlags_HasIcon AssetFlags = 256
	// IsPrivate means this item is not intended for general use and is not normally visible.
	AssetFlags_IsPrivate AssetFlags = 512
	// IsSkybox means this is a transform containing a Skybox component.
	AssetFlags_IsSkybox AssetFlags = 1024
	// AutoScale means this asset should be placed with auto scale enabled by default.
	AssetFlags_AutoScale AssetFlags = 2048
	// IsSurface means this asset behaves like terrain and/or should be considered a constituent part of a scene.
	// These objects should be opaque and have colliders attached to them
	// e.g.  a building, a terrain formation, a wall
	AssetFlags_IsSurface AssetFlags = 4096
	// IsVisualLayer denotes the asset contains a VisualLayer component.
	AssetFlags_IsVisualLayer AssetFlags = 8192
	// IsVisualScope denotes the asset contains a VisualScope component
	AssetFlags_IsVisualScope AssetFlags = 16384
)

// Enum value maps for AssetFlags.
var (
	AssetFlags_name = map[int32]string{
		0:     "NoFlags",
		1:     "IsTexture",
		2:     "IsSprite",
		4:     "IsMaterial",
		8:     "IsPlaceable",
		16:    "IsRectTransform",
		32:    "IsScene",
		256:   "HasIcon",
		512:   "IsPrivate",
		1024:  "IsSkybox",
		2048:  "AutoScale",
		4096:  "IsSurface",
		8192:  "IsVisualLayer",
		16384: "IsVisualScope",
	}
	AssetFlags_value = map[string]int32{
		"NoFlags":         0,
		"IsTexture":       1,
		"IsSprite":        2,
		"IsMaterial":      4,
		"IsPlaceable":     8,
		"IsRectTransform": 16,
		"IsScene":         32,
		"HasIcon":         256,
		"IsPrivate":       512,
		"IsSkybox":        1024,
		"AutoScale":       2048,
		"IsSurface":       4096,
		"IsVisualLayer":   8192,
		"IsVisualScope":   16384,
	}
)

func (x AssetFlags) Enum() *AssetFlags {
	p := new(AssetFlags)
	*p = x
	return p
}

func (x AssetFlags) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetFlags) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_crates_amp_crates_proto_enumTypes[0].Descriptor()
}

func (AssetFlags) Type() protoreflect.EnumType {
	return &file_amp_crates_amp_crates_proto_enumTypes[0]
}

func (x AssetFlags) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetFlags.Descriptor instead.
func (AssetFlags) EnumDescriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{0}
}

// Enum values should be three base-10 digits corresponding to the major, minor, and revision number.
type CrateSchema int32

const (
	CrateSchema_UndefinedSchema CrateSchema = 0
	// v100 (April 2020) should be used for CrateInfo.CrateSchema
	CrateSchema_v100 CrateSchema = 100
)

// Enum value maps for CrateSchema.
var (
	CrateSchema_name = map[int32]string{
		0:   "UndefinedSchema",
		100: "v100",
	}
	CrateSchema_value = map[string]int32{
		"UndefinedSchema": 0,
		"v100":            100,
	}
)

func (x CrateSchema) Enum() *CrateSchema {
	p := new(CrateSchema)
	*p = x
	return p
}

func (x CrateSchema) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrateSchema) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_crates_amp_crates_proto_enumTypes[1].Descriptor()
}

func (CrateSchema) Type() protoreflect.EnumType {
	return &file_amp_crates_amp_crates_proto_enumTypes[1]
}

func (x CrateSchema) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrateSchema.Descriptor instead.
func (CrateSchema) EnumDescriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{1}
}

type AssetEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AssetFlags specifies properties about this AssetEntry.
	Flags AssetFlags `protobuf:"varint,1,opt,name=Flags,proto3,enum=crates.AssetFlags" json:"Flags,omitempty"`
	// EntryURI is a Unix-style pathname that identifies an asset within a crate.
	// By convention, this URI does *not* start or end with '/'
	// An asset URI has the form "{CrateURI}/{EntryURI}"
	// If two or more assets have the same EntryURI, then only one is accessible.
	EntryURI string `protobuf:"bytes,2,opt,name=EntryURI,proto3" json:"EntryURI,omitempty"`
	// Label is the human-readable label for this asset.
	Label string `protobuf:"bytes,3,opt,name=Label,proto3" json:"Label,omitempty"`
	// AssetID is an alternative name for this asset that is used to identify the asset in code.
	// DEPRECATED -- EntryURI should be used instead of AssetID (or use [2]uint64 that Unity returns)
	AssetID string `protobuf:"bytes,4,opt,name=AssetID,proto3" json:"AssetID,omitempty"`
	// CenterX and CenterZ specify the positional center of this asset (and are typically 0).
	// CenterY is the distance above the baseline (y=0) to the y center-point height of this asset.
	// Y is considered to be the *vertical* (up) direction and by convention rests on the plane y=0.
	CenterX float32 `protobuf:"fixed32,5,opt,name=CenterX,proto3" json:"CenterX,omitempty"`
	CenterY float32 `protobuf:"fixed32,6,opt,name=CenterY,proto3" json:"CenterY,omitempty"`
	CenterZ float32 `protobuf:"fixed32,7,opt,name=CenterZ,proto3" json:"CenterZ,omitempty"`
	// Extents specify the distance from the center to the extent of the asset on each axis.
	ExtentsX float32 `protobuf:"fixed32,10,opt,name=ExtentsX,proto3" json:"ExtentsX,omitempty"`
	ExtentsY float32 `protobuf:"fixed32,11,opt,name=ExtentsY,proto3" json:"ExtentsY,omitempty"`
	ExtentsZ float32 `protobuf:"fixed32,12,opt,name=ExtentsZ,proto3" json:"ExtentsZ,omitempty"`
	// Reserved for runtime use -- defaults to empty.
	LocalURI string `protobuf:"bytes,30,opt,name=LocalURI,proto3" json:"LocalURI,omitempty"`
	// Comma-delimited and whitespace-trimmed list of tags.
	Tags string `protobuf:"bytes,31,opt,name=Tags,proto3" json:"Tags,omitempty"`
	// A short phrase or fragment describing this asset, starting with an article where appropriate. e.g.:
	//
	//	"A typical 6 crew member fire truck"
	//	"A leading U.S. naval ship-based helicopter"
	//	"The Texas capitol building located in Austin"
	//	"An animated scared-geometry inspired flat seal"
	ShortDesc     string `protobuf:"bytes,32,opt,name=ShortDesc,proto3" json:"ShortDesc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetEntry) Reset() {
	*x = AssetEntry{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetEntry) ProtoMessage() {}

func (x *AssetEntry) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetEntry.ProtoReflect.Descriptor instead.
func (*AssetEntry) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{0}
}

func (x *AssetEntry) GetFlags() AssetFlags {
	if x != nil {
		return x.Flags
	}
	return AssetFlags_NoFlags
}

func (x *AssetEntry) GetEntryURI() string {
	if x != nil {
		return x.EntryURI
	}
	return ""
}

func (x *AssetEntry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AssetEntry) GetAssetID() string {
	if x != nil {
		return x.AssetID
	}
	return ""
}

func (x *AssetEntry) GetCenterX() float32 {
	if x != nil {
		return x.CenterX
	}
	return 0
}

func (x *AssetEntry) GetCenterY() float32 {
	if x != nil {
		return x.CenterY
	}
	return 0
}

func (x *AssetEntry) GetCenterZ() float32 {
	if x != nil {
		return x.CenterZ
	}
	return 0
}

func (x *AssetEntry) GetExtentsX() float32 {
	if x != nil {
		return x.ExtentsX
	}
	return 0
}

func (x *AssetEntry) GetExtentsY() float32 {
	if x != nil {
		return x.ExtentsY
	}
	return 0
}

func (x *AssetEntry) GetExtentsZ() float32 {
	if x != nil {
		return x.ExtentsZ
	}
	return 0
}

func (x *AssetEntry) GetLocalURI() string {
	if x != nil {
		return x.LocalURI
	}
	return ""
}

func (x *AssetEntry) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *AssetEntry) GetShortDesc() string {
	if x != nil {
		return x.ShortDesc
	}
	return ""
}

type BundleManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BundleTitle is how the outside world sees this bundle and has no other impact.
	// This means it can change from build to build and contain any Unicode characters.
	BundleTitle string `protobuf:"bytes,2,opt,name=BundleTitle,proto3" json:"BundleTitle,omitempty"`
	// BundleNameID is how this bundle is internally identified and expressed as the filename of this bundle.
	// This is case sensitive, contains only path-safe characters (sans /:\<>|?*\"), and does not terminate in '.' or whitespace.
	BundleNameID  string        `protobuf:"bytes,3,opt,name=BundleNameID,proto3" json:"BundleNameID,omitempty"`
	Assets        []*AssetEntry `protobuf:"bytes,10,rep,name=Assets,proto3" json:"Assets,omitempty"`
	LoadAllHint   bool          `protobuf:"varint,20,opt,name=LoadAllHint,proto3" json:"LoadAllHint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleManifest) Reset() {
	*x = BundleManifest{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleManifest) ProtoMessage() {}

func (x *BundleManifest) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleManifest.ProtoReflect.Descriptor instead.
func (*BundleManifest) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{1}
}

func (x *BundleManifest) GetBundleTitle() string {
	if x != nil {
		return x.BundleTitle
	}
	return ""
}

func (x *BundleManifest) GetBundleNameID() string {
	if x != nil {
		return x.BundleNameID
	}
	return ""
}

func (x *BundleManifest) GetAssets() []*AssetEntry {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *BundleManifest) GetLoadAllHint() bool {
	if x != nil {
		return x.LoadAllHint
	}
	return false
}

// CrateInfo represents a Crate, the fundamental unit of amp's asset/package manager.
type CrateInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CrateSchema communicates which build and packaging schema was used for this crate build.
	// This value should be the integer value of a valid CrateSchema.vNNN enum.
	CrateSchema int32 `protobuf:"varint,1,opt,name=CrateSchema,proto3" json:"CrateSchema,omitempty"`
	// InstID is 0 by default and reserved for a runtime manager to reference a crate via issuing integers.
	// If non-zero, it will not change and no other instance will have the same value.
	InstID uint32 `protobuf:"varint,2,opt,name=InstID,proto3" json:"InstID,omitempty"`
	// CrateURI takes the form "{PublisherID}/{CrateID}" and is used to globally reference assets in this crate.
	// This URI string can only contain chars in [A-Za-z0-9_.-] (other than the separating '/' char).
	// PublisherID uniquely identifies the author/owner/publisher of this crate (and potentially other crates).
	// CrateID uniquely identifies this crate for the given publisher and all subsequent revisions.
	//
	//	"plan-systems.org/plan.app.ui"
	//	"plan-systems.org/about-plan-systems"
	//	"themushroom.farm/land"
	//	"themushroom.farm/mycology-201"
	//	"the-smiths.family/123-Maple"
	CrateURI string `protobuf:"bytes,4,opt,name=CrateURI,proto3" json:"CrateURI,omitempty"`
	// PublisherName is a human-readable name of the author/owner/publisher of this crate and can change without repercussions (i.e. is purely optical).
	PublisherName string `protobuf:"bytes,6,opt,name=PublisherName,proto3" json:"PublisherName,omitempty"`
	// CrateName is a human-readable title for this crate and can change without repercussions.
	CrateName string `protobuf:"bytes,10,opt,name=CrateName,proto3" json:"CrateName,omitempty"`
	// ShortDesc describes this crate in a brief phrase.
	ShortDesc string `protobuf:"bytes,11,opt,name=ShortDesc,proto3" json:"ShortDesc,omitempty"`
	// Comma-delimited and whitespace-trimmed list of tags.
	Tags string `protobuf:"bytes,15,opt,name=Tags,proto3" json:"Tags,omitempty"`
	// TimeCreated is the UTC value (in seconds) when this crate was first created (and does not change).
	TimeCreated int64 `protobuf:"varint,30,opt,name=TimeCreated,proto3" json:"TimeCreated,omitempty"`
	// TimeBuilt is the UTC value (in seconds) when this crate was built.
	TimeBuilt int64 `protobuf:"varint,31,opt,name=TimeBuilt,proto3" json:"TimeBuilt,omitempty"`
	// VersionID uniquely identifies this build and has the form "v{MajorNum}.{MinorNum}.{BuildNum}"
	// e.g. "v1.11.201"
	MajorVersion int32 `protobuf:"varint,40,opt,name=MajorVersion,proto3" json:"MajorVersion,omitempty"`
	MinorVersion int32 `protobuf:"varint,41,opt,name=MinorVersion,proto3" json:"MinorVersion,omitempty"`
	BuildNumber  int32 `protobuf:"varint,42,opt,name=BuildNumber,proto3" json:"BuildNumber,omitempty"`
	// BuildID uniquely identifies a particular crate build/version.
	// This value should have no spaces and only have '.', '_', or '-' (and starts and ends with an alphanumeric character).
	// By convention, the format is "yyMMdd-{VersionID}" (so that sorting by BuildID string yields the most recent release).
	// e.g. "210320-v0.1.11"
	BuildID string `protobuf:"bytes,45,opt,name=BuildID,proto3" json:"BuildID,omitempty"`
	// HomeURL is an optional link that allows a human to learn more about this crate.
	HomeURL string `protobuf:"bytes,50,opt,name=HomeURL,proto3" json:"HomeURL,omitempty"`
	// URL is an optional string available to specify a URL to download this crate.
	URL string `protobuf:"bytes,55,opt,name=URL,proto3" json:"URL,omitempty"`
	// Approximate size of this crate in bytes (or 0 if unknown).
	ApproxSize    int64 `protobuf:"varint,60,opt,name=ApproxSize,proto3" json:"ApproxSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrateInfo) Reset() {
	*x = CrateInfo{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrateInfo) ProtoMessage() {}

func (x *CrateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrateInfo.ProtoReflect.Descriptor instead.
func (*CrateInfo) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{2}
}

func (x *CrateInfo) GetCrateSchema() int32 {
	if x != nil {
		return x.CrateSchema
	}
	return 0
}

func (x *CrateInfo) GetInstID() uint32 {
	if x != nil {
		return x.InstID
	}
	return 0
}

func (x *CrateInfo) GetCrateURI() string {
	if x != nil {
		return x.CrateURI
	}
	return ""
}

func (x *CrateInfo) GetPublisherName() string {
	if x != nil {
		return x.PublisherName
	}
	return ""
}

func (x *CrateInfo) GetCrateName() string {
	if x != nil {
		return x.CrateName
	}
	return ""
}

func (x *CrateInfo) GetShortDesc() string {
	if x != nil {
		return x.ShortDesc
	}
	return ""
}

func (x *CrateInfo) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *CrateInfo) GetTimeCreated() int64 {
	if x != nil {
		return x.TimeCreated
	}
	return 0
}

func (x *CrateInfo) GetTimeBuilt() int64 {
	if x != nil {
		return x.TimeBuilt
	}
	return 0
}

func (x *CrateInfo) GetMajorVersion() int32 {
	if x != nil {
		return x.MajorVersion
	}
	return 0
}

func (x *CrateInfo) GetMinorVersion() int32 {
	if x != nil {
		return x.MinorVersion
	}
	return 0
}

func (x *CrateInfo) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

func (x *CrateInfo) GetBuildID() string {
	if x != nil {
		return x.BuildID
	}
	return ""
}

func (x *CrateInfo) GetHomeURL() string {
	if x != nil {
		return x.HomeURL
	}
	return ""
}

func (x *CrateInfo) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *CrateInfo) GetApproxSize() int64 {
	if x != nil {
		return x.ApproxSize
	}
	return 0
}

// CrateManifest is the top-level manifest/catalog for a amp asset module called a "crate".
// It contains catalog and type info that amp loads at runtime to know what's inside binary asset bundles without having to load them.
//
// A reference to a amp asset is via a URI with the form:
//
//	assetURI := "PublisherID/CrateID[@CrateBuildID]/{AssetEntry.Pathname}"
type CrateManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Info  *CrateInfo             `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	// IconBundleName is the bundle name ID of the bundle containing icons (Sprites) used to represent the "real" crate assets.
	// Asset name IDs in this bundle correspond to assets in all the other Crate's bundles.
	IconBundleName string            `protobuf:"bytes,5,opt,name=IconBundleName,proto3" json:"IconBundleName,omitempty"`
	Bundles        []*BundleManifest `protobuf:"bytes,10,rep,name=Bundles,proto3" json:"Bundles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CrateManifest) Reset() {
	*x = CrateManifest{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrateManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrateManifest) ProtoMessage() {}

func (x *CrateManifest) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrateManifest.ProtoReflect.Descriptor instead.
func (*CrateManifest) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{3}
}

func (x *CrateManifest) GetInfo() *CrateInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *CrateManifest) GetIconBundleName() string {
	if x != nil {
		return x.IconBundleName
	}
	return ""
}

func (x *CrateManifest) GetBundles() []*BundleManifest {
	if x != nil {
		return x.Bundles
	}
	return nil
}

// CrateSnapshot is a general purpose container to track multiple crates and associated build IDs.
type CrateSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RevID int64                  `protobuf:"varint,1,opt,name=RevID,proto3" json:"RevID,omitempty"`
	// This is a template URL where the symbols "CrateURI", "CrateBuildID", "PlatformID" are delimited with { }.
	// The symbol "{.}" is to be replaced with a local pathname if the URL refers to a local file system pathname.
	// e.g. "https://whatever.com/{CrateURI}__{CrateBuildID}.{PlatformID}.crate"
	//
	//	"{.}/{CrateURI}__{CrateBuildID}.{PlatformID}.crate"
	DownloadURL   string       `protobuf:"bytes,3,opt,name=DownloadURL,proto3" json:"DownloadURL,omitempty"`
	Crates        []*CrateInfo `protobuf:"bytes,10,rep,name=Crates,proto3" json:"Crates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrateSnapshot) Reset() {
	*x = CrateSnapshot{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrateSnapshot) ProtoMessage() {}

func (x *CrateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrateSnapshot.ProtoReflect.Descriptor instead.
func (*CrateSnapshot) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{4}
}

func (x *CrateSnapshot) GetRevID() int64 {
	if x != nil {
		return x.RevID
	}
	return 0
}

func (x *CrateSnapshot) GetDownloadURL() string {
	if x != nil {
		return x.DownloadURL
	}
	return ""
}

func (x *CrateSnapshot) GetCrates() []*CrateInfo {
	if x != nil {
		return x.Crates
	}
	return nil
}

// AppVars help the amp runtime manage dynamic Go or Clib module loading
// This can be thought of a data record for a registered app in the art-media-platform ecosystem.
type AppVars struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// AppDomain is the domain name used for primary queries (e.g. "plan-systems.org")
	AppDomain string `protobuf:"bytes,2,opt,name=AppDomain,proto3" json:"AppDomain,omitempty"`
	// AppDesc is a short human readable description of AppDomain
	AppDesc string `protobuf:"bytes,4,opt,name=AppDesc,proto3" json:"AppDesc,omitempty"`
	// OrgHomeURL is the home link for this org (e.g. "https://plan-systems.org")
	OrgHomeURL string `protobuf:"bytes,6,opt,name=OrgHomeURL,proto3" json:"OrgHomeURL,omitempty"`
	// AppHomeURL points to the home URL for the app
	AppHomeURL string `protobuf:"bytes,12,opt,name=AppHomeURL,proto3" json:"AppHomeURL,omitempty"`
	// CrateSnapshotURL specifies where to load this org's CrateSnapshot
	CrateSnapshotURL string `protobuf:"bytes,14,opt,name=CrateSnapshotURL,proto3" json:"CrateSnapshotURL,omitempty"`
	// AppDownloadURLs are a download URL for a given platform.
	// A key of "" denotes an unknown platform
	AppDownloadURLs map[string]string `protobuf:"bytes,16,rep,name=AppDownloadURLs,proto3" json:"AppDownloadURLs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// URLSchemes declare URL prefixes used to check if in incoming URL from the OS should be handled.
	// The first entry is the primary scheme and the rest are alternately recognized schemes.
	//
	// If an URL is matched, it is replaced by "amp://" and then passed to the amp runtime.
	URLSchemes []string `protobuf:"bytes,18,rep,name=URLSchemes,proto3" json:"URLSchemes,omitempty"`
	// Overrides default settings
	Settings map[string]string `protobuf:"bytes,20,rep,name=Settings,proto3" json:"Settings,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Links is a list of channel URIs for easy access.
	Links         []*KVEntry `protobuf:"bytes,40,rep,name=Links,proto3" json:"Links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppVars) Reset() {
	*x = AppVars{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppVars) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppVars) ProtoMessage() {}

func (x *AppVars) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppVars.ProtoReflect.Descriptor instead.
func (*AppVars) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{5}
}

func (x *AppVars) GetAppDomain() string {
	if x != nil {
		return x.AppDomain
	}
	return ""
}

func (x *AppVars) GetAppDesc() string {
	if x != nil {
		return x.AppDesc
	}
	return ""
}

func (x *AppVars) GetOrgHomeURL() string {
	if x != nil {
		return x.OrgHomeURL
	}
	return ""
}

func (x *AppVars) GetAppHomeURL() string {
	if x != nil {
		return x.AppHomeURL
	}
	return ""
}

func (x *AppVars) GetCrateSnapshotURL() string {
	if x != nil {
		return x.CrateSnapshotURL
	}
	return ""
}

func (x *AppVars) GetAppDownloadURLs() map[string]string {
	if x != nil {
		return x.AppDownloadURLs
	}
	return nil
}

func (x *AppVars) GetURLSchemes() []string {
	if x != nil {
		return x.URLSchemes
	}
	return nil
}

func (x *AppVars) GetSettings() map[string]string {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *AppVars) GetLinks() []*KVEntry {
	if x != nil {
		return x.Links
	}
	return nil
}

// KVEntry is a generic entry for any key-value pair.
type KVEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVEntry) Reset() {
	*x = KVEntry{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVEntry) ProtoMessage() {}

func (x *KVEntry) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVEntry.ProtoReflect.Descriptor instead.
func (*KVEntry) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{6}
}

func (x *KVEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_amp_crates_amp_crates_proto protoreflect.FileDescriptor

const file_amp_crates_amp_crates_proto_rawDesc = "" +
	"\n" +
	"\x1bamp/crates/amp.crates.proto\x12\x06crates\"\xf2\x02\n" +
	"\n" +
	"AssetEntry\x12(\n" +
	"\x05Flags\x18\x01 \x01(\x0e2\x12.crates.AssetFlagsR\x05Flags\x12\x1a\n" +
	"\bEntryURI\x18\x02 \x01(\tR\bEntryURI\x12\x14\n" +
	"\x05Label\x18\x03 \x01(\tR\x05Label\x12\x18\n" +
	"\aAssetID\x18\x04 \x01(\tR\aAssetID\x12\x18\n" +
	"\aCenterX\x18\x05 \x01(\x02R\aCenterX\x12\x18\n" +
	"\aCenterY\x18\x06 \x01(\x02R\aCenterY\x12\x18\n" +
	"\aCenterZ\x18\a \x01(\x02R\aCenterZ\x12\x1a\n" +
	"\bExtentsX\x18\n" +
	" \x01(\x02R\bExtentsX\x12\x1a\n" +
	"\bExtentsY\x18\v \x01(\x02R\bExtentsY\x12\x1a\n" +
	"\bExtentsZ\x18\f \x01(\x02R\bExtentsZ\x12\x1a\n" +
	"\bLocalURI\x18\x1e \x01(\tR\bLocalURI\x12\x12\n" +
	"\x04Tags\x18\x1f \x01(\tR\x04Tags\x12\x1c\n" +
	"\tShortDesc\x18  \x01(\tR\tShortDesc\"\xa4\x01\n" +
	"\x0eBundleManifest\x12 \n" +
	"\vBundleTitle\x18\x02 \x01(\tR\vBundleTitle\x12\"\n" +
	"\fBundleNameID\x18\x03 \x01(\tR\fBundleNameID\x12*\n" +
	"\x06Assets\x18\n" +
	" \x03(\v2\x12.crates.AssetEntryR\x06Assets\x12 \n" +
	"\vLoadAllHint\x18\x14 \x01(\bR\vLoadAllHint\"\xe7\x03\n" +
	"\tCrateInfo\x12 \n" +
	"\vCrateSchema\x18\x01 \x01(\x05R\vCrateSchema\x12\x16\n" +
	"\x06InstID\x18\x02 \x01(\rR\x06InstID\x12\x1a\n" +
	"\bCrateURI\x18\x04 \x01(\tR\bCrateURI\x12$\n" +
	"\rPublisherName\x18\x06 \x01(\tR\rPublisherName\x12\x1c\n" +
	"\tCrateName\x18\n" +
	" \x01(\tR\tCrateName\x12\x1c\n" +
	"\tShortDesc\x18\v \x01(\tR\tShortDesc\x12\x12\n" +
	"\x04Tags\x18\x0f \x01(\tR\x04Tags\x12 \n" +
	"\vTimeCreated\x18\x1e \x01(\x03R\vTimeCreated\x12\x1c\n" +
	"\tTimeBuilt\x18\x1f \x01(\x03R\tTimeBuilt\x12\"\n" +
	"\fMajorVersion\x18( \x01(\x05R\fMajorVersion\x12\"\n" +
	"\fMinorVersion\x18) \x01(\x05R\fMinorVersion\x12 \n" +
	"\vBuildNumber\x18* \x01(\x05R\vBuildNumber\x12\x18\n" +
	"\aBuildID\x18- \x01(\tR\aBuildID\x12\x18\n" +
	"\aHomeURL\x182 \x01(\tR\aHomeURL\x12\x10\n" +
	"\x03URL\x187 \x01(\tR\x03URL\x12\x1e\n" +
	"\n" +
	"ApproxSize\x18< \x01(\x03R\n" +
	"ApproxSize\"\x90\x01\n" +
	"\rCrateManifest\x12%\n" +
	"\x04Info\x18\x01 \x01(\v2\x11.crates.CrateInfoR\x04Info\x12&\n" +
	"\x0eIconBundleName\x18\x05 \x01(\tR\x0eIconBundleName\x120\n" +
	"\aBundles\x18\n" +
	" \x03(\v2\x16.crates.BundleManifestR\aBundles\"r\n" +
	"\rCrateSnapshot\x12\x14\n" +
	"\x05RevID\x18\x01 \x01(\x03R\x05RevID\x12 \n" +
	"\vDownloadURL\x18\x03 \x01(\tR\vDownloadURL\x12)\n" +
	"\x06Crates\x18\n" +
	" \x03(\v2\x11.crates.CrateInfoR\x06Crates\"\x80\x04\n" +
	"\aAppVars\x12\x1c\n" +
	"\tAppDomain\x18\x02 \x01(\tR\tAppDomain\x12\x18\n" +
	"\aAppDesc\x18\x04 \x01(\tR\aAppDesc\x12\x1e\n" +
	"\n" +
	"OrgHomeURL\x18\x06 \x01(\tR\n" +
	"OrgHomeURL\x12\x1e\n" +
	"\n" +
	"AppHomeURL\x18\f \x01(\tR\n" +
	"AppHomeURL\x12*\n" +
	"\x10CrateSnapshotURL\x18\x0e \x01(\tR\x10CrateSnapshotURL\x12N\n" +
	"\x0fAppDownloadURLs\x18\x10 \x03(\v2$.crates.AppVars.AppDownloadURLsEntryR\x0fAppDownloadURLs\x12\x1e\n" +
	"\n" +
	"URLSchemes\x18\x12 \x03(\tR\n" +
	"URLSchemes\x129\n" +
	"\bSettings\x18\x14 \x03(\v2\x1d.crates.AppVars.SettingsEntryR\bSettings\x12%\n" +
	"\x05Links\x18( \x03(\v2\x0f.crates.KVEntryR\x05Links\x1aB\n" +
	"\x14AppDownloadURLsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a;\n" +
	"\rSettingsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"1\n" +
	"\aKVEntry\x12\x10\n" +
	"\x03Key\x18\x01 \x01(\tR\x03Key\x12\x14\n" +
	"\x05Value\x18\x02 \x01(\tR\x05Value*\xef\x01\n" +
	"\n" +
	"AssetFlags\x12\v\n" +
	"\aNoFlags\x10\x00\x12\r\n" +
	"\tIsTexture\x10\x01\x12\f\n" +
	"\bIsSprite\x10\x02\x12\x0e\n" +
	"\n" +
	"IsMaterial\x10\x04\x12\x0f\n" +
	"\vIsPlaceable\x10\b\x12\x13\n" +
	"\x0fIsRectTransform\x10\x10\x12\v\n" +
	"\aIsScene\x10 \x12\f\n" +
	"\aHasIcon\x10\x80\x02\x12\x0e\n" +
	"\tIsPrivate\x10\x80\x04\x12\r\n" +
	"\bIsSkybox\x10\x80\b\x12\x0e\n" +
	"\tAutoScale\x10\x80\x10\x12\x0e\n" +
	"\tIsSurface\x10\x80 \x12\x12\n" +
	"\rIsVisualLayer\x10\x80@\x12\x13\n" +
	"\rIsVisualScope\x10\x80\x80\x01*,\n" +
	"\vCrateSchema\x12\x13\n" +
	"\x0fUndefinedSchema\x10\x00\x12\b\n" +
	"\x04v100\x10dBGZ0github.com/art-media-platform/amp.SDK/amp/crates\xaa\x02\x12art.media.platformb\x06proto3"

var (
	file_amp_crates_amp_crates_proto_rawDescOnce sync.Once
	file_amp_crates_amp_crates_proto_rawDescData []byte
)

func file_amp_crates_amp_crates_proto_rawDescGZIP() []byte {
	file_amp_crates_amp_crates_proto_rawDescOnce.Do(func() {
		file_amp_crates_amp_crates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amp_crates_amp_crates_proto_rawDesc), len(file_amp_crates_amp_crates_proto_rawDesc)))
	})
	return file_amp_crates_amp_crates_proto_rawDescData
}

var file_amp_crates_amp_crates_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_amp_crates_amp_crates_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_amp_crates_amp_crates_proto_goTypes = []any{
	(AssetFlags)(0),        // 0: crates.AssetFlags
	(CrateSchema)(0),       // 1: crates.CrateSchema
	(*AssetEntry)(nil),     // 2: crates.AssetEntry
	(*BundleManifest)(nil), // 3: crates.BundleManifest
	(*CrateInfo)(nil),      // 4: crates.CrateInfo
	(*CrateManifest)(nil),  // 5: crates.CrateManifest
	(*CrateSnapshot)(nil),  // 6: crates.CrateSnapshot
	(*AppVars)(nil),        // 7: crates.AppVars
	(*KVEntry)(nil),        // 8: crates.KVEntry
	nil,                    // 9: crates.AppVars.AppDownloadURLsEntry
	nil,                    // 10: crates.AppVars.SettingsEntry
}
var file_amp_crates_amp_crates_proto_depIdxs = []int32{
	0,  // 0: crates.AssetEntry.Flags:type_name -> crates.AssetFlags
	2,  // 1: crates.BundleManifest.Assets:type_name -> crates.AssetEntry
	4,  // 2: crates.CrateManifest.Info:type_name -> crates.CrateInfo
	3,  // 3: crates.CrateManifest.Bundles:type_name -> crates.BundleManifest
	4,  // 4: crates.CrateSnapshot.Crates:type_name -> crates.CrateInfo
	9,  // 5: crates.AppVars.AppDownloadURLs:type_name -> crates.AppVars.AppDownloadURLsEntry
	10, // 6: crates.AppVars.Settings:type_name -> crates.AppVars.SettingsEntry
	8,  // 7: crates.AppVars.Links:type_name -> crates.KVEntry
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_amp_crates_amp_crates_proto_init() }
func file_amp_crates_amp_crates_proto_init() {
	if File_amp_crates_amp_crates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amp_crates_amp_crates_proto_rawDesc), len(file_amp_crates_amp_crates_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amp_crates_amp_crates_proto_goTypes,
		DependencyIndexes: file_amp_crates_amp_crates_proto_depIdxs,
		EnumInfos:         file_amp_crates_amp_crates_proto_enumTypes,
		MessageInfos:      file_amp_crates_amp_crates_proto_msgTypes,
	}.Build()
	File_amp_crates_amp_crates_proto = out.File
	file_amp_crates_amp_crates_proto_goTypes = nil
	file_amp_crates_amp_crates_proto_depIdxs = nil
}
