// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: amp/crates/amp.crates.proto

// Contains data structures used by the client for content management and deployment

package crates

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PlatformID identifies a build target.  Orthogonal to OSVariant (same APK covers
// multiple Android variants, for example).
type PlatformID int32

const (
	PlatformID_UnspecifiedPlatform PlatformID = 0
	PlatformID_macOS               PlatformID = 1
	PlatformID_Windows             PlatformID = 2
	PlatformID_Linux               PlatformID = 3
	PlatformID_Android             PlatformID = 4
	PlatformID_iOS                 PlatformID = 5
)

// Enum value maps for PlatformID.
var (
	PlatformID_name = map[int32]string{
		0: "UnspecifiedPlatform",
		1: "macOS",
		2: "Windows",
		3: "Linux",
		4: "Android",
		5: "iOS",
	}
	PlatformID_value = map[string]int32{
		"UnspecifiedPlatform": 0,
		"macOS":               1,
		"Windows":             2,
		"Linux":               3,
		"Android":             4,
		"iOS":                 5,
	}
)

func (x PlatformID) Enum() *PlatformID {
	p := new(PlatformID)
	*p = x
	return p
}

func (x PlatformID) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PlatformID) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_crates_amp_crates_proto_enumTypes[0].Descriptor()
}

func (PlatformID) Type() protoreflect.EnumType {
	return &file_amp_crates_amp_crates_proto_enumTypes[0]
}

func (x PlatformID) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PlatformID.Descriptor instead.
func (PlatformID) EnumDescriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{0}
}

// OSVariant distinguishes privacy/de-Googled forks sharing a PlatformID's binary.
type OSVariant int32

const (
	OSVariant_Stock      OSVariant = 0 // default stock OS (Apple, Microsoft, Google, Ubuntu, etc.)
	OSVariant_GrapheneOS OSVariant = 1
	OSVariant_CalyxOS    OSVariant = 2
	OSVariant_LineageOS  OSVariant = 3
)

// Enum value maps for OSVariant.
var (
	OSVariant_name = map[int32]string{
		0: "Stock",
		1: "GrapheneOS",
		2: "CalyxOS",
		3: "LineageOS",
	}
	OSVariant_value = map[string]int32{
		"Stock":      0,
		"GrapheneOS": 1,
		"CalyxOS":    2,
		"LineageOS":  3,
	}
)

func (x OSVariant) Enum() *OSVariant {
	p := new(OSVariant)
	*p = x
	return p
}

func (x OSVariant) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OSVariant) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_crates_amp_crates_proto_enumTypes[1].Descriptor()
}

func (OSVariant) Type() protoreflect.EnumType {
	return &file_amp_crates_amp_crates_proto_enumTypes[1]
}

func (x OSVariant) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OSVariant.Descriptor instead.
func (OSVariant) EnumDescriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{1}
}

// AssetKind identifies what an asset *is* — exactly one kind per AssetEntry.
// Orthogonal properties (placeable, private, auto-scale, etc.) live as explicit
// bool fields on AssetEntry.
type AssetKind int32

const (
	AssetKind_UnspecifiedKind AssetKind = 0
	AssetKind_Texture         AssetKind = 1
	AssetKind_Sprite          AssetKind = 2
	AssetKind_Material        AssetKind = 3
	AssetKind_Scene           AssetKind = 4
	AssetKind_Skybox          AssetKind = 5
	AssetKind_Surface         AssetKind = 6 // terrain-like / opaque collider (buildings, walls, terrain)
	AssetKind_VisualLayer     AssetKind = 7
	AssetKind_VisualScope     AssetKind = 8
)

// Enum value maps for AssetKind.
var (
	AssetKind_name = map[int32]string{
		0: "UnspecifiedKind",
		1: "Texture",
		2: "Sprite",
		3: "Material",
		4: "Scene",
		5: "Skybox",
		6: "Surface",
		7: "VisualLayer",
		8: "VisualScope",
	}
	AssetKind_value = map[string]int32{
		"UnspecifiedKind": 0,
		"Texture":         1,
		"Sprite":          2,
		"Material":        3,
		"Scene":           4,
		"Skybox":          5,
		"Surface":         6,
		"VisualLayer":     7,
		"VisualScope":     8,
	}
)

func (x AssetKind) Enum() *AssetKind {
	p := new(AssetKind)
	*p = x
	return p
}

func (x AssetKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AssetKind) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_crates_amp_crates_proto_enumTypes[2].Descriptor()
}

func (AssetKind) Type() protoreflect.EnumType {
	return &file_amp_crates_amp_crates_proto_enumTypes[2]
}

func (x AssetKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AssetKind.Descriptor instead.
func (AssetKind) EnumDescriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{2}
}

// Enum values should be three base-10 digits corresponding to the major, minor, and revision number.
type CrateSchema int32

const (
	CrateSchema_UndefinedSchema CrateSchema = 0
	// v100 (April 2020) should be used for CrateInfo.CrateSchema
	CrateSchema_v100 CrateSchema = 100
)

// Enum value maps for CrateSchema.
var (
	CrateSchema_name = map[int32]string{
		0:   "UndefinedSchema",
		100: "v100",
	}
	CrateSchema_value = map[string]int32{
		"UndefinedSchema": 0,
		"v100":            100,
	}
)

func (x CrateSchema) Enum() *CrateSchema {
	p := new(CrateSchema)
	*p = x
	return p
}

func (x CrateSchema) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CrateSchema) Descriptor() protoreflect.EnumDescriptor {
	return file_amp_crates_amp_crates_proto_enumTypes[3].Descriptor()
}

func (CrateSchema) Type() protoreflect.EnumType {
	return &file_amp_crates_amp_crates_proto_enumTypes[3]
}

func (x CrateSchema) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CrateSchema.Descriptor instead.
func (CrateSchema) EnumDescriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{3}
}

type AssetEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Kind  AssetKind              `protobuf:"varint,1,opt,name=Kind,proto3,enum=crates.AssetKind" json:"Kind,omitempty"`
	// EntryURI is a Unix-style pathname that identifies an asset within a crate.
	// By convention, this URI does *not* start or end with '/'
	// An asset URI has the form "{CrateURI}/{EntryURI}"
	// If two or more assets have the same EntryURI, then only one is accessible.
	EntryURI string `protobuf:"bytes,2,opt,name=EntryURI,proto3" json:"EntryURI,omitempty"`
	// Label is the human-readable label for this asset.
	Label string `protobuf:"bytes,3,opt,name=Label,proto3" json:"Label,omitempty"`
	// Orthogonal asset properties (each independently settable).
	IsPlaceable     bool `protobuf:"varint,5,opt,name=IsPlaceable,proto3" json:"IsPlaceable,omitempty"`         // can be placed in a space
	IsRectTransform bool `protobuf:"varint,6,opt,name=IsRectTransform,proto3" json:"IsRectTransform,omitempty"` // has a RectTransform component
	HasIcon         bool `protobuf:"varint,7,opt,name=HasIcon,proto3" json:"HasIcon,omitempty"`                 // ships with a matching icon asset
	IsPrivate       bool `protobuf:"varint,8,opt,name=IsPrivate,proto3" json:"IsPrivate,omitempty"`             // not normally visible to end users
	AutoScale       bool `protobuf:"varint,9,opt,name=AutoScale,proto3" json:"AutoScale,omitempty"`             // place with auto-scale enabled by default
	// CenterX and CenterZ specify the positional center of this asset (and are typically 0).
	// CenterY is the distance above the baseline (y=0) to the y center-point height of this asset.
	// Y is considered to be the *vertical* (up) direction and by convention rests on the plane y=0.
	CenterX float32 `protobuf:"fixed32,10,opt,name=CenterX,proto3" json:"CenterX,omitempty"`
	CenterY float32 `protobuf:"fixed32,11,opt,name=CenterY,proto3" json:"CenterY,omitempty"`
	CenterZ float32 `protobuf:"fixed32,12,opt,name=CenterZ,proto3" json:"CenterZ,omitempty"`
	// Extents specify the distance from the center to the extent of the asset on each axis.
	ExtentsX float32 `protobuf:"fixed32,15,opt,name=ExtentsX,proto3" json:"ExtentsX,omitempty"`
	ExtentsY float32 `protobuf:"fixed32,16,opt,name=ExtentsY,proto3" json:"ExtentsY,omitempty"`
	ExtentsZ float32 `protobuf:"fixed32,17,opt,name=ExtentsZ,proto3" json:"ExtentsZ,omitempty"`
	// Reserved for runtime use -- defaults to empty.
	LocalURI string `protobuf:"bytes,30,opt,name=LocalURI,proto3" json:"LocalURI,omitempty"`
	// Comma-delimited and whitespace-trimmed list of tags.
	Tags string `protobuf:"bytes,31,opt,name=Tags,proto3" json:"Tags,omitempty"`
	// A short phrase or fragment describing this asset, starting with an article where appropriate. e.g.:
	//
	//	"A typical 6 crew member fire truck"
	//	"A leading U.S. naval ship-based helicopter"
	//	"The Texas capitol building located in Austin"
	//	"An animated scared-geometry inspired flat seal"
	ShortDesc     string `protobuf:"bytes,32,opt,name=ShortDesc,proto3" json:"ShortDesc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssetEntry) Reset() {
	*x = AssetEntry{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssetEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssetEntry) ProtoMessage() {}

func (x *AssetEntry) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssetEntry.ProtoReflect.Descriptor instead.
func (*AssetEntry) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{0}
}

func (x *AssetEntry) GetKind() AssetKind {
	if x != nil {
		return x.Kind
	}
	return AssetKind_UnspecifiedKind
}

func (x *AssetEntry) GetEntryURI() string {
	if x != nil {
		return x.EntryURI
	}
	return ""
}

func (x *AssetEntry) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AssetEntry) GetIsPlaceable() bool {
	if x != nil {
		return x.IsPlaceable
	}
	return false
}

func (x *AssetEntry) GetIsRectTransform() bool {
	if x != nil {
		return x.IsRectTransform
	}
	return false
}

func (x *AssetEntry) GetHasIcon() bool {
	if x != nil {
		return x.HasIcon
	}
	return false
}

func (x *AssetEntry) GetIsPrivate() bool {
	if x != nil {
		return x.IsPrivate
	}
	return false
}

func (x *AssetEntry) GetAutoScale() bool {
	if x != nil {
		return x.AutoScale
	}
	return false
}

func (x *AssetEntry) GetCenterX() float32 {
	if x != nil {
		return x.CenterX
	}
	return 0
}

func (x *AssetEntry) GetCenterY() float32 {
	if x != nil {
		return x.CenterY
	}
	return 0
}

func (x *AssetEntry) GetCenterZ() float32 {
	if x != nil {
		return x.CenterZ
	}
	return 0
}

func (x *AssetEntry) GetExtentsX() float32 {
	if x != nil {
		return x.ExtentsX
	}
	return 0
}

func (x *AssetEntry) GetExtentsY() float32 {
	if x != nil {
		return x.ExtentsY
	}
	return 0
}

func (x *AssetEntry) GetExtentsZ() float32 {
	if x != nil {
		return x.ExtentsZ
	}
	return 0
}

func (x *AssetEntry) GetLocalURI() string {
	if x != nil {
		return x.LocalURI
	}
	return ""
}

func (x *AssetEntry) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *AssetEntry) GetShortDesc() string {
	if x != nil {
		return x.ShortDesc
	}
	return ""
}

type BundleManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BundleTitle is how the outside world sees this bundle and has no other impact.
	// This means it can change from build to build and contain any Unicode characters.
	BundleTitle string `protobuf:"bytes,2,opt,name=BundleTitle,proto3" json:"BundleTitle,omitempty"`
	// BundleNameID is how this bundle is internally identified and expressed as the filename of this bundle.
	// This is case sensitive, contains only path-safe characters (sans /:\<>|?*\"), and does not terminate in '.' or whitespace.
	BundleNameID  string        `protobuf:"bytes,3,opt,name=BundleNameID,proto3" json:"BundleNameID,omitempty"`
	Assets        []*AssetEntry `protobuf:"bytes,10,rep,name=Assets,proto3" json:"Assets,omitempty"`
	LoadAllHint   bool          `protobuf:"varint,20,opt,name=LoadAllHint,proto3" json:"LoadAllHint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BundleManifest) Reset() {
	*x = BundleManifest{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BundleManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BundleManifest) ProtoMessage() {}

func (x *BundleManifest) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BundleManifest.ProtoReflect.Descriptor instead.
func (*BundleManifest) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{1}
}

func (x *BundleManifest) GetBundleTitle() string {
	if x != nil {
		return x.BundleTitle
	}
	return ""
}

func (x *BundleManifest) GetBundleNameID() string {
	if x != nil {
		return x.BundleNameID
	}
	return ""
}

func (x *BundleManifest) GetAssets() []*AssetEntry {
	if x != nil {
		return x.Assets
	}
	return nil
}

func (x *BundleManifest) GetLoadAllHint() bool {
	if x != nil {
		return x.LoadAllHint
	}
	return false
}

// CrateInfo represents a Crate, the fundamental unit of amp's asset/package manager.
type CrateInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// CrateSchema communicates which build and packaging schema was used for this crate build.
	// This value should be the integer value of a valid CrateSchema.vNNN enum.
	CrateSchema int32 `protobuf:"varint,1,opt,name=CrateSchema,proto3" json:"CrateSchema,omitempty"`
	// InstID is 0 by default and reserved for a runtime manager to reference a crate via issuing integers.
	// If non-zero, it will not change and no other instance will have the same value.
	InstID uint32 `protobuf:"varint,2,opt,name=InstID,proto3" json:"InstID,omitempty"`
	// CrateURI takes the form "{PublisherID}/{CrateID}" and is used to globally reference assets in this crate.
	// This URI string can only contain chars in [A-Za-z0-9_.-] (other than the separating '/' char).
	// PublisherID uniquely identifies the author/owner/publisher of this crate (and potentially other crates).
	// CrateID uniquely identifies this crate for the given publisher and all subsequent revisions.
	//
	//	"plan-systems.org/plan.app.ui"
	//	"plan-systems.org/about-plan-systems"
	//	"themushroom.farm/land"
	//	"themushroom.farm/mycology-201"
	//	"the-smiths.family/123-Maple"
	CrateURI string `protobuf:"bytes,4,opt,name=CrateURI,proto3" json:"CrateURI,omitempty"`
	// PublisherName is a human-readable name of the author/owner/publisher of this crate and can change without repercussions (i.e. is purely optical).
	PublisherName string `protobuf:"bytes,6,opt,name=PublisherName,proto3" json:"PublisherName,omitempty"`
	// CrateName is a human-readable title for this crate and can change without repercussions.
	CrateName string `protobuf:"bytes,10,opt,name=CrateName,proto3" json:"CrateName,omitempty"`
	// ShortDesc describes this crate in a brief phrase.
	ShortDesc string `protobuf:"bytes,11,opt,name=ShortDesc,proto3" json:"ShortDesc,omitempty"`
	// Comma-delimited and whitespace-trimmed list of tags.
	Tags string `protobuf:"bytes,15,opt,name=Tags,proto3" json:"Tags,omitempty"`
	// TimeCreated is the UTC value (in seconds) when this crate was first created (and does not change).
	TimeCreated int64 `protobuf:"varint,30,opt,name=TimeCreated,proto3" json:"TimeCreated,omitempty"`
	// TimeBuilt is the UTC value (in seconds) when this crate was built.
	TimeBuilt int64 `protobuf:"varint,31,opt,name=TimeBuilt,proto3" json:"TimeBuilt,omitempty"`
	// VersionID uniquely identifies this build and has the form "v{MajorNum}.{MinorNum}.{BuildNum}"
	// e.g. "v1.11.201"
	MajorVersion int32 `protobuf:"varint,40,opt,name=MajorVersion,proto3" json:"MajorVersion,omitempty"`
	MinorVersion int32 `protobuf:"varint,41,opt,name=MinorVersion,proto3" json:"MinorVersion,omitempty"`
	BuildNumber  int32 `protobuf:"varint,42,opt,name=BuildNumber,proto3" json:"BuildNumber,omitempty"`
	// BuildID uniquely identifies a particular crate build/version.
	// This value should have no spaces and only have '.', '_', or '-' (and starts and ends with an alphanumeric character).
	// By convention, the format is "yyMMdd-{VersionID}" (so that sorting by BuildID string yields the most recent release).
	// e.g. "210320-v0.1.11"
	BuildID string `protobuf:"bytes,45,opt,name=BuildID,proto3" json:"BuildID,omitempty"`
	// HomeURL is an optional link that allows a human to learn more about this crate.
	HomeURL string `protobuf:"bytes,50,opt,name=HomeURL,proto3" json:"HomeURL,omitempty"`
	// URL is an optional string available to specify a URL to download this crate.
	URL string `protobuf:"bytes,55,opt,name=URL,proto3" json:"URL,omitempty"`
	// Approximate size of this crate in bytes (or 0 if unknown).
	ApproxSize    int64 `protobuf:"varint,60,opt,name=ApproxSize,proto3" json:"ApproxSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrateInfo) Reset() {
	*x = CrateInfo{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrateInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrateInfo) ProtoMessage() {}

func (x *CrateInfo) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrateInfo.ProtoReflect.Descriptor instead.
func (*CrateInfo) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{2}
}

func (x *CrateInfo) GetCrateSchema() int32 {
	if x != nil {
		return x.CrateSchema
	}
	return 0
}

func (x *CrateInfo) GetInstID() uint32 {
	if x != nil {
		return x.InstID
	}
	return 0
}

func (x *CrateInfo) GetCrateURI() string {
	if x != nil {
		return x.CrateURI
	}
	return ""
}

func (x *CrateInfo) GetPublisherName() string {
	if x != nil {
		return x.PublisherName
	}
	return ""
}

func (x *CrateInfo) GetCrateName() string {
	if x != nil {
		return x.CrateName
	}
	return ""
}

func (x *CrateInfo) GetShortDesc() string {
	if x != nil {
		return x.ShortDesc
	}
	return ""
}

func (x *CrateInfo) GetTags() string {
	if x != nil {
		return x.Tags
	}
	return ""
}

func (x *CrateInfo) GetTimeCreated() int64 {
	if x != nil {
		return x.TimeCreated
	}
	return 0
}

func (x *CrateInfo) GetTimeBuilt() int64 {
	if x != nil {
		return x.TimeBuilt
	}
	return 0
}

func (x *CrateInfo) GetMajorVersion() int32 {
	if x != nil {
		return x.MajorVersion
	}
	return 0
}

func (x *CrateInfo) GetMinorVersion() int32 {
	if x != nil {
		return x.MinorVersion
	}
	return 0
}

func (x *CrateInfo) GetBuildNumber() int32 {
	if x != nil {
		return x.BuildNumber
	}
	return 0
}

func (x *CrateInfo) GetBuildID() string {
	if x != nil {
		return x.BuildID
	}
	return ""
}

func (x *CrateInfo) GetHomeURL() string {
	if x != nil {
		return x.HomeURL
	}
	return ""
}

func (x *CrateInfo) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

func (x *CrateInfo) GetApproxSize() int64 {
	if x != nil {
		return x.ApproxSize
	}
	return 0
}

// CrateManifest is the top-level manifest/catalog for a amp asset module called a "crate".
// It contains catalog and type info that amp loads at runtime to know what's inside binary asset bundles without having to load them.
//
// A reference to a amp asset is via a URI with the form:
//
//	assetURI := "PublisherID/CrateID[@CrateBuildID]/{AssetEntry.Pathname}"
type CrateManifest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Info  *CrateInfo             `protobuf:"bytes,1,opt,name=Info,proto3" json:"Info,omitempty"`
	// IconBundleName is the bundle name ID of the bundle containing icons (Sprites) used to represent the "real" crate assets.
	// Asset name IDs in this bundle correspond to assets in all the other Crate's bundles.
	IconBundleName string            `protobuf:"bytes,5,opt,name=IconBundleName,proto3" json:"IconBundleName,omitempty"`
	Bundles        []*BundleManifest `protobuf:"bytes,10,rep,name=Bundles,proto3" json:"Bundles,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CrateManifest) Reset() {
	*x = CrateManifest{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrateManifest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrateManifest) ProtoMessage() {}

func (x *CrateManifest) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrateManifest.ProtoReflect.Descriptor instead.
func (*CrateManifest) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{3}
}

func (x *CrateManifest) GetInfo() *CrateInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *CrateManifest) GetIconBundleName() string {
	if x != nil {
		return x.IconBundleName
	}
	return ""
}

func (x *CrateManifest) GetBundles() []*BundleManifest {
	if x != nil {
		return x.Bundles
	}
	return nil
}

// CrateSnapshot is a general purpose container to track multiple crates and associated build IDs.
type CrateSnapshot struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	RevID int64                  `protobuf:"varint,1,opt,name=RevID,proto3" json:"RevID,omitempty"`
	// This is a template URL where the symbols "CrateURI", "CrateBuildID", "PlatformID" are delimited with { }.
	// The symbol "{.}" is to be replaced with a local pathname if the URL refers to a local file system pathname.
	// e.g. "https://whatever.com/{CrateURI}__{CrateBuildID}.{PlatformID}.crate"
	//
	//	"{.}/{CrateURI}__{CrateBuildID}.{PlatformID}.crate"
	DownloadURL   string       `protobuf:"bytes,3,opt,name=DownloadURL,proto3" json:"DownloadURL,omitempty"`
	Crates        []*CrateInfo `protobuf:"bytes,10,rep,name=Crates,proto3" json:"Crates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CrateSnapshot) Reset() {
	*x = CrateSnapshot{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrateSnapshot) ProtoMessage() {}

func (x *CrateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CrateSnapshot.ProtoReflect.Descriptor instead.
func (*CrateSnapshot) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{4}
}

func (x *CrateSnapshot) GetRevID() int64 {
	if x != nil {
		return x.RevID
	}
	return 0
}

func (x *CrateSnapshot) GetDownloadURL() string {
	if x != nil {
		return x.DownloadURL
	}
	return ""
}

func (x *CrateSnapshot) GetCrates() []*CrateInfo {
	if x != nil {
		return x.Crates
	}
	return nil
}

// AppBrand is the whitelabel skin and install manifest for an amp-built app.
//
// Shipped bundled with the app (factory copy) and refreshable over the air via
// {AppDomain}/.well-known/app.brand.json.  A single AppBrand covers one app's
// identity, its deep-link schemes, per-platform install targets, and curated
// entry points — enough for any landing page or planet invite to route a new
// user to the correct store link for their device.
type AppBrand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Identity
	AppName    string `protobuf:"bytes,1,opt,name=AppName,proto3" json:"AppName,omitempty"`       // "Tunr"
	AppDomain  string `protobuf:"bytes,2,opt,name=AppDomain,proto3" json:"AppDomain,omitempty"`   // "tunr.plan.tools"  (also used for well-known fetches)
	AppDesc    string `protobuf:"bytes,3,opt,name=AppDesc,proto3" json:"AppDesc,omitempty"`       // short one-liner
	OrgName    string `protobuf:"bytes,5,opt,name=OrgName,proto3" json:"OrgName,omitempty"`       // "PLAN Systems"
	OrgHomeURL string `protobuf:"bytes,6,opt,name=OrgHomeURL,proto3" json:"OrgHomeURL,omitempty"` // "https://plan-systems.org"
	AppHomeURL string `protobuf:"bytes,7,opt,name=AppHomeURL,proto3" json:"AppHomeURL,omitempty"` // "https://tunr.plan.tools"
	// Native URL schemes this app registers (first is primary).
	// Incoming URLs on these schemes are rewritten to "amp://" internally.
	URLSchemes []string `protobuf:"bytes,10,rep,name=URLSchemes,proto3" json:"URLSchemes,omitempty"`
	// Platform install targets — the portal and onboarding pages choose the
	// matching AppTarget for the visitor's device.
	Targets []*AppTarget `protobuf:"bytes,15,rep,name=Targets,proto3" json:"Targets,omitempty"`
	// CrateSnapshot feed this brand consumes for content updates.
	CrateSnapshotURL string `protobuf:"bytes,20,opt,name=CrateSnapshotURL,proto3" json:"CrateSnapshotURL,omitempty"`
	// Curated deep links: featured planets, support channel, onboarding, etc.
	Links         []*AppLink `protobuf:"bytes,25,rep,name=Links,proto3" json:"Links,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppBrand) Reset() {
	*x = AppBrand{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppBrand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppBrand) ProtoMessage() {}

func (x *AppBrand) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppBrand.ProtoReflect.Descriptor instead.
func (*AppBrand) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{5}
}

func (x *AppBrand) GetAppName() string {
	if x != nil {
		return x.AppName
	}
	return ""
}

func (x *AppBrand) GetAppDomain() string {
	if x != nil {
		return x.AppDomain
	}
	return ""
}

func (x *AppBrand) GetAppDesc() string {
	if x != nil {
		return x.AppDesc
	}
	return ""
}

func (x *AppBrand) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

func (x *AppBrand) GetOrgHomeURL() string {
	if x != nil {
		return x.OrgHomeURL
	}
	return ""
}

func (x *AppBrand) GetAppHomeURL() string {
	if x != nil {
		return x.AppHomeURL
	}
	return ""
}

func (x *AppBrand) GetURLSchemes() []string {
	if x != nil {
		return x.URLSchemes
	}
	return nil
}

func (x *AppBrand) GetTargets() []*AppTarget {
	if x != nil {
		return x.Targets
	}
	return nil
}

func (x *AppBrand) GetCrateSnapshotURL() string {
	if x != nil {
		return x.CrateSnapshotURL
	}
	return ""
}

func (x *AppBrand) GetLinks() []*AppLink {
	if x != nil {
		return x.Links
	}
	return nil
}

// AppTarget describes where to obtain the app for one (PlatformID, OSVariant) pair.
type AppTarget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Platform      PlatformID             `protobuf:"varint,1,opt,name=Platform,proto3,enum=crates.PlatformID" json:"Platform,omitempty"`
	OSVariant     OSVariant              `protobuf:"varint,2,opt,name=OSVariant,proto3,enum=crates.OSVariant" json:"OSVariant,omitempty"` // 0 = Stock; set for de-Googled variants
	DownloadURL   string                 `protobuf:"bytes,3,opt,name=DownloadURL,proto3" json:"DownloadURL,omitempty"`                    // store URL, HTTPS download, magnet link, etc.
	BundleID      string                 `protobuf:"bytes,4,opt,name=BundleID,proto3" json:"BundleID,omitempty"`                          // "org.plan.tunr" (iOS/Android bundle ID)
	MinOSVersion  string                 `protobuf:"bytes,5,opt,name=MinOSVersion,proto3" json:"MinOSVersion,omitempty"`                  // minimum OS version, e.g. "14.0"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppTarget) Reset() {
	*x = AppTarget{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppTarget) ProtoMessage() {}

func (x *AppTarget) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppTarget.ProtoReflect.Descriptor instead.
func (*AppTarget) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{6}
}

func (x *AppTarget) GetPlatform() PlatformID {
	if x != nil {
		return x.Platform
	}
	return PlatformID_UnspecifiedPlatform
}

func (x *AppTarget) GetOSVariant() OSVariant {
	if x != nil {
		return x.OSVariant
	}
	return OSVariant_Stock
}

func (x *AppTarget) GetDownloadURL() string {
	if x != nil {
		return x.DownloadURL
	}
	return ""
}

func (x *AppTarget) GetBundleID() string {
	if x != nil {
		return x.BundleID
	}
	return ""
}

func (x *AppTarget) GetMinOSVersion() string {
	if x != nil {
		return x.MinOSVersion
	}
	return ""
}

// AppLink is one curated entry point — typically an amp:// or https:// URL with a label.
type AppLink struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Label         string                 `protobuf:"bytes,1,opt,name=Label,proto3" json:"Label,omitempty"`
	URL           string                 `protobuf:"bytes,2,opt,name=URL,proto3" json:"URL,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppLink) Reset() {
	*x = AppLink{}
	mi := &file_amp_crates_amp_crates_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppLink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppLink) ProtoMessage() {}

func (x *AppLink) ProtoReflect() protoreflect.Message {
	mi := &file_amp_crates_amp_crates_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppLink.ProtoReflect.Descriptor instead.
func (*AppLink) Descriptor() ([]byte, []int) {
	return file_amp_crates_amp_crates_proto_rawDescGZIP(), []int{7}
}

func (x *AppLink) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *AppLink) GetURL() string {
	if x != nil {
		return x.URL
	}
	return ""
}

var File_amp_crates_amp_crates_proto protoreflect.FileDescriptor

const file_amp_crates_amp_crates_proto_rawDesc = "" +
	"\n" +
	"\x1bamp/crates/amp.crates.proto\x12\x06crates\"\xf7\x03\n" +
	"\n" +
	"AssetEntry\x12%\n" +
	"\x04Kind\x18\x01 \x01(\x0e2\x11.crates.AssetKindR\x04Kind\x12\x1a\n" +
	"\bEntryURI\x18\x02 \x01(\tR\bEntryURI\x12\x14\n" +
	"\x05Label\x18\x03 \x01(\tR\x05Label\x12 \n" +
	"\vIsPlaceable\x18\x05 \x01(\bR\vIsPlaceable\x12(\n" +
	"\x0fIsRectTransform\x18\x06 \x01(\bR\x0fIsRectTransform\x12\x18\n" +
	"\aHasIcon\x18\a \x01(\bR\aHasIcon\x12\x1c\n" +
	"\tIsPrivate\x18\b \x01(\bR\tIsPrivate\x12\x1c\n" +
	"\tAutoScale\x18\t \x01(\bR\tAutoScale\x12\x18\n" +
	"\aCenterX\x18\n" +
	" \x01(\x02R\aCenterX\x12\x18\n" +
	"\aCenterY\x18\v \x01(\x02R\aCenterY\x12\x18\n" +
	"\aCenterZ\x18\f \x01(\x02R\aCenterZ\x12\x1a\n" +
	"\bExtentsX\x18\x0f \x01(\x02R\bExtentsX\x12\x1a\n" +
	"\bExtentsY\x18\x10 \x01(\x02R\bExtentsY\x12\x1a\n" +
	"\bExtentsZ\x18\x11 \x01(\x02R\bExtentsZ\x12\x1a\n" +
	"\bLocalURI\x18\x1e \x01(\tR\bLocalURI\x12\x12\n" +
	"\x04Tags\x18\x1f \x01(\tR\x04Tags\x12\x1c\n" +
	"\tShortDesc\x18  \x01(\tR\tShortDesc\"\xa4\x01\n" +
	"\x0eBundleManifest\x12 \n" +
	"\vBundleTitle\x18\x02 \x01(\tR\vBundleTitle\x12\"\n" +
	"\fBundleNameID\x18\x03 \x01(\tR\fBundleNameID\x12*\n" +
	"\x06Assets\x18\n" +
	" \x03(\v2\x12.crates.AssetEntryR\x06Assets\x12 \n" +
	"\vLoadAllHint\x18\x14 \x01(\bR\vLoadAllHint\"\xe7\x03\n" +
	"\tCrateInfo\x12 \n" +
	"\vCrateSchema\x18\x01 \x01(\x05R\vCrateSchema\x12\x16\n" +
	"\x06InstID\x18\x02 \x01(\rR\x06InstID\x12\x1a\n" +
	"\bCrateURI\x18\x04 \x01(\tR\bCrateURI\x12$\n" +
	"\rPublisherName\x18\x06 \x01(\tR\rPublisherName\x12\x1c\n" +
	"\tCrateName\x18\n" +
	" \x01(\tR\tCrateName\x12\x1c\n" +
	"\tShortDesc\x18\v \x01(\tR\tShortDesc\x12\x12\n" +
	"\x04Tags\x18\x0f \x01(\tR\x04Tags\x12 \n" +
	"\vTimeCreated\x18\x1e \x01(\x03R\vTimeCreated\x12\x1c\n" +
	"\tTimeBuilt\x18\x1f \x01(\x03R\tTimeBuilt\x12\"\n" +
	"\fMajorVersion\x18( \x01(\x05R\fMajorVersion\x12\"\n" +
	"\fMinorVersion\x18) \x01(\x05R\fMinorVersion\x12 \n" +
	"\vBuildNumber\x18* \x01(\x05R\vBuildNumber\x12\x18\n" +
	"\aBuildID\x18- \x01(\tR\aBuildID\x12\x18\n" +
	"\aHomeURL\x182 \x01(\tR\aHomeURL\x12\x10\n" +
	"\x03URL\x187 \x01(\tR\x03URL\x12\x1e\n" +
	"\n" +
	"ApproxSize\x18< \x01(\x03R\n" +
	"ApproxSize\"\x90\x01\n" +
	"\rCrateManifest\x12%\n" +
	"\x04Info\x18\x01 \x01(\v2\x11.crates.CrateInfoR\x04Info\x12&\n" +
	"\x0eIconBundleName\x18\x05 \x01(\tR\x0eIconBundleName\x120\n" +
	"\aBundles\x18\n" +
	" \x03(\v2\x16.crates.BundleManifestR\aBundles\"r\n" +
	"\rCrateSnapshot\x12\x14\n" +
	"\x05RevID\x18\x01 \x01(\x03R\x05RevID\x12 \n" +
	"\vDownloadURL\x18\x03 \x01(\tR\vDownloadURL\x12)\n" +
	"\x06Crates\x18\n" +
	" \x03(\v2\x11.crates.CrateInfoR\x06Crates\"\xd6\x02\n" +
	"\bAppBrand\x12\x18\n" +
	"\aAppName\x18\x01 \x01(\tR\aAppName\x12\x1c\n" +
	"\tAppDomain\x18\x02 \x01(\tR\tAppDomain\x12\x18\n" +
	"\aAppDesc\x18\x03 \x01(\tR\aAppDesc\x12\x18\n" +
	"\aOrgName\x18\x05 \x01(\tR\aOrgName\x12\x1e\n" +
	"\n" +
	"OrgHomeURL\x18\x06 \x01(\tR\n" +
	"OrgHomeURL\x12\x1e\n" +
	"\n" +
	"AppHomeURL\x18\a \x01(\tR\n" +
	"AppHomeURL\x12\x1e\n" +
	"\n" +
	"URLSchemes\x18\n" +
	" \x03(\tR\n" +
	"URLSchemes\x12+\n" +
	"\aTargets\x18\x0f \x03(\v2\x11.crates.AppTargetR\aTargets\x12*\n" +
	"\x10CrateSnapshotURL\x18\x14 \x01(\tR\x10CrateSnapshotURL\x12%\n" +
	"\x05Links\x18\x19 \x03(\v2\x0f.crates.AppLinkR\x05Links\"\xce\x01\n" +
	"\tAppTarget\x12.\n" +
	"\bPlatform\x18\x01 \x01(\x0e2\x12.crates.PlatformIDR\bPlatform\x12/\n" +
	"\tOSVariant\x18\x02 \x01(\x0e2\x11.crates.OSVariantR\tOSVariant\x12 \n" +
	"\vDownloadURL\x18\x03 \x01(\tR\vDownloadURL\x12\x1a\n" +
	"\bBundleID\x18\x04 \x01(\tR\bBundleID\x12\"\n" +
	"\fMinOSVersion\x18\x05 \x01(\tR\fMinOSVersion\"1\n" +
	"\aAppLink\x12\x14\n" +
	"\x05Label\x18\x01 \x01(\tR\x05Label\x12\x10\n" +
	"\x03URL\x18\x02 \x01(\tR\x03URL*^\n" +
	"\n" +
	"PlatformID\x12\x17\n" +
	"\x13UnspecifiedPlatform\x10\x00\x12\t\n" +
	"\x05macOS\x10\x01\x12\v\n" +
	"\aWindows\x10\x02\x12\t\n" +
	"\x05Linux\x10\x03\x12\v\n" +
	"\aAndroid\x10\x04\x12\a\n" +
	"\x03iOS\x10\x05*B\n" +
	"\tOSVariant\x12\t\n" +
	"\x05Stock\x10\x00\x12\x0e\n" +
	"\n" +
	"GrapheneOS\x10\x01\x12\v\n" +
	"\aCalyxOS\x10\x02\x12\r\n" +
	"\tLineageOS\x10\x03*\x8d\x01\n" +
	"\tAssetKind\x12\x13\n" +
	"\x0fUnspecifiedKind\x10\x00\x12\v\n" +
	"\aTexture\x10\x01\x12\n" +
	"\n" +
	"\x06Sprite\x10\x02\x12\f\n" +
	"\bMaterial\x10\x03\x12\t\n" +
	"\x05Scene\x10\x04\x12\n" +
	"\n" +
	"\x06Skybox\x10\x05\x12\v\n" +
	"\aSurface\x10\x06\x12\x0f\n" +
	"\vVisualLayer\x10\a\x12\x0f\n" +
	"\vVisualScope\x10\b*,\n" +
	"\vCrateSchema\x12\x13\n" +
	"\x0fUndefinedSchema\x10\x00\x12\b\n" +
	"\x04v100\x10dBGZ0github.com/art-media-platform/amp.SDK/amp/crates\xaa\x02\x12art.media.platformb\x06proto3"

var (
	file_amp_crates_amp_crates_proto_rawDescOnce sync.Once
	file_amp_crates_amp_crates_proto_rawDescData []byte
)

func file_amp_crates_amp_crates_proto_rawDescGZIP() []byte {
	file_amp_crates_amp_crates_proto_rawDescOnce.Do(func() {
		file_amp_crates_amp_crates_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_amp_crates_amp_crates_proto_rawDesc), len(file_amp_crates_amp_crates_proto_rawDesc)))
	})
	return file_amp_crates_amp_crates_proto_rawDescData
}

var file_amp_crates_amp_crates_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_amp_crates_amp_crates_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_amp_crates_amp_crates_proto_goTypes = []any{
	(PlatformID)(0),        // 0: crates.PlatformID
	(OSVariant)(0),         // 1: crates.OSVariant
	(AssetKind)(0),         // 2: crates.AssetKind
	(CrateSchema)(0),       // 3: crates.CrateSchema
	(*AssetEntry)(nil),     // 4: crates.AssetEntry
	(*BundleManifest)(nil), // 5: crates.BundleManifest
	(*CrateInfo)(nil),      // 6: crates.CrateInfo
	(*CrateManifest)(nil),  // 7: crates.CrateManifest
	(*CrateSnapshot)(nil),  // 8: crates.CrateSnapshot
	(*AppBrand)(nil),       // 9: crates.AppBrand
	(*AppTarget)(nil),      // 10: crates.AppTarget
	(*AppLink)(nil),        // 11: crates.AppLink
}
var file_amp_crates_amp_crates_proto_depIdxs = []int32{
	2,  // 0: crates.AssetEntry.Kind:type_name -> crates.AssetKind
	4,  // 1: crates.BundleManifest.Assets:type_name -> crates.AssetEntry
	6,  // 2: crates.CrateManifest.Info:type_name -> crates.CrateInfo
	5,  // 3: crates.CrateManifest.Bundles:type_name -> crates.BundleManifest
	6,  // 4: crates.CrateSnapshot.Crates:type_name -> crates.CrateInfo
	10, // 5: crates.AppBrand.Targets:type_name -> crates.AppTarget
	11, // 6: crates.AppBrand.Links:type_name -> crates.AppLink
	0,  // 7: crates.AppTarget.Platform:type_name -> crates.PlatformID
	1,  // 8: crates.AppTarget.OSVariant:type_name -> crates.OSVariant
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_amp_crates_amp_crates_proto_init() }
func file_amp_crates_amp_crates_proto_init() {
	if File_amp_crates_amp_crates_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_amp_crates_amp_crates_proto_rawDesc), len(file_amp_crates_amp_crates_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_amp_crates_amp_crates_proto_goTypes,
		DependencyIndexes: file_amp_crates_amp_crates_proto_depIdxs,
		EnumInfos:         file_amp_crates_amp_crates_proto_enumTypes,
		MessageInfos:      file_amp_crates_amp_crates_proto_msgTypes,
	}.Build()
	File_amp_crates_amp_crates_proto = out.File
	file_amp_crates_amp_crates_proto_goTypes = nil
	file_amp_crates_amp_crates_proto_depIdxs = nil
}
