// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: stdlib/status/status.proto

package status

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Code expresses status and error codes.
type Code int32

const (
	Code_Nil                        Code = 0
	Code_Unnamed                    Code = -23001
	Code_AssertFailed               Code = -23002
	Code_UnsupportedOp              Code = -23003
	Code_Unimplemented              Code = -23004
	Code_Timeout                    Code = -23005
	Code_ShuttingDown               Code = -23006
	Code_NotConnected               Code = -23007
	Code_AuthFailed                 Code = -23008
	Code_LoginFailed                Code = -23009
	Code_Expired                    Code = -23010
	Code_NotReady                   Code = -23011
	Code_Cancelled                  Code = -23012
	Code_ItemNotFound               Code = -23013
	Code_ParseFailed                Code = -23014
	Code_StartupFailed              Code = -23015
	Code_ContextNotReady            Code = -23020
	Code_RequestClosed              Code = -23021
	Code_BadRequest                 Code = -23022
	Code_BadTag                     Code = -23023
	Code_BadValue                   Code = -23024
	Code_AlreadyExists              Code = -23025
	Code_AttrNotFound               Code = -23026
	Code_NothingToCommit            Code = -23027
	Code_CommitFailed               Code = -23028
	Code_StorageFailure             Code = -23030
	Code_MalformedTx                Code = -23032
	Code_BadSchema                  Code = -23040
	Code_DataFailure                Code = -23041
	Code_ExportErr                  Code = -23042
	Code_PinFailed                  Code = -23043
	Code_ProviderErr                Code = -23045
	Code_ViolatesAppendOnly         Code = -23050
	Code_InsufficientPermissions    Code = -23051
	Code_CryptoKitAlreadyRegistered Code = -23100
	Code_UnrecognizedCryptoKit      Code = -23101
	Code_DecryptFailed              Code = -23102
	Code_VerifySignatureFailed      Code = -23103
	Code_BadKeyFormat               Code = -23104
	Code_KeyGenerationFailed        Code = -23105
	Code_KeyringNotFound            Code = -23106
	Code_KeyEntryNotFound           Code = -23107
	Code_HashKitNotFound            Code = -23108
	Code_UnrecognizedCryptOp        Code = -23110
	Code_MarshalFailed              Code = -23111
	Code_UnmarshalFailed            Code = -23112
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:      "Nil",
		-23001: "Unnamed",
		-23002: "AssertFailed",
		-23003: "UnsupportedOp",
		-23004: "Unimplemented",
		-23005: "Timeout",
		-23006: "ShuttingDown",
		-23007: "NotConnected",
		-23008: "AuthFailed",
		-23009: "LoginFailed",
		-23010: "Expired",
		-23011: "NotReady",
		-23012: "Cancelled",
		-23013: "ItemNotFound",
		-23014: "ParseFailed",
		-23015: "StartupFailed",
		-23020: "ContextNotReady",
		-23021: "RequestClosed",
		-23022: "BadRequest",
		-23023: "BadTag",
		-23024: "BadValue",
		-23025: "AlreadyExists",
		-23026: "AttrNotFound",
		-23027: "NothingToCommit",
		-23028: "CommitFailed",
		-23030: "StorageFailure",
		-23032: "MalformedTx",
		-23040: "BadSchema",
		-23041: "DataFailure",
		-23042: "ExportErr",
		-23043: "PinFailed",
		-23045: "ProviderErr",
		-23050: "ViolatesAppendOnly",
		-23051: "InsufficientPermissions",
		-23100: "CryptoKitAlreadyRegistered",
		-23101: "UnrecognizedCryptoKit",
		-23102: "DecryptFailed",
		-23103: "VerifySignatureFailed",
		-23104: "BadKeyFormat",
		-23105: "KeyGenerationFailed",
		-23106: "KeyringNotFound",
		-23107: "KeyEntryNotFound",
		-23108: "HashKitNotFound",
		-23110: "UnrecognizedCryptOp",
		-23111: "MarshalFailed",
		-23112: "UnmarshalFailed",
	}
	Code_value = map[string]int32{
		"Nil":                        0,
		"Unnamed":                    -23001,
		"AssertFailed":               -23002,
		"UnsupportedOp":              -23003,
		"Unimplemented":              -23004,
		"Timeout":                    -23005,
		"ShuttingDown":               -23006,
		"NotConnected":               -23007,
		"AuthFailed":                 -23008,
		"LoginFailed":                -23009,
		"Expired":                    -23010,
		"NotReady":                   -23011,
		"Cancelled":                  -23012,
		"ItemNotFound":               -23013,
		"ParseFailed":                -23014,
		"StartupFailed":              -23015,
		"ContextNotReady":            -23020,
		"RequestClosed":              -23021,
		"BadRequest":                 -23022,
		"BadTag":                     -23023,
		"BadValue":                   -23024,
		"AlreadyExists":              -23025,
		"AttrNotFound":               -23026,
		"NothingToCommit":            -23027,
		"CommitFailed":               -23028,
		"StorageFailure":             -23030,
		"MalformedTx":                -23032,
		"BadSchema":                  -23040,
		"DataFailure":                -23041,
		"ExportErr":                  -23042,
		"PinFailed":                  -23043,
		"ProviderErr":                -23045,
		"ViolatesAppendOnly":         -23050,
		"InsufficientPermissions":    -23051,
		"CryptoKitAlreadyRegistered": -23100,
		"UnrecognizedCryptoKit":      -23101,
		"DecryptFailed":              -23102,
		"VerifySignatureFailed":      -23103,
		"BadKeyFormat":               -23104,
		"KeyGenerationFailed":        -23105,
		"KeyringNotFound":            -23106,
		"KeyEntryNotFound":           -23107,
		"HashKitNotFound":            -23108,
		"UnrecognizedCryptOp":        -23110,
		"MarshalFailed":              -23111,
		"UnmarshalFailed":            -23112,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_stdlib_status_status_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_stdlib_status_status_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_stdlib_status_status_proto_rawDescGZIP(), []int{0}
}

type Severity int32

const (
	Severity_Error   Severity = 0
	Severity_Warning Severity = 1
	Severity_Info    Severity = 2
	Severity_Debug   Severity = 3
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0: "Error",
		1: "Warning",
		2: "Info",
		3: "Debug",
	}
	Severity_value = map[string]int32{
		"Error":   0,
		"Warning": 1,
		"Info":    2,
		"Debug":   3,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_stdlib_status_status_proto_enumTypes[1].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_stdlib_status_status_proto_enumTypes[1]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_stdlib_status_status_proto_rawDescGZIP(), []int{1}
}

// Status is a general purpose status message.
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=Code,proto3,enum=status.Code" json:"Code,omitempty"`             // numberical code
	Severity      Severity               `protobuf:"varint,2,opt,name=Severity,proto3,enum=status.Severity" json:"Severity,omitempty"` // which log to larget
	Level         int32                  `protobuf:"varint,3,opt,name=Level,proto3" json:"Level,omitempty"`                            // log level, 0 is highest priority
	Message       string                 `protobuf:"bytes,4,opt,name=Message,proto3" json:"Message,omitempty"`                         // human readable message, may be empty
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_stdlib_status_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_stdlib_status_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_stdlib_status_status_proto_rawDescGZIP(), []int{0}
}

func (x *Status) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Nil
}

func (x *Status) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_Error
}

func (x *Status) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_stdlib_status_status_proto protoreflect.FileDescriptor

const file_stdlib_status_status_proto_rawDesc = "" +
	"\n" +
	"\x1astdlib/status/status.proto\x12\x06status\"\x88\x01\n" +
	"\x06Status\x12 \n" +
	"\x04Code\x18\x01 \x01(\x0e2\f.status.CodeR\x04Code\x12,\n" +
	"\bSeverity\x18\x02 \x01(\x0e2\x10.status.SeverityR\bSeverity\x12\x14\n" +
	"\x05Level\x18\x03 \x01(\x05R\x05Level\x12\x18\n" +
	"\aMessage\x18\x04 \x01(\tR\aMessage*\xf7\t\n" +
	"\x04Code\x12\a\n" +
	"\x03Nil\x10\x00\x12\x14\n" +
	"\aUnnamed\x10\xa7\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x19\n" +
	"\fAssertFailed\x10\xa6\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1a\n" +
	"\rUnsupportedOp\x10\xa5\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1a\n" +
	"\rUnimplemented\x10\xa4\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x14\n" +
	"\aTimeout\x10\xa3\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x19\n" +
	"\fShuttingDown\x10\xa2\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x19\n" +
	"\fNotConnected\x10\xa1\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x17\n" +
	"\n" +
	"AuthFailed\x10\xa0\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x18\n" +
	"\vLoginFailed\x10\x9f\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x14\n" +
	"\aExpired\x10\x9e\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x15\n" +
	"\bNotReady\x10\x9d\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x16\n" +
	"\tCancelled\x10\x9c\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x19\n" +
	"\fItemNotFound\x10\x9b\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x18\n" +
	"\vParseFailed\x10\x9a\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1a\n" +
	"\rStartupFailed\x10\x99\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1c\n" +
	"\x0fContextNotReady\x10\x94\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1a\n" +
	"\rRequestClosed\x10\x93\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x17\n" +
	"\n" +
	"BadRequest\x10\x92\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x13\n" +
	"\x06BadTag\x10\x91\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x15\n" +
	"\bBadValue\x10\x90\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1a\n" +
	"\rAlreadyExists\x10\x8f\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x19\n" +
	"\fAttrNotFound\x10\x8e\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1c\n" +
	"\x0fNothingToCommit\x10\x8d\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x19\n" +
	"\fCommitFailed\x10\x8c\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1b\n" +
	"\x0eStorageFailure\x10\x8a\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x18\n" +
	"\vMalformedTx\x10\x88\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x16\n" +
	"\tBadSchema\x10\x80\xcc\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x18\n" +
	"\vDataFailure\x10\xff\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x16\n" +
	"\tExportErr\x10\xfe\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x16\n" +
	"\tPinFailed\x10\xfd\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x18\n" +
	"\vProviderErr\x10\xfb\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1f\n" +
	"\x12ViolatesAppendOnly\x10\xf6\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12$\n" +
	"\x17InsufficientPermissions\x10\xf5\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12'\n" +
	"\x1aCryptoKitAlreadyRegistered\x10\xc4\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\"\n" +
	"\x15UnrecognizedCryptoKit\x10\xc3\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1a\n" +
	"\rDecryptFailed\x10\xc2\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\"\n" +
	"\x15VerifySignatureFailed\x10\xc1\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x19\n" +
	"\fBadKeyFormat\x10\xc0\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12 \n" +
	"\x13KeyGenerationFailed\x10\xbf\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1c\n" +
	"\x0fKeyringNotFound\x10\xbe\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1d\n" +
	"\x10KeyEntryNotFound\x10\xbd\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1c\n" +
	"\x0fHashKitNotFound\x10\xbc\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12 \n" +
	"\x13UnrecognizedCryptOp\x10\xba\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1a\n" +
	"\rMarshalFailed\x10\xb9\xcb\xfe\xff\xff\xff\xff\xff\xff\x01\x12\x1c\n" +
	"\x0fUnmarshalFailed\x10\xb8\xcb\xfe\xff\xff\xff\xff\xff\xff\x01*7\n" +
	"\bSeverity\x12\t\n" +
	"\x05Error\x10\x00\x12\v\n" +
	"\aWarning\x10\x01\x12\b\n" +
	"\x04Info\x10\x02\x12\t\n" +
	"\x05Debug\x10\x03BQZ3github.com/art-media-platform/amp.SDK/stdlib/status\xaa\x02\x19art.media.platform.statusb\x06proto3"

var (
	file_stdlib_status_status_proto_rawDescOnce sync.Once
	file_stdlib_status_status_proto_rawDescData []byte
)

func file_stdlib_status_status_proto_rawDescGZIP() []byte {
	file_stdlib_status_status_proto_rawDescOnce.Do(func() {
		file_stdlib_status_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_stdlib_status_status_proto_rawDesc), len(file_stdlib_status_status_proto_rawDesc)))
	})
	return file_stdlib_status_status_proto_rawDescData
}

var file_stdlib_status_status_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_stdlib_status_status_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_stdlib_status_status_proto_goTypes = []any{
	(Code)(0),      // 0: status.Code
	(Severity)(0),  // 1: status.Severity
	(*Status)(nil), // 2: status.Status
}
var file_stdlib_status_status_proto_depIdxs = []int32{
	0, // 0: status.Status.Code:type_name -> status.Code
	1, // 1: status.Status.Severity:type_name -> status.Severity
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_stdlib_status_status_proto_init() }
func file_stdlib_status_status_proto_init() {
	if File_stdlib_status_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_stdlib_status_status_proto_rawDesc), len(file_stdlib_status_status_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_stdlib_status_status_proto_goTypes,
		DependencyIndexes: file_stdlib_status_status_proto_depIdxs,
		EnumInfos:         file_stdlib_status_status_proto_enumTypes,
		MessageInfos:      file_stdlib_status_status_proto_msgTypes,
	}.Build()
	File_stdlib_status_status_proto = out.File
	file_stdlib_status_status_proto_goTypes = nil
	file_stdlib_status_status_proto_depIdxs = nil
}
